# STEP 01 — 개발환경 확인

## 작업 목표
실제 데이터 수집을 시작하기 전에, 지금 사용 중인 Notebook 실행 환경이 정상인지 확인합니다.

## 확인 항목
- Python 버전이 올바른지
- 운영체제(Platform) 정보
- `pandas`, `requests`, `BeautifulSoup` 라이브러리가 문제없이 import 되는지

## 완료 조건
- 아래 코드 셀이 모두 에러 없이 실행된다
- 커널이 `Python (ax-job-agent)`로 선택되어 있다
- 출력된 Python 경로가 `.venv` 안에 있는 것을 사람이 직접 확인한다

In [1]:
# Python 버전과 운영체제(Platform) 정보를 확인합니다.
import sys
import platform

print("Python:", sys.version)
print("Platform:", platform.platform())
print("Python 실행 경로:", sys.executable)

Python: 3.14.6 (tags/v3.14.6:c63aec6, Jun 10 2026, 10:26:10) [MSC v.1944 64 bit (AMD64)]
Platform: Windows-11-10.0.26200-SP0
Python 실행 경로: c:\dev\claude-code-agent-course\chapter11\ax-job-agent\.venv\Scripts\python.exe

In [4]:
# pandas, requests, BeautifulSoup이 정상적으로 import 되는지 확인합니다.
import pandas as pd
import requests
from bs4 import BeautifulSoup

print("pandas:", pd.__version__)
print("requests:", requests.__version__)
print("BeautifulSoup import: OK")

pandas: 3.0.6
requests: 2.34.2
BeautifulSoup import: OK

In [2]:
import sys
print(sys.executable)

c:\dev\claude-code-agent-course\chapter11\ax-job-agent\.venv\Scripts\python.exe

In [3]:
import sys
!{sys.executable} -m pip install pandas requests beautifulsoup4

Requirement already satisfied: pandas in c:\dev\claude-code-agent-course\chapter11\ax-job-agent\.venv\Lib\site-packages (3.0.6)
Requirement already satisfied: requests in c:\dev\claude-code-agent-course\chapter11\ax-job-agent\.venv\Lib\site-packages (2.34.2)
Requirement already satisfied: beautifulsoup4 in c:\dev\claude-code-agent-course\chapter11\ax-job-agent\.venv\Lib\site-packages (4.15.0)
Requirement already satisfied: numpy>=2.3.3 in c:\dev\claude-code-agent-course\chapter11\ax-job-agent\.venv\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\dev\claude-code-agent-course\chapter11\ax-job-agent\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\dev\claude-code-agent-course\chapter11\ax-job-agent\.venv\Lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\dev\claude-code-agent-course\chapter11\ax-job-agent\.venv\Lib\site-packages (from requests) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in c:\dev\claude-code-agent-course\chapter11\ax-job-agent\.venv\Lib\site-packages (from requests) (3.20)
Requirement already satisfied: urllib3<3,>=1.26 in c:\dev\claude-code-agent-course\chapter11\ax-job-agent\.venv\Lib\site-packages (from requests) (2.8.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\dev\claude-code-agent-course\chapter11\ax-job-agent\.venv\Lib\site-packages (from requests) (2026.7.22)
Requirement already satisfied: soupsieve>=1.6.1 in c:\dev\claude-code-agent-course\chapter11\ax-job-agent\.venv\Lib\site-packages (from beautifulsoup4) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\dev\claude-code-agent-course\chapter11\ax-job-agent\.venv\Lib\site-packages (from beautifulsoup4) (4.16.0)
Requirement already satisfied: six>=1.5 in c:\dev\claude-code-agent-course\chapter11\ax-job-agent\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

### 실행 결과 해석 / 분석 / 요약

- 현재 Jupyter Notebook은 프로젝트의 `.venv` 가상환경을 정상적으로 사용하고 있다.
- Python과 Windows 환경 정보가 정상적으로 출력되었다.
- pandas, requests, BeautifulSoup 라이브러리가 모두 정상적으로 import되었다.
- 따라서 STEP 01 개발환경 확인은 완료되었다.
- 다음 단계인 STEP 02 수집 데이터 명세로 진행할 수 있다.

### STEP 02. 수집 데이터 명세

### 작업 계획

이번 단계에서는 실제 크롤링 코드를 작성하기 전에
채용공고 데이터를 어떤 구조로 저장할지 먼저 정의한다.

기준:
- DataFrame의 한 행은 채용공고 1건을 의미한다.
- 처음에는 검색 결과에서 안정적으로 얻을 수 있는 정보만 사용한다.
- 아직 실제 웹페이지 수집은 하지 않는다.

In [1]:
import pandas as pd

columns_spec = pd.DataFrame({
    "컬럼명": [
        "company_name",
        "job_title",
        "career",
        "location",
        "posted_date",
        "closing_date",
        "job_url",
        "search_keyword",
        "collected_at"
    ],
    "의미": [
        "회사명",
        "공고 제목",
        "경력 조건",
        "근무 지역",
        "등록일",
        "마감일",
        "공고 URL",
        "공고를 발견한 검색어",
        "수집 시각"
    ]
})

columns_spec

              컬럼명           의미
0    company_name          회사명
1       job_title        공고 제목
2          career        경력 조건
3        location        근무 지역
4     posted_date          등록일
5    closing_date          마감일
6         job_url       공고 URL
7  search_keyword  공고를 발견한 검색어
8    collected_at        수집 시각

### 실행 결과 해석 / 분석 / 요약

- DataFrame의 한 행은 채용공고 1건을 의미한다.
- 초기 수집 컬럼은 회사명, 공고 제목, 경력 조건, 근무 지역, 등록일, 마감일, URL, 검색어, 수집 시각로 정의했다.
- 실제 크롤링 전에 데이터 구조를 먼저 정했기 때문에 이후 수집 결과가 이 기준에 맞는지 검증할 수 있다.
- 아직 실제 채용공고 수집은 수행하지 않았다.

### STEP 03. 채용공고 페이지 접근 테스트

### 작업 계획

이번 단계에서는 실제 데이터 수집 전에
채용공고 검색 페이지에 HTTP 요청이 가능한지 확인한다.

확인할 항목:
- HTTP 상태 코드
- 응답 Content-Type
- 응답 길이
- HTML 문서가 정상적으로 반환되는지

아직 여러 페이지를 반복 수집하지 않는다.

In [2]:
import requests

url = "https://www.jobkorea.co.kr/Search/?stext=AI"

response = requests.get(url, timeout=10)

print("상태 코드:", response.status_code)
print("Content-Type:", response.headers.get("Content-Type"))
print("응답 길이:", len(response.text))
print("HTML 시작 부분:")
print(response.text[:500])

상태 코드: 200
Content-Type: text/html
응답 길이: 3675
HTML 시작 부분:
<!DOCTYPE html><html lang="ko"><head><meta charset="utf-8" /><meta http-equiv="X-UA-Compatible" content="IE=edge" /><title>ë³´ìì ì±</title><style> *{margin:0;padding:0;box-sizing:border-box}body{font-family:'NanumGothic','ëëê³ ë','Malgun Gothic','ë§ì ê³ ë',sans-serif;background-color:#f8f9fa;line-height:1.6;color:#333;min-height:100vh;display:flex;flex-direction:column}.container{max-width:800px;margin:50px auto;padding:40px 20px;background-color:#fff;box-shadow:0 2px 10px rgba(0,

### 실행 결과 해석 / 분석 / 요약

- HTTP 요청 자체는 상태 코드 200으로 성공했다.
- Content-Type도 text/html로 확인되었다.
- 하지만 반환된 HTML은 실제 채용공고 검색 결과가 아니라 보안정책 페이지였다.
- 따라서 현재 requests 방식으로는 원하는 채용공고 데이터를 정상적으로 가져올 수 없다고 판단했다.
- 상태 코드 200만으로 정상적인 데이터 수집이라고 판단하면 안 된다는 점을 확인했다.
- 다음 단계에서는 사이트 제한을 우회하기보다 샘플 HTML 또는 CSV 사용 여부를 결정해야 한다.

### STEP 04. 소량 샘플 데이터 준비

### 작업 계획

STEP 03에서 잡코리아가 실제 검색결과 대신 보안정책 페이지를 반환했다.

이번 단계에서는 사이트 제한을 우회하지 않고,
파이프라인 학습을 계속하기 위해 소량의 샘플 채용공고 데이터를 만든다.

확인할 항목:
- 채용공고 5건 생성
- STEP 02에서 정의한 컬럼 사용
- DataFrame 생성 여부 확인

주의:
- 아래 데이터는 실제 수집 결과가 아니라 실습용 샘플 데이터이다.

In [3]:
import pandas as pd

sample_jobs = [
    {
        "company_name": "회사A",
        "job_title": "AI Engineer",
        "career": "신입",
        "location": "서울",
        "posted_date": "2026-09-20",
        "closing_date": "2026-10-10",
        "job_url": "https://example.com/job/1",
        "search_keyword": "AI",
        "collected_at": "2026-09-23"
    },
    {
        "company_name": "회사B",
        "job_title": "데이터 분석가",
        "career": "경력 1~3년",
        "location": "경기",
        "posted_date": "2026-09-21",
        "closing_date": "2026-10-15",
        "job_url": "https://example.com/job/2",
        "search_keyword": "데이터 분석",
        "collected_at": "2026-09-23"
    },
    {
        "company_name": "회사C",
        "job_title": "AX Engineer",
        "career": "신입/경력",
        "location": "서울",
        "posted_date": "2026-09-21",
        "closing_date": "2026-10-20",
        "job_url": "https://example.com/job/3",
        "search_keyword": "AX",
        "collected_at": "2026-09-23"
    },
    {
        "company_name": "회사D",
        "job_title": "LLM 서비스 개발자",
        "career": "경력 3년 이상",
        "location": "서울",
        "posted_date": "2026-09-22",
        "closing_date": "2026-10-12",
        "job_url": "https://example.com/job/4",
        "search_keyword": "LLM",
        "collected_at": "2026-09-23"
    },
    {
        "company_name": "회사E",
        "job_title": "Machine Learning Engineer",
        "career": "신입",
        "location": "부산",
        "posted_date": "2026-09-22",
        "closing_date": "2026-10-18",
        "job_url": "https://example.com/job/5",
        "search_keyword": "Machine Learning",
        "collected_at": "2026-09-23"
    }
]

df_jobs = pd.DataFrame(sample_jobs)

print("데이터 크기:", df_jobs.shape)
display(df_jobs)

데이터 크기: (5, 9)

,company_name,job_title,career,location,posted_date,closing_date,job_url,search_keyword,collected_at
0,회사A,AI Engineer,신입,서울,2026-09-20,2026-10-10,https://example.com/job/1,AI,2026-09-23
1,회사B,데이터 분석가,경력 1~3년,경기,2026-09-21,2026-10-15,https://example.com/job/2,데이터 분석,2026-09-23
2,회사C,AX Engineer,신입/경력,서울,2026-09-21,2026-10-20,https://example.com/job/3,AX,2026-09-23
3,회사D,LLM 서비스 개발자,경력 3년 이상,서울,2026-09-22,2026-10-12,https://example.com/job/4,LLM,2026-09-23
4,회사E,Machine Learning Engineer,신입,부산,2026-09-22,2026-10-18,https://example.com/job/5,Machine Learning,2026-09-23

### 실행 결과 해석 / 분석 / 요약

- 실습용 채용공고 5건이 정상적으로 DataFrame으로 생성되었다.
- 각 행은 채용공고 1건을 의미한다.
- STEP 02에서 정의한 9개 컬럼이 모두 포함되어 있다.
- 현재 데이터는 실제 크롤링 결과가 아니라 이후 전처리와 분석을 연습하기 위한 샘플 데이터이다.
- 다음 단계에서는 컬럼 구조, 결측값, 중복 여부를 확인한다.

### STEP 05. DataFrame 기본 구조 확인

### 작업 계획

STEP 04에서 만든 `df_jobs`의 기본 구조가 예상대로 만들어졌는지 확인한다.

확인할 항목:
- 행과 열의 개수
- 컬럼 목록
- 상위 데이터
- 결측값
- `job_url` 기준 중복 여부

아직 데이터를 수정하거나 전처리하지 않는다.
이번 단계는 현재 상태를 확인하는 단계이다.

In [4]:
print("데이터 크기:", df_jobs.shape)

print("\n컬럼 목록:")
print(df_jobs.columns.tolist())

print("\n상위 5개 데이터:")
display(df_jobs.head())

print("\n결측값 개수:")
display(df_jobs.isna().sum())

print("\njob_url 중복 개수:")
print(df_jobs.duplicated(subset=["job_url"]).sum())

데이터 크기: (5, 9)

컬럼 목록:
['company_name', 'job_title', 'career', 'location', 'posted_date', 'closing_date', 'job_url', 'search_keyword', 'collected_at']

상위 5개 데이터:

,company_name,job_title,career,location,posted_date,closing_date,job_url,search_keyword,collected_at
0,회사A,AI Engineer,신입,서울,2026-09-20,2026-10-10,https://example.com/job/1,AI,2026-09-23
1,회사B,데이터 분석가,경력 1~3년,경기,2026-09-21,2026-10-15,https://example.com/job/2,데이터 분석,2026-09-23
2,회사C,AX Engineer,신입/경력,서울,2026-09-21,2026-10-20,https://example.com/job/3,AX,2026-09-23
3,회사D,LLM 서비스 개발자,경력 3년 이상,서울,2026-09-22,2026-10-12,https://example.com/job/4,LLM,2026-09-23
4,회사E,Machine Learning Engineer,신입,부산,2026-09-22,2026-10-18,https://example.com/job/5,Machine Learning,2026-09-23

결측값 개수:

company_name      0
job_title         0
career            0
location          0
posted_date       0
closing_date      0
job_url           0
search_keyword    0
collected_at      0
dtype: int64

job_url 중복 개수:
0

### 실행 결과 해석 / 분석 / 요약

- DataFrame의 크기는 5행 × 9열이다.
- STEP 02에서 정의한 9개 컬럼이 모두 존재한다.
- 상위 데이터를 확인한 결과 각 행이 채용공고 1건 형태로 정상적으로 구성되어 있다.
- 모든 컬럼의 결측값은 0개이다.
- `job_url` 기준 중복 공고는 0건이다.
- 현재 샘플 데이터의 기본 구조에는 이상이 없으며, 다음 단계에서 데이터 타입 확인과 전처리를 진행할 수 있다.

### STEP 06. 전처리 / 중복 제거

### 작업 계획

STEP 05에서 `df_jobs`의 기본 구조에 이상이 없음을 확인했다.
이번 단계에서는 이후 분석에 사용할 수 있도록 데이터를 정리(전처리)한다.

할 일:
- 전처리 전 `df_jobs`의 크기(shape)와 데이터 타입(dtypes) 확인
- 날짜 컬럼(`posted_date`, `closing_date`, `collected_at`)을 datetime 타입으로 변환
  - `pd.to_datetime(..., errors="coerce")` 사용 → 날짜로 바꿀 수 없는 값은 `NaT`(날짜 결측값)가 된다
- 문자열 컬럼(`company_name`, `job_title`, `career`, `location`, `job_url`, `search_keyword`)의 앞뒤 공백 제거
- `job_url` 기준 중복 제거
- 전처리 후 shape / dtypes / 결측값 / `job_url` 중복 개수 재확인

이번 단계에서 하지 않는 것:
- STEP 07 신규 공고 판별
- 실제 크롤링 재시도, Gemini API, Slack / Gmail

완료 조건:
- 날짜 컬럼 3개의 dtype이 datetime으로 바뀐다
- 날짜 변환 후 결측값(`NaT`)이 새로 생기지 않는다
- `job_url` 중복 개수가 0이다

In [1]:
# ----- 1) 전처리 전 상태 확인 -----
shape_before = df_jobs.shape
print("[전처리 전] 데이터 크기:", shape_before)
print("\n[전처리 전] 데이터 타입:")
display(df_jobs.dtypes)

# ----- 2) 날짜 컬럼을 datetime 타입으로 변환 -----
date_columns = ["posted_date", "closing_date", "collected_at"]
for col in date_columns:
    # errors="coerce": 날짜로 바꿀 수 없는 값은 에러를 내지 않고 NaT(날짜 결측값)로 바꾼다
    df_jobs[col] = pd.to_datetime(df_jobs[col], errors="coerce")

# ----- 3) 문자열 컬럼의 앞뒤 공백 제거 -----
text_columns = ["company_name", "job_title", "career", "location", "job_url", "search_keyword"]
for col in text_columns:
    # .str.strip(): " 회사A " → "회사A" 처럼 앞뒤 공백만 제거한다
    df_jobs[col] = df_jobs[col].str.strip()

# ----- 4) job_url 기준 중복 제거 -----
# 같은 job_url이 여러 번 있으면 첫 번째 행만 남긴다
df_jobs = df_jobs.drop_duplicates(subset=["job_url"])

# ----- 5) 전처리 후 상태 확인 -----
print("\n[전처리 후] 데이터 크기:", df_jobs.shape)
print("제거된 행 수:", shape_before[0] - df_jobs.shape[0])

print("\n[전처리 후] 데이터 타입:")
display(df_jobs.dtypes)

print("\n[전처리 후] 결측값 개수:")
display(df_jobs.isna().sum())

print("\n[전처리 후] job_url 중복 개수:")
print(df_jobs.duplicated(subset=["job_url"]).sum())

[전처리 전] 데이터 크기: (5, 9)

[전처리 전] 데이터 타입:

company_name      str
job_title         str
career            str
location          str
posted_date       str
closing_date      str
job_url           str
search_keyword    str
collected_at      str
dtype: object

[전처리 후] 데이터 크기: (5, 9)
제거된 행 수: 0

[전처리 후] 데이터 타입:

company_name                 str
job_title                    str
career                       str
location                     str
posted_date       datetime64[us]
closing_date      datetime64[us]
job_url                      str
search_keyword               str
collected_at      datetime64[us]
dtype: object

[전처리 후] 결측값 개수:

company_name      0
job_title         0
career            0
location          0
posted_date       0
closing_date      0
job_url           0
search_keyword    0
collected_at      0
dtype: int64

[전처리 후] job_url 중복 개수:
0

### 실행 결과 해석 / 분석 / 요약

- 셀이 에러 없이 실행되었다.
- 전처리 전 데이터 크기는 5행 × 9열이고, 9개 컬럼이 모두 문자열(`str`) 타입이었다.
  - 즉 날짜처럼 보이는 `"2026-09-20"`도 pandas 입장에서는 그냥 글자였다.
- 날짜 컬럼 3개(`posted_date`, `closing_date`, `collected_at`)는 `datetime64[us]` 타입으로 변환되었다.
  - 이제 날짜 비교, 마감일까지 남은 기간 계산 같은 날짜 연산이 가능하다.
  - 변환 후 결측값이 0개이므로 `errors="coerce"` 때문에 `NaT`가 된 값은 없다. 즉 모든 날짜가 정상적으로 변환되었다.
- 문자열 컬럼 6개의 앞뒤 공백 제거를 적용했다. 샘플 데이터는 원래 공백이 없어서 값이 달라지지는 않았지만, 실제 수집 데이터에 대비한 기본 정리 절차를 갖추었다.
- `job_url` 기준 중복 제거 결과 제거된 행은 0개였고, 전처리 후 크기도 5행 × 9열로 그대로이다.
- 전처리 후 모든 컬럼의 결측값은 0개, `job_url` 중복 개수도 0개이다.
- 참고: pandas 3.x에서는 문자열 컬럼의 dtype이 `object` 대신 `str`로 표시된다.
- 결론: 전처리 / 중복 제거가 정상 완료되었으며, 다음 단계인 STEP 07 신규 공고 판별로 진행할 수 있다.

### STEP 07. 신규 공고 판별

### 작업 계획

STEP 06에서 전처리를 마친 `df_jobs`(공고 5건)를 이전 실행 이력과 비교해
**이번에 처음 나타난 공고(신규 공고)**만 골라낸다.

판별 기준:
- 1차 기준은 `job_url`이다. (URL이 같으면 같은 공고로 본다)
- 이전 이력에 있던 URL → 기존 공고
- 이전 이력에 없던 URL → 신규 공고

이전 실행 이력:
- 아직 실제 이력 파일이나 데이터베이스가 없으므로, 간단한 샘플 목록 `previous_urls`를 직접 만든다.
- 이전 이력에 `https://example.com/job/1`, `https://example.com/job/2`가 있었다고 가정한다.

확인할 항목:
- 이전 이력 URL 수
- 전체 공고 수 / 기존 공고 수 / 신규 공고 수
- 신규 공고의 `company_name`, `job_title`, `job_url`

이번 단계에서 하지 않는 것:
- STEP 08 기본 분석
- CSV 저장
- 실제 크롤링, Gemini API, Slack / Gmail

완료 조건:
- 기존 공고 수 + 신규 공고 수 = 전체 공고 수
- 신규 공고가 `new_jobs` DataFrame으로 만들어진다
- 신규 공고 목록에 이전 이력 URL이 들어 있지 않다

In [1]:
# ----- 1) 이전 실행 이력(샘플) 만들기 -----
# 실제로는 이전 실행 때 저장해 둔 URL 목록을 불러와야 하지만,
# 지금은 연습을 위해 "이전에 이미 봤던 공고 URL" 2개를 직접 적어 둔다.
previous_urls = [
    "https://example.com/job/1",
    "https://example.com/job/2",
]
print("이전 이력 URL 수:", len(previous_urls))

# ----- 2) job_url이 이전 이력에 있는지 비교하기 -----
# isin(): 각 행의 job_url이 previous_urls 목록 안에 "들어 있는지" 한 번에 검사한다.
#         들어 있으면 True(기존 공고), 없으면 False(신규 공고)가 된다.
#         for 문으로 한 행씩 비교하지 않아도 되어서 간단하고 빠르다.
is_existing = df_jobs["job_url"].isin(previous_urls)

# ----- 3) 기존 공고 / 신규 공고 구분하기 -----
existing_jobs = df_jobs[is_existing]   # True인 행만 → 기존 공고
new_jobs = df_jobs[~is_existing]       # ~ 는 True/False를 뒤집는다 → 신규 공고

# ----- 4) 결과 출력 -----
print("\n전체 공고 수:", len(df_jobs))
print("기존 공고 수:", len(existing_jobs))
print("신규 공고 수:", len(new_jobs))

print("\n신규 공고 목록:")
display(new_jobs[["company_name", "job_title", "job_url"]])

이전 이력 URL 수: 2

전체 공고 수: 5
기존 공고 수: 2
신규 공고 수: 3

신규 공고 목록:

  company_name                  job_title                    job_url
2          회사C                AX Engineer  https://example.com/job/3
3          회사D                LLM 서비스 개발자  https://example.com/job/4
4          회사E  Machine Learning Engineer  https://example.com/job/5

### 실행 결과 해석 / 분석 / 요약

- 셀이 에러 없이 실행되었다.
- 이전 실행 이력(`previous_urls`)에는 URL 2개(`job/1`, `job/2`)가 있다.
- 현재 `df_jobs`의 전체 공고는 5건이다.
- `isin()`으로 비교한 결과:
  - 기존 공고(이전 이력에 있던 URL): 2건 → 회사A, 회사B
  - 신규 공고(이전 이력에 없던 URL): 3건 → 회사C, 회사D, 회사E
- 기존 2건 + 신규 3건 = 전체 5건이므로 빠지거나 겹친 공고가 없다.
- `new_jobs`에는 `job/3`, `job/4`, `job/5`만 들어 있고, 이전 이력 URL은 포함되지 않았다.
- 참고: 신규 공고의 행 번호(index)가 2, 3, 4로 남아 있는 것은 원래 `df_jobs`에서의 위치를 그대로 유지했기 때문이며 문제는 아니다.
- 한계: 지금의 `previous_urls`는 직접 만든 샘플이다. 실제 운영에서는 이번 실행의 URL을 저장해 두었다가 다음 실행 때 불러와야 한다. (저장은 이후 단계에서 진행)
- 결론: `job_url` 기준 신규 공고 판별이 정상 동작하며, 다음 단계인 STEP 08 기본 분석으로 진행할 수 있다.

### STEP 07-A. 실제 JobKorea 소량 크롤링 검증

### 작업 계획

STEP 04~07은 직접 만든 **샘플 데이터**로 파이프라인을 연습했다. (이 기록은 그대로 보존한다)
이번 단계에서는 샘플이 아니라 **실제 JobKorea 검색 결과 웹페이지**에서 채용공고를 소량 읽어 올 수 있는지 검증한다.

사용 URL:
- `https://www.jobkorea.co.kr/Search/?stext=ax&tabType=recruit` (검색어 `ax`, 1페이지)

처음부터 여러 페이지를 수집하지 않는 이유:
- 한 페이지에서 정확히 읽는 방법이 확인되지 않았는데 페이지를 늘리면, 틀린 데이터만 많아진다.
- 짧은 시간에 요청을 많이 보내면 사이트에 부담을 주고 차단될 수 있다.
- 그래서 **검색어 1개 · 페이지 1개 · 최대 5건**만 읽는다.

상태 코드 200만으로 성공 판단을 하면 안 되는 이유:
- STEP 03에서 상태 코드는 200이었지만, 실제로는 **보안정책(접속 제한) 페이지**가 돌아왔다.
- 그래서 상태 코드와 함께 Content-Type, 응답 길이, HTML `title`, "채용공고"/"AX" 문자열 포함 여부를 같이 확인한다.
- 기본 요청이 보안정책 페이지를 받으면, 일반 브라우저 User-Agent 헤더를 붙여 **딱 1회만** 다시 확인한다. (반복 재시도·우회 기법은 사용하지 않는다)

HTML 구조를 먼저 확인해야 하는 이유:
- 브라우저 화면과 HTML 코드 구조는 다를 수 있어서, 선택자를 추측하면 엉뚱한 값을 읽을 수 있다.
- 이번에는 실제 응답 HTML에서 공고 링크(`/Recruit/GI_Read/번호`)를 찾고, 그 부모 요소를 거슬러 올라가
  공고 1건을 감싸는 반복 블록(`div[data-sentry-component="CardJob"]`)을 먼저 확인한 뒤 선택자를 정했다.

날짜 데이터를 가져오는 방법:
- 화면 카드 HTML에는 등록일/마감일 **텍스트가 직접 들어 있지 않다.**
- 하지만 같은 HTML 응답 안의 `<script>`(Next.js가 심어 둔 `self.__next_f.push(...)` 데이터)에 공고별 JSON이 들어 있고, 여기에 날짜가 있다.
- 이 프로젝트에서는 **지원 제출 기간**이 중요하므로 다음 값을 사용한다.
  - 지원 제출 시작일 → `applicationPeriod.start`
  - 지원 제출 마감일 → `applicationPeriod.end`
- `createdAt`은 공고가 사이트에 **등록된 시각**이라 지원 기간과 다를 수 있으므로 사용하지 않는다.
  (예: 에스코어 공고는 `createdAt`=07-15, `applicationPeriod.start`=07-01)
- 카드 순서와 JSON 순서에 기대지 않고, **공고 ID**(`job_url` 끝의 숫자)로 카드와 JSON을 짝지어 날짜를 붙인다.

컬럼 의미 정의 (컬럼명은 STEP 02 명세를 유지):
- `posted_date` = 이번 프로젝트에서는 **지원 제출 시작일**을 의미한다. (`applicationPeriod.start`의 날짜 부분, 예: `2026-09-21`)
- `closing_date` = **지원 제출 마감일** (`applicationPeriod.end`의 날짜 + 시:분, 예: `2026-10-01 23:00`)
- 참고: 이름과 의미를 맞추기 위해, 이후 전체 리팩터링 단계에서 `application_start_date` / `application_end_date`로 바꿀 수 있다.
- `search_keyword` = `ax`, `collected_at` = 이번에 페이지를 받아 온 시각

추출 결과를 사람이 브라우저와 비교해야 하는 이유:
- 코드가 에러 없이 실행돼도 다른 칸의 글자를 읽었을 수 있다.
- 출력된 제목·회사명·지역·경력·날짜·URL을 브라우저 화면과 직접 비교해야 "제대로 읽었다"고 판단할 수 있다.

이번 단계에서 하지 않는 것:
- 여러 페이지 / 여러 검색어 / 상세 페이지 반복 요청
- DataFrame 생성(다음 STEP 07-B에서 확인), CSV·JSON 저장, 신규 공고 판별, 분석
- Gemini API, Slack / Gmail

성공 기준:
- 실제 검색 결과 HTML을 받았음을 확인한다
- 반복되는 공고 블록을 확인한다
- 최대 5건을 추출한다
- 최소 `company_name` 또는 `job_title`을 확인한다
- 가능하면 `job_url`도 확인한다
- `posted_date` / `closing_date`에 `applicationPeriod.start` / `end` 값이 들어간다
- 브라우저 화면과 비교할 수 있는 형태로 출력한다

In [1]:
import re
import json
from datetime import datetime

import requests
from bs4 import BeautifulSoup

url = "https://www.jobkorea.co.kr/Search/?stext=ax&tabType=recruit"
search_keyword = "ax"
MAX_JOBS = 5  # 이번 STEP에서는 최대 5건만 읽는다


# 응답이 "실제 검색 결과"인지 확인하는 함수
# 상태 코드 200이어도 보안정책(접속 제한) 페이지일 수 있으므로 title과 본문 문자열까지 확인한다
def check_response(response):
    response.encoding = "utf-8"  # 한글이 깨지지 않도록 인코딩 지정
    soup = BeautifulSoup(response.text, "html.parser")
    title = soup.title.get_text(strip=True) if soup.title else None
    is_blocked = "보안정책" in response.text
    is_search_result = ("채용공고" in (title or "")) and ("AX" in response.text.upper())

    print("  상태 코드:", response.status_code)
    print("  Content-Type:", response.headers.get("Content-Type"))
    print("  응답 길이:", len(response.text))
    print("  HTML title:", title)
    print("  보안정책 페이지 여부:", is_blocked)
    print("  실제 검색 결과 여부:", is_search_result)
    return soup, is_search_result


# ----- 1) 가장 단순한 방식으로 1차 요청 -----
print("[1차 요청] requests.get() 기본 요청")
response = requests.get(url, timeout=10)
response.raise_for_status()
soup, is_search_result = check_response(response)

# ----- 2) 1차 요청이 보안정책 페이지일 때만, 일반 브라우저 User-Agent로 1회 추가 테스트 -----
used_user_agent = False
if not is_search_result:
    print("\n[2차 요청] 일반 브라우저 User-Agent 헤더를 붙여 1회만 다시 요청")
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                      "(KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"
    }
    response = requests.get(url, headers=headers, timeout=10)
    response.raise_for_status()
    soup, is_search_result = check_response(response)
    used_user_agent = True

# 수집 시각: 이번에 페이지를 받아 온 시각
collected_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

# ----- 3) 실제 검색 결과가 아니면 여기서 중단 (재시도하지 않는다) -----
jobs = []
if not is_search_result:
    print("\n실제 검색 결과 HTML을 받지 못했습니다. 추출을 진행하지 않습니다.")
else:
    # ----- 4) Next.js script 안에서 공고 목록 JSON 찾기 -----
    # 화면 카드에는 날짜 텍스트가 없지만, 같은 HTML 안의 <script>에
    # self.__next_f.push([1, "...문자열..."]) 형태로 공고 데이터(JSON)가 들어 있다
    period_by_id = {}  # 공고 ID별 applicationPeriod 매핑: {"50032017": {"start": ..., "end": ...}}
    for script in soup.find_all("script"):
        text = script.string or ""
        if "applicationPeriod" not in text:
            continue
        match = re.match(r'self\.__next_f\.push\(\[1,(".*")\]\)', text, re.S)
        if not match:
            continue
        # 따옴표로 감싼 JavaScript 문자열 → 일반 문자열로 풀기
        payload = json.loads(match.group(1))
        # 문자열 안에서 공고 목록 "content": [ {...}, {...} ] 부분을 찾아 JSON으로 읽기
        for found in re.finditer(r'"content":\[\{"id":', payload):
            start_index = found.start() + len('"content":')
            content, _ = json.JSONDecoder().raw_decode(payload, start_index)
            # 공고 ID별 applicationPeriod 매핑 만들기
            for item in content:
                period_by_id[item["id"]] = item.get("applicationPeriod")
    print("\nJSON에서 찾은 공고 날짜 데이터 수:", len(period_by_id))

    # ----- 5) 반복되는 채용공고 블록 찾기 -----
    # 실제 HTML 확인 결과, 공고 1건은 data-sentry-component="CardJob" 인 div 하나로 감싸져 있었다
    cards = soup.select('div[data-sentry-component="CardJob"]')
    print("찾은 채용공고 후보(CardJob) 수:", len(cards))

    # ----- 6) 최대 5건만 필드 추출 -----
    for card in cards[:MAX_JOBS]:
        # 공고 제목 링크: data-sentry-component="Title" 인 <a>
        title_link = card.select_one('a[data-sentry-component="Title"]')
        # 회사명: 제목 링크 바로 다음에 나오는 <a>(같은 공고 URL) 안의 첫 번째 <span>
        company_link = title_link.find_next("a") if title_link else None
        company_tag = company_link.select_one("span") if company_link else None
        # 근무 지역: 첫 번째 GrayChip(📍 아이콘이 있는 칩) 안의 텍스트
        location_tag = card.select_one('[data-sentry-component="GrayChip"] span.truncate')
        # 경력 조건: "경력3년↑", "신입" 등이 들어 있는 작은 글씨 span
        career_tag = card.select_one("span.flex-shrink-0.text-typo-c1-13")

        # 공고 URL: 뒤에 붙은 ?Oem_Code=...&listno=... 는 검색 위치 추적용이라 제거하고 기본 주소만 남긴다
        job_url = title_link["href"].split("?")[0] if title_link else None

        # 화면 카드와 같은 ID의 날짜 붙이기 (순서가 아니라 공고 ID로 매칭한다)
        # 예: .../GI_Read/50032017 → job_id = "50032017"
        job_id = job_url.rsplit("/", 1)[-1] if job_url else None
        period = period_by_id.get(job_id) or {}
        start_raw = period.get("start")  # 예: "2026-09-21T00:00:00+09:00"
        end_raw = period.get("end")      # 예: "2026-10-01T23:00:00+09:00"

        jobs.append({
            "company_name": company_tag.get_text(strip=True) if company_tag else None,
            "job_title": title_link.get_text(strip=True) if title_link else None,
            "career": career_tag.get_text(strip=True) if career_tag else None,
            "location": location_tag.get_text(strip=True) if location_tag else None,
            # posted_date = 지원 제출 시작일 (applicationPeriod.start의 날짜 부분만)
            "posted_date": start_raw[:10] if start_raw else None,
            # closing_date = 지원 제출 마감일 (applicationPeriod.end의 날짜 + 시:분)
            "closing_date": end_raw[:16].replace("T", " ") if end_raw else None,
            "job_url": job_url,
            "search_keyword": search_keyword,
            "collected_at": collected_at,
        })

        # 원본 값도 함께 보여 주어 잘라 낸 결과와 비교할 수 있게 한다
        print(f"  ID {job_id} 원본 applicationPeriod: start={start_raw}, end={end_raw}")

# ----- 7) 결과 출력 (브라우저 화면과 비교용) -----
print("\nUser-Agent 추가 요청 여부:", used_user_agent)
print("실제 출력한 공고 수:", len(jobs))
for i, job in enumerate(jobs, start=1):
    print(f"\n[{i}]")
    for key, value in job.items():
        print(f"  {key}: {value}")

[1차 요청] requests.get() 기본 요청
  상태 코드: 200
  Content-Type: text/html
  응답 길이: 3186
  HTML title: 보안정책
  보안정책 페이지 여부: True
  실제 검색 결과 여부: False

[2차 요청] 일반 브라우저 User-Agent 헤더를 붙여 1회만 다시 요청

  상태 코드: 200
  Content-Type: text/html; charset=utf-8
  응답 길이: 347641
  HTML title: 'ax' 관련 📢 채용공고 | 총 888건의 검색결과
  보안정책 페이지 여부: False
  실제 검색 결과 여부: True

JSON에서 찾은 공고 날짜 데이터 수: 31
찾은 채용공고 후보(CardJob) 수: 20
  ID 50032017 원본 applicationPeriod: start=2026-09-21T00:00:00+09:00, end=2026-10-01T23:00:00+09:00
  ID 49589368 원본 applicationPeriod: start=2026-07-01T00:00:00+09:00, end=2026-09-30T23:00:00+09:00
  ID 49976564 원본 applicationPeriod: start=2026-09-10T00:00:00+09:00, end=2026-09-29T10:00:00+09:00
  ID 49858859 원본 applicationPeriod: start=2026-08-26T00:00:00+09:00, end=2026-10-25T23:00:00+09:00
  ID 49976547 원본 applicationPeriod: start=2026-09-10T00:00:00+09:00, end=2026-09-29T10:00:00+09:00

User-Agent 추가 요청 여부: True
실제 출력한 공고 수: 5

[1]
  company_name: GS리테일
  job_title: [GS리테일] 9·10월 통합공고(BIZ CLUB팀 경력사원, MD AX 담당, 물류 AX 담당, 보안성 검토 담당)
  career: 경력3년↑
  location: 서울 강남구 외 1
  posted_date: 2026-09-21
  closing_date: 2026-10-01 23:00
  job_url: https://www.jobkorea.co.kr/Recruit/GI_Read/50032017
  search_keyword: ax
  collected_at: 2026-09-23 12:49:05

[2]
  company_name: 에스코어
  job_title: AX 컨설턴트 채용
  career: 경력
  location: 서울 송파구
  posted_date: 2026-07-01
  closing_date: 2026-09-30 23:00
  job_url: https://www.jobkorea.co.kr/Recruit/GI_Read/49589368
  search_keyword: ax
  collected_at: 2026-09-23 12:49:05

[3]
  company_name: ㈜NAVER
  job_title: 광고 프로덕트 기획 경력 채용(AX 광고 예산/과금 구조 설계 담당)
  career: 경력
  location: 경기 성남시
  posted_date: 2026-09-10
  closing_date: 2026-09-29 10:00
  job_url: https://www.jobkorea.co.kr/Recruit/GI_Read/49976564
  search_keyword: ax
  collected_at: 2026-09-23 12:49:05

[4]
  company_name: ㈜슈프리마
  job_title: [슈프리마HQ] HRD & AX 담당자 모집
  career: 경력7년↑
  location: 경기 성남시
  posted_date: 2026-08-26
  closing_date: 2026-10-25 23:00
  job_url: https://www.jobkorea.co.kr/Recruit/GI_Read/49858859
  search_keyword: ax
  collected_at: 2026-09-23 12:49:05

[5]
  company_name: ㈜NAVER
  job_title: 광고 프로덕트 기획 경력 채용(AX 광고 최적화 전략 담당)
  career: 경력
  location: 경기 성남시
  posted_date: 2026-09-10
  closing_date: 2026-09-29 10:00
  job_url: https://www.jobkorea.co.kr/Recruit/GI_Read/49976547
  search_keyword: ax
  collected_at: 2026-09-23 12:49:05

### 실행 결과 해석 / 분석 / 요약

- 사용 URL: `https://www.jobkorea.co.kr/Search/?stext=ax&tabType=recruit`
- 첫 번째 요청 상태 코드: `200` → 하지만 title이 `보안정책`, 응답 길이 3186 → **접속 제한 페이지**였다.
- User-Agent 추가 요청 여부: **예 (1회)** — 일반 브라우저 User-Agent 헤더만 추가했고, 그 외 우회 기법이나 반복 재시도는 쓰지 않았다.
- 최종 Content-Type: `text/html; charset=utf-8`
- 최종 응답 길이: 347641 (실행 시점마다 조금씩 달라질 수 있다)
- HTML title: `'ax' 관련 📢 채용공고 | 총 888건의 검색결과`
- 실제 검색 결과 HTML 여부: **예** (보안정책 문구 없음, title에 "채용공고" 포함)
- 찾은 채용공고 후보 수: 20개 (1페이지 기준)
- 실제 출력한 공고 수: 5건 (`cards[:5]`)
- 사용한 선택자 또는 탐색 방식:
  - 먼저 공고 링크 패턴 `/Recruit/GI_Read/번호`를 찾고, 그 부모 요소를 거슬러 올라가 반복 블록을 확인했다.
  - 공고 블록: `div[data-sentry-component="CardJob"]`
  - 제목: `a[data-sentry-component="Title"]`의 텍스트
  - 회사명: 제목 링크 다음 `<a>` 안의 첫 `<span>`
  - 지역: 첫 번째 `[data-sentry-component="GrayChip"] span.truncate`
  - 경력: `span.flex-shrink-0.text-typo-c1-13`
  - URL: 제목 링크의 `href`에서 `?` 뒤 추적용 파라미터를 제거한 기본 주소
  - 날짜: `self.__next_f.push(...)` script 안 JSON의 `"content": [...]` 공고 목록 → **공고 ID로 카드와 매칭**
- 날짜 데이터 결과:
  - 화면 카드 HTML에는 날짜 텍스트가 직접 없지만, 같은 응답의 Next.js script JSON에는 날짜가 있었다.
  - 지원 제출 시작일 → `applicationPeriod.start` → `posted_date`
    - 이번 프로젝트에서 **`posted_date`는 지원 제출 시작일을 의미한다.** (공고 등록일이 아님)
  - 지원 제출 마감일 → `applicationPeriod.end` → `closing_date`
  - `createdAt`은 사이트 등록 시각이라 사용하지 않았다.
  - 원본 값 예: `start=2026-09-21T00:00:00+09:00`, `end=2026-10-01T23:00:00+09:00`
    → 저장 값: `posted_date=2026-09-21`, `closing_date=2026-10-01 23:00`
    - 모든 값이 한국 시간(`+09:00`)이라 시간대 표기는 떼고, 시작일은 날짜만, 마감일은 날짜 + 시:분만 남겼다.
    - 원본 값은 코드 출력(`원본 applicationPeriod`)에서 함께 확인할 수 있다.
  - JSON에서 날짜가 있는 공고는 31건이었다. 검색 결과 목록 20건과, 별도 목록(`COMPANY_LIST` 쿼리) 11건이 섞여 있었다.
    ID로 매칭하기 때문에 섞여 있어도 문제가 없고, 같은 ID인데 날짜가 다른 경우는 없었다.
  - 5건 모두 JSON에서 같은 ID를 찾아 날짜가 채워졌다. (결측 없음)
- 추출 성공 필드: `company_name`, `job_title`, `career`, `location`, `posted_date`, `closing_date`, `job_url`, `search_keyword`, `collected_at` (9개 모두 값 있음)
- 비어 있는 필드: 없음
- HTML 구조상 특이사항:
  - 기본 `requests.get()`은 차단되고, 브라우저 User-Agent를 붙였을 때만 실제 페이지가 반환됐다.
  - 공고 1건에 같은 URL 링크가 3개(로고·제목·회사명) 있다. 그래서 `<a>` 태그를 세지 않고 `CardJob` 블록 단위로 셌다.
  - 경력 선택자와 script JSON 구조는 사이트 내부 구현이라, 사이트가 바뀌면 깨질 수 있다.
  - "서울 강남구 외 1"처럼 근무지가 여러 곳이면 화면에 보이는 요약 문구가 그대로 저장된다.
  - 비정상적으로 먼 날짜가 존재할 수 있으며, 후속 단계에서 상시채용 표기와의 관계를 별도 검증해야 한다.
    (이번 5건에는 없지만, 같은 페이지 6번째 공고의 `applicationPeriod.end`가 `2070-01-01`이었다. 원본 값을 그대로 둔다)
- 다음 단계 진행 가능 여부: 아래 브라우저 비교를 사람이 확인한 뒤, STEP 07-B에서 DataFrame 전달을 검증한다.

#### 브라우저와 직접 비교할 항목
1. 첫 번째 공고 제목이 브라우저 화면과 일치하는가? (`[GS리테일] 9·10월 통합공고(...)`)
2. 회사명이 일치하는가?
3. `job_url`을 브라우저에서 열면 해당 공고 상세 페이지로 연결되는가?
4. 위치/경력 정보가 실제 화면과 같은가?
5. 화면의 "MM/DD 등록 · MM/DD 마감"이 `posted_date` / `closing_date`와 같은가? (첫 공고: 화면 `09/21 등록 · 10/01 마감`)
6. 공고 순서가 브라우저와 같은가? (광고·추천 정렬 때문에 순서가 다를 수 있다)

### STEP 07-B. 날짜 데이터 전달 검증

### 작업 계획

이번 단계의 목적:
- STEP 07-A에서 추출한 `jobs`(list[dict]) 데이터가 DataFrame으로 변환된 뒤에도
  **지원 제출 시작일 / 마감일이 정상적으로 유지되는지** 확인한다.

DataFrame 이름:
- 실데이터용 DataFrame은 `df_real_jobs`로 만든다.
- STEP 04~07의 샘플 데이터 `df_jobs`를 덮어쓰지 않기 위해서다.

확인 항목:
- `jobs` → DataFrame 변환
- shape 확인
- 9개 컬럼 확인 (STEP 02 명세 순서)
- `posted_date`(= 지원 제출 시작일) 값 확인
- `closing_date`(= 지원 제출 마감일) 값 확인
- 결측값 확인
- `pd.to_datetime()`으로 날짜 변환이 가능한지 확인

중요:
- 원본 날짜 문자열은 보존한다.
- 날짜 변환 가능 여부는 원본 컬럼을 덮어쓰지 않고, 별도 변수(`posted_parsed`, `closing_parsed`)로만 확인한다.

이번 단계에서 하지 않는 것:
- 중복 제거, 신규 공고 판별, CSV 저장, 분석 (STEP 08 이후)

완료 조건:
- shape가 (5, 9)이다
- `posted_date`, `closing_date` 결측값이 0이다 (JSON에 값이 없는 공고가 있다면 그 수만큼 결측으로 남는 것이 정상)
- 날짜 변환 실패가 0건이다

In [2]:
import pandas as pd

# STEP 02에서 정한 9개 컬럼 순서
columns = [
    "company_name",
    "job_title",
    "career",
    "location",
    "posted_date",    # 지원 제출 시작일 (applicationPeriod.start)
    "closing_date",   # 지원 제출 마감일 (applicationPeriod.end)
    "job_url",
    "search_keyword",
    "collected_at",
]

# ----- 1) jobs(list[dict]) → DataFrame 변환 -----
# 샘플 데이터 df_jobs를 덮어쓰지 않도록 실데이터는 df_real_jobs라는 이름을 쓴다
df_real_jobs = pd.DataFrame(jobs, columns=columns)

# ----- 2) 크기와 컬럼 확인 -----
print("데이터 크기:", df_real_jobs.shape)
print("컬럼 목록:", df_real_jobs.columns.tolist())

# ----- 3) 날짜 값 확인 (원본 문자열 그대로) -----
print("\n회사명 / 지원 시작일 / 지원 마감일:")
display(df_real_jobs[["company_name", "posted_date", "closing_date"]])

# ----- 4) 결측값 확인 -----
print("\n결측값 개수:")
print(df_real_jobs.isna().sum())

# ----- 5) 날짜 변환 가능 여부 확인 -----
# 원본 컬럼은 그대로 두고, 변환 결과는 별도 변수에만 저장한다
# errors="coerce": 날짜로 바꿀 수 없는 값은 NaT(날짜 결측값)가 된다 → NaT 개수 = 변환 실패 수
posted_parsed = pd.to_datetime(df_real_jobs["posted_date"], errors="coerce")
closing_parsed = pd.to_datetime(df_real_jobs["closing_date"], errors="coerce")

print("\nposted_date 변환 실패:", posted_parsed.isna().sum())
print("closing_date 변환 실패:", closing_parsed.isna().sum())
print("변환 후 dtype:", posted_parsed.dtype, "/", closing_parsed.dtype)
print("원본 컬럼 dtype(그대로 유지):", df_real_jobs["posted_date"].dtype, "/", df_real_jobs["closing_date"].dtype)

데이터 크기: (5, 9)
컬럼 목록: ['company_name', 'job_title', 'career', 'location', 'posted_date', 'closing_date', 'job_url', 'search_keyword', 'collected_at']

회사명 / 지원 시작일 / 지원 마감일:

  company_name posted_date      closing_date
0        GS리테일  2026-09-21  2026-10-01 23:00
1         에스코어  2026-07-01  2026-09-30 23:00
2       ㈜NAVER  2026-09-10  2026-09-29 10:00
3        ㈜슈프리마  2026-08-26  2026-10-25 23:00
4       ㈜NAVER  2026-09-10  2026-09-29 10:00

결측값 개수:
company_name      0
job_title         0
career            0
location          0
posted_date       0
closing_date      0
job_url           0
search_keyword    0
collected_at      0
dtype: int64

posted_date 변환 실패: 0
closing_date 변환 실패: 0
변환 후 dtype: datetime64[us] / datetime64[us]
원본 컬럼 dtype(그대로 유지): str / str

### 실행 결과 해석 / 분석 / 요약

- 셀이 에러 없이 실행되었다.
- DataFrame shape: `(5, 9)`
- 총 행 수: 5 (STEP 07-A에서 추출한 공고 5건)
- 총 컬럼 수: 9 (`company_name`, `job_title`, `career`, `location`, `posted_date`, `closing_date`, `job_url`, `search_keyword`, `collected_at`)
- posted_date 결측 수: 0
- closing_date 결측 수: 0 (다른 7개 컬럼도 모두 결측 0)
- posted_date 변환 실패 수: 0
- closing_date 변환 실패 수: 0
  - 변환은 `posted_parsed`, `closing_parsed` 변수에만 했고, `df_real_jobs`의 원본 컬럼은 문자열(`str`) 그대로 유지했다.
- 첫 번째 공고의 지원 시작일: `2026-09-21` (GS리테일)
- 첫 번째 공고의 지원 마감일: `2026-10-01 23:00`
- 브라우저 화면과 일치 여부: 화면에 표시되는 `09/21 등록 · 10/01 마감`과 날짜가 일치한다. 나머지 4건은 사람이 브라우저에서 직접 확인해야 한다.
- 5건 날짜 요약:

| company_name | posted_date (지원 시작일) | closing_date (지원 마감일) |
|---|---|---|
| GS리테일 | 2026-09-21 | 2026-10-01 23:00 |
| 에스코어 | 2026-07-01 | 2026-09-30 23:00 |
| ㈜NAVER | 2026-09-10 | 2026-09-29 10:00 |
| ㈜슈프리마 | 2026-08-26 | 2026-10-25 23:00 |
| ㈜NAVER | 2026-09-10 | 2026-09-29 10:00 |

- 2070년 등 특이값 존재 여부: 이번 5건에는 없다. 다만 같은 페이지 6번째 공고에서 `2070-01-01`이 확인되었으므로,
  비정상적으로 먼 날짜가 존재할 수 있으며, 후속 단계에서 상시채용 표기와의 관계를 별도 검증해야 한다.
- 결론: `applicationPeriod.start/end → posted_date/closing_date → jobs → DataFrame` 흐름에서 날짜가 빠짐없이 유지되었다.
- 다음 단계 진행 가능 여부: 사용자가 브라우저 화면과 날짜를 비교해 확인하면 진행 가능하다.

# STEP 07-C. 실데이터 중복 확인 및 제거

## 작업 계획

이번 단계에서는 STEP 07-A/07-B에서 만든 **실제 공고 5건(`df_real_jobs`)** 안에
같은 공고가 두 번 이상 들어 있는지 확인한다.

> 참고: STEP 06의 중복 제거는 **샘플 데이터(`df_jobs`)** 연습이었다.
> 이번에는 실데이터(`df_real_jobs`)를 대상으로 한다.

중복 기준: `job_url`
- 같은 회사가 공고를 여러 개 낼 수 있어서, 회사명만으로는 중복을 판단할 수 없다.
- 공고 제목도 비슷하거나 같을 수 있다. (예: 같은 회사의 "광고 프로덕트 기획 경력 채용(...)" 공고 2개)
- `job_url`은 공고마다 번호가 달라서 개별 공고를 구분하는 데 가장 적합하다.
- STEP 07-A에서 `?Oem_Code=...&listno=...` 같은 추적용 값을 떼고 기본 공고 URL만 저장했으므로, 같은 공고는 같은 URL이 된다.

확인 내용:
- 현재 공고 수
- 중복된 `job_url`이 있는지
- 중복 행 수
- 중복 제거 후 공고 수
- 어떤 공고가 중복이었는지

중요:
- 원본 DataFrame인 `df_real_jobs`는 수정하지 않는다.
- 중복 제거 결과는 새로운 DataFrame `df_unique_jobs`에 저장한다.
- `df_real_jobs`가 메모리에 없으면 데이터를 임의로 만들지 않고, STEP 07-A → 07-B를 먼저 실행하라고 안내한다.

아직 하지 않는 것:
- 이전 실행 결과와 비교
- 신규/기존 공고 판별
- CSV 저장
- 여러 페이지 크롤링
- 여러 검색어 수집
- 통계 분석

완료 조건:
- `job_url` 기준 중복 확인을 수행하고 중복 행 수를 확인한다
- `df_unique_jobs`가 만들어진다
- 원본 `df_real_jobs`가 그대로 보존된다
- 중복 제거 전/후 행 수를 확인한다

In [4]:
# ----- 0) df_real_jobs가 있는지 먼저 확인 -----
# STEP 07-A → 07-B를 실행하지 않았다면 df_real_jobs가 없다 (데이터를 임의로 만들지 않는다)
if "df_real_jobs" not in globals():
    print("df_real_jobs가 없습니다. STEP 07-A와 STEP 07-B를 먼저 실행하세요.")
else:
    # ----- 1) 현재 행 수 -----
    print("현재 공고 수:", len(df_real_jobs))

    # ----- 2) job_url 기준 중복 여부 확인 -----
    # duplicated(): 중복인 행을 "찾기"만 한다 (True/False)
    # keep=False: 중복된 행을 첫 번째 것까지 모두 True로 표시 → 어떤 공고끼리 겹쳤는지 전부 볼 수 있다
    duplicate_mask = df_real_jobs.duplicated(subset=["job_url"], keep=False)
    duplicate_rows = df_real_jobs.loc[duplicate_mask, ["company_name", "job_title", "job_url"]]

    # ----- 3) 중복 행 수 -----
    print("중복 행 수:", duplicate_mask.sum())

    # ----- 4) 중복이 있으면 출력 -----
    if duplicate_mask.any():
        display(duplicate_rows)
    else:
        print("현재 5건 안에는 job_url 기준 중복 공고가 없습니다.")

    # ----- 5) 원본을 보존한 채 새 DataFrame 생성 -----
    # drop_duplicates(): 중복 행을 제거한 "새 결과"를 만든다 (df_real_jobs 자체는 바뀌지 않는다)
    # keep="first": 같은 job_url이 여러 개면 처음 나온 행만 남긴다
    # reset_index(drop=True): 행 번호를 0부터 다시 매긴다
    df_unique_jobs = (
        df_real_jobs
        .drop_duplicates(subset=["job_url"], keep="first")
        .reset_index(drop=True)
    )

    # ----- 6) 전/후 개수 확인 -----
    print("\n중복 제거 전:", len(df_real_jobs))
    print("중복 제거 후:", len(df_unique_jobs))
    print("제거된 행 수:", len(df_real_jobs) - len(df_unique_jobs))

    # ----- 7) 결과 확인 -----
    display(df_unique_jobs[["company_name", "job_title", "posted_date", "closing_date", "job_url"]])

현재 공고 수: 5
중복 행 수: 0
현재 5건 안에는 job_url 기준 중복 공고가 없습니다.

중복 제거 전: 5
중복 제거 후: 5
제거된 행 수: 0

,company_name,job_title,posted_date,closing_date,job_url
0,GS리테일,"[GS리테일] 9·10월 통합공고(BIZ CLUB팀 경력사원, MD AX 담당, 물...",2026-09-21,2026-10-01 23:00,https://www.jobkorea.co.kr/Recruit/GI_Read/500...
1,에스코어,AX 컨설턴트 채용,2026-07-01,2026-09-30 23:00,https://www.jobkorea.co.kr/Recruit/GI_Read/495...
2,㈜NAVER,광고 프로덕트 기획 경력 채용(AX 광고 예산/과금 구조 설계 담당),2026-09-10,2026-09-29 10:00,https://www.jobkorea.co.kr/Recruit/GI_Read/499...
3,㈜슈프리마,[슈프리마HQ] HRD & AX 담당자 모집,2026-08-26,2026-10-25 23:00,https://www.jobkorea.co.kr/Recruit/GI_Read/498...
4,㈜NAVER,광고 프로덕트 기획 경력 채용(AX 광고 최적화 전략 담당),2026-09-10,2026-09-29 10:00,https://www.jobkorea.co.kr/Recruit/GI_Read/499...

## 실행 결과 해석 / 분석 / 요약

- 셀이 에러 없이 실행되었다. (STEP 07-A → 07-B → 07-C 순서로 실행)
- 중복 확인 전 공고 수: 5
- 중복된 행 수: 0
- 중복 제거 후 공고 수: 5
- 실제 제거된 행 수: 0
- 사용한 중복 기준: `job_url` (추적용 파라미터를 뗀 기본 공고 URL)
- 중복 공고 존재 여부: **없음** — 현재 5건은 모두 서로 다른 공고이다.
- `df_real_jobs` 원본 보존 여부: **보존됨** — 실행 전후 5행 그대로이며 내용도 바뀌지 않았다.
- 새 DataFrame 이름: `df_unique_jobs` (5행)
- 예상과 다른 부분: 없음.
  - 참고로 ㈜NAVER 공고가 2건(3번째, 5번째) 있고 제목도 비슷하다.
    하지만 `job_url`이 서로 다르므로(`.../49976564`, `.../49976547`) **서로 다른 공고**로 판단되었다.
    회사명이나 제목이 아니라 `job_url`을 중복 기준으로 쓰는 이유를 보여 주는 사례이다.
- 다음 단계 진행 가능 여부: 사용자가 결과를 확인하면, 이전 실행 결과와 비교하는 다음 단계로 진행할 수 있다.

#### 초보자 설명
- `duplicated()` → 어떤 행이 중복인지 **"찾는"** 기능이다. 행마다 True/False를 돌려줄 뿐 데이터를 지우지 않는다.
  - `keep=False`로 두면 겹치는 행을 모두 True로 표시해서, 어떤 공고끼리 겹쳤는지 전부 볼 수 있다.
- `drop_duplicates()` → 중복된 행을 실제로 **"제거한 새 결과를 만드는"** 기능이다.
  - `keep="first"`로 두면 같은 URL 중 처음 나온 행만 남긴다.
- 이번에는 원본을 보존하기 위해 두 DataFrame을 분리했다.
  - `df_real_jobs` → 원본 (수집한 그대로)
  - `df_unique_jobs` → 중복 제거 결과
- 이번 단계는 "현재 5건 **안에서** 같은 공고가 겹치는가?"만 확인했다.
  "지난번 수집 결과와 비교해서 신규 공고인가?"는 아직 하지 않았다.

# STEP 07-D. 신규 공고 판별 및 이력 초기화

## 작업 계획

이번 단계에서는 현재 실데이터 공고(`df_unique_jobs`)를 **과거에 수집한 공고 이력**과 비교해서
이번에 처음 나타난 공고(신규 공고)만 골라낸다.

> 참고: STEP 07은 샘플 이력(`previous_urls`)으로 연습한 것이었다.
> 이번에는 실데이터와 **실제 파일로 저장되는 이력**을 사용한다.

신규 공고 판별의 개념:

```text
현재 수집 공고
  minus
과거에 이미 본 공고
  =
신규 공고
```

비교 기준: `job_url`
- 회사명이나 제목은 같거나 비슷할 수 있다. (예: ㈜NAVER의 비슷한 제목 공고 2건)
- `job_url`은 공고마다 번호가 달라서 개별 공고를 구분하기에 적합하다.

이력 파일:
- `data/processed/jobs_history.csv` (프로젝트 루트 기준)
- Notebook은 `notebooks/` 폴더에서 실행되므로, 코드에서 프로젝트 루트를 계산해 경로를 만든다.
- 폴더(`data/processed/`)가 없으면 저장할 때 만든다.

첫 실행 규칙:
- history 파일이 없으면 과거 데이터가 없다는 뜻이다.
- 현재 `df_unique_jobs` 전체를 신규 공고로 간주한다.
- 현재 데이터를 history 파일의 초기값으로 저장한다.

두 번째 실행부터:
- history의 `job_url` 집합과 현재 `job_url`을 비교한다.
- history에 없는 `job_url`만 신규 공고이다.
- history에는 현재 공고를 합치되, `job_url` 기준으로 중복을 제거해서 같은 공고가 두 번 쌓이지 않게 한다.

DataFrame 역할 분리 (원본은 수정하지 않는다):
- `df_real_jobs` → 원본 실데이터
- `df_unique_jobs` → 현재 실행의 중복 제거 결과
- `history_df` → 파일에서 읽은 과거 이력
- `new_jobs_df` → 이번 실행에서 새로 발견된 공고
- `updated_history_df` → 저장할 누적 이력

이번 단계에서 하지 않는 것:
- 통계 분석, Gemini 요약, Slack / Gmail
- 여러 페이지 / 여러 검색어 수집

완료 조건:
- 첫 실행: history 없음 → 현재 5건 모두 신규 → history 5건 생성
- 두 번째 실행: 같은 5건 → 신규 0건 → history 여전히 5건 (10건으로 늘어나면 안 된다)

In [5]:
from pathlib import Path
import pandas as pd

# ----- 0) df_unique_jobs가 있는지 먼저 확인 -----
if "df_unique_jobs" not in globals():
    print("df_unique_jobs가 없습니다. STEP 07-A → 07-B → 07-C를 먼저 실행하세요.")
else:
    # ----- A) 경로 정의 -----
    # Notebook은 notebooks/ 폴더에서 실행되므로, 그 경우 한 단계 위를 프로젝트 루트로 사용한다
    current_dir = Path.cwd()
    project_root = current_dir.parent if current_dir.name == "notebooks" else current_dir
    history_path = project_root / "data" / "processed" / "jobs_history.csv"
    print("현재 실행 위치:", current_dir)
    print("history 파일 경로:", history_path)

    # ----- B) history 존재 여부 확인 -----
    if history_path.exists():
        history_df = pd.read_csv(history_path)
        print("\n기존 이력 파일 있음")
        print("기존 이력 건수:", len(history_df))
    else:
        # 과거 데이터가 없으므로 컬럼만 있는 빈 표로 시작한다
        history_df = pd.DataFrame(columns=df_unique_jobs.columns)
        print("\n기존 이력 파일 없음")
        print("첫 실행으로 처리합니다.")

    # ----- C) 신규 공고 판별 -----
    # set(): 이미 본 URL을 모아 둔 "집합" — 어떤 URL이 들어 있는지 빠르게 확인할 수 있다
    known_urls = set(history_df["job_url"].dropna().astype(str))

    # isin(known_urls): 현재 URL이 과거 URL 집합에 "있는지" True/False로 확인
    # ~ 를 붙이면 True/False가 뒤집힌다 → 과거 집합에 "없는" 공고만 선택 = 신규 공고
    new_jobs_df = df_unique_jobs[~df_unique_jobs["job_url"].isin(known_urls)].copy()

    print("\n현재 공고 수:", len(df_unique_jobs))
    print("기존 이력 수:", len(history_df))
    print("신규 공고 수:", len(new_jobs_df))

    # ----- E) 신규 공고 출력 -----
    if len(new_jobs_df) > 0:
        display(new_jobs_df[["company_name", "job_title", "posted_date", "closing_date", "job_url"]])
    else:
        print("이번 실행에서 새로 발견된 공고가 없습니다.")

    # ----- F) history 업데이트 -----
    # 과거 이력 + 현재 공고를 합친 뒤, job_url 기준으로 중복을 제거한다
    # keep="last": 같은 공고가 있으면 나중에 붙은 행(= 이번 실행의 최신 정보)을 남긴다
    updated_history_df = pd.concat([history_df, df_unique_jobs], ignore_index=True)
    updated_history_df = (
        updated_history_df
        .drop_duplicates(subset=["job_url"], keep="last")
        .reset_index(drop=True)
    )

    # 폴더가 없으면 만든다 (이미 있으면 그대로 사용)
    history_path.parent.mkdir(parents=True, exist_ok=True)
    # encoding="utf-8-sig": 엑셀에서 열어도 한글이 깨지지 않게 저장
    updated_history_df.to_csv(history_path, index=False, encoding="utf-8-sig")

    print("\n업데이트 후 이력 건수:", len(updated_history_df))
    print("history 저장 경로:", history_path)

현재 실행 위치: C:\dev\claude-code-agent-course\chapter11\ax-job-agent\notebooks
history 파일 경로: C:\dev\claude-code-agent-course\chapter11\ax-job-agent\data\processed\jobs_history.csv

기존 이력 파일 없음
첫 실행으로 처리합니다.

현재 공고 수: 5
기존 이력 수: 0
신규 공고 수: 5

,company_name,job_title,posted_date,closing_date,job_url
0,GS리테일,"[GS리테일] 9·10월 통합공고(BIZ CLUB팀 경력사원, MD AX 담당, 물...",2026-09-21,2026-10-01 23:00,https://www.jobkorea.co.kr/Recruit/GI_Read/500...
1,에스코어,AX 컨설턴트 채용,2026-07-01,2026-09-30 23:00,https://www.jobkorea.co.kr/Recruit/GI_Read/495...
2,㈜NAVER,광고 프로덕트 기획 경력 채용(AX 광고 예산/과금 구조 설계 담당),2026-09-10,2026-09-29 10:00,https://www.jobkorea.co.kr/Recruit/GI_Read/499...
3,㈜슈프리마,[슈프리마HQ] HRD & AX 담당자 모집,2026-08-26,2026-10-25 23:00,https://www.jobkorea.co.kr/Recruit/GI_Read/498...
4,㈜NAVER,광고 프로덕트 기획 경력 채용(AX 광고 최적화 전략 담당),2026-09-10,2026-09-29 10:00,https://www.jobkorea.co.kr/Recruit/GI_Read/499...

업데이트 후 이력 건수: 5
history 저장 경로: C:\dev\claude-code-agent-course\chapter11\ax-job-agent\data\processed\jobs_history.csv

## 실행 결과 해석 / 분석 / 요약

- 셀이 에러 없이 실행되었다. (STEP 07-A → 07-B → 07-C → 07-D 순서로 실행, 실행 위치는 `notebooks/`)
- 위 출력은 **첫 실행** 결과이다.

#### 첫 실행 결과
- 현재 공고 수: 5
- 기존 history 건수: 0
- 신규 공고 수: 5
- history 업데이트 후 건수: 5
- 첫 실행 여부: **예** — 실행 전에는 `data/` 폴더와 history 파일이 없었다.
- history 파일 생성 여부: **생성됨** — `data/processed/jobs_history.csv` (5행 × 9열, `job_url` 5개 모두 서로 다름)

#### 두 번째 실행 결과 (같은 셀을 같은 5건으로 한 번 더 실행)
- 기존 history 건수: 5 (첫 실행에서 만든 파일을 읽음)
- 신규 공고 수: **0** — "이번 실행에서 새로 발견된 공고가 없습니다."
- history 업데이트 후 건수: **5** — 10건으로 늘어나지 않았다.
- 같은 공고 재실행 시 신규 0건인지: **예**

→ 첫 실행(5건 모두 신규)과 두 번째 실행(신규 0건) 결과가 다르게 나왔다.
즉 **"이미 본 공고는 다시 신규로 잡히지 않는다"**는 것이 확인되었다.

#### 기타 확인
- 신규 공고 기준: `job_url`이 history의 `job_url` 집합에 없으면 신규
- 원본 `df_unique_jobs` 보존 여부: **보존됨** (`df_real_jobs`도 그대로)
- `new_jobs_df` 생성 여부: **생성됨** (첫 실행 5건, 두 번째 실행 0건)
- 예상과 다른 부분: 없음.
- 참고 / 한계:
  - 두 번째 실행은 **다시 크롤링하지 않고** 같은 커널의 같은 5건으로 실행했다. 판별 로직 검증이 목적이었기 때문이다.
    실제 운영에서는 다음 수집 때 새로 나온 공고만 신규로 잡힐 것으로 예상하며, 이는 이후 실제 재수집으로 확인해야 한다.
  - history에는 `keep="last"`로 저장하므로, 같은 공고를 다시 수집하면 `collected_at`이 최신 수집 시각으로 바뀐다.
    ("처음 발견한 시각"을 따로 남기고 싶다면 후속 단계에서 컬럼 추가를 검토한다)
  - 이 셀은 실행할 때마다 history 파일을 덮어써 저장한다.
- 다음 단계 진행 가능 여부: 사용자가 결과와 CSV 파일을 확인하면 진행 가능하다.

#### 초보자 설명
- `set()` → 이미 본 URL을 모아 둔 **집합**이다. 어떤 URL이 들어 있는지 빠르게 비교할 수 있다.
- `isin()` → 현재 URL이 과거 URL 목록에 **있는지** True/False로 확인한다.
- `~isin(...)` → True/False를 뒤집어서, 과거 목록에 **없는 것만** 선택한다. = 신규 공고
- 첫 실행: history 없음 → 현재 공고 모두 신규 → history 초기 생성
- 두 번째 실행: history에 같은 5개 `job_url` 있음 → 신규 0건

# STEP 07-E. 실데이터 기본 분석

## 작업 계획

이번 단계의 목적:
- 수집된 채용공고를 **숫자로 요약**해서, 어떤 회사·지역·경력 조건이 많이 나오는지 확인한다.
- pandas의 기본 집계 방법(`value_counts()`, `min()`, `max()`)을 연습하는 것이 목적이다.

분석 대상: `df_unique_jobs`
- 현재 실행에서 `job_url` 기준으로 중복을 제거한 **실제 공고 데이터**이기 때문이다.
- 원본 `df_unique_jobs`는 수정하지 않고, 읽기만 한다.

확인 항목:
- 전체 공고 수
- 회사별 공고 수
- 지역별 공고 수
- 경력별 공고 수
- 검색어별 공고 수
- 신규 공고 수 (STEP 07-D의 `new_jobs_df`가 있을 때만)
- 지원 시작일(`posted_date`) / 지원 마감일(`closing_date`) 범위

중요한 해석 원칙:
- 현재 표본은 **검색어 `ax`, 1페이지 상위 5건**뿐이다.
- 따라서 결과를 "채용 시장 전체의 경향"으로 해석하면 안 된다.
- 결과는 항상 "현재 수집된 5건 기준으로"처럼 제한해서 해석한다.

참고:
- 신규 공고 수는 STEP 07-D를 실행한 결과(`new_jobs_df`)에 따라 달라진다.
  - 첫 실행 직후라면 5, 같은 공고로 다시 실행했다면 0이 나온다.
  - STEP 07-D를 실행하지 않았다면 신규 공고 수는 확인하지 못했다고 출력된다.

이번 단계에서 하지 않는 것:
- 관련 공고 점수화, Gemini 요약, Slack / Gmail
- 여러 검색어 / 여러 페이지 수집

완료 조건:
- 위 확인 항목이 모두 출력된다
- `df_unique_jobs`가 바뀌지 않는다

In [5]:
import pandas as pd

# ----- 0) df_unique_jobs가 있는지 먼저 확인 -----
if "df_unique_jobs" not in globals():
    print("df_unique_jobs가 없습니다. 이전 실데이터 STEP을 먼저 실행하세요.")
else:
    # ----- 1) 전체 공고 수 -----
    print("전체 공고 수:", len(df_unique_jobs))

    # ----- 2) 회사별 공고 수 -----
    # value_counts(): 같은 값이 몇 번 나오는지 세어서 많은 순서로 보여 준다
    company_counts = df_unique_jobs["company_name"].value_counts()
    print("\n=== 회사별 공고 수 ===")
    print(company_counts)

    # ----- 3) 지역별 공고 수 -----
    location_counts = df_unique_jobs["location"].value_counts()
    print("\n=== 지역별 공고 수 ===")
    print(location_counts)

    # ----- 4) 경력별 공고 수 -----
    career_counts = df_unique_jobs["career"].value_counts()
    print("\n=== 경력별 공고 수 ===")
    print(career_counts)

    # ----- 5) 검색어별 공고 수 -----
    keyword_counts = df_unique_jobs["search_keyword"].value_counts()
    print("\n=== 검색어별 공고 수 ===")
    print(keyword_counts)

    # ----- 6) 신규 공고 수 (STEP 07-D를 실행했을 때만 확인 가능) -----
    if "new_jobs_df" in globals():
        print("\n신규 공고 수:", len(new_jobs_df))
    else:
        print("\nnew_jobs_df가 없어 신규 공고 수는 확인하지 못했습니다.")

    # ----- 7) 날짜 범위 확인 -----
    # 원본 문자열 컬럼은 그대로 두고, 날짜로 바꾼 결과는 별도 변수에만 저장한다
    posted_parsed = pd.to_datetime(df_unique_jobs["posted_date"], errors="coerce")
    closing_parsed = pd.to_datetime(df_unique_jobs["closing_date"], errors="coerce")

    # min(): 가장 작은 값(가장 이른 날짜), max(): 가장 큰 값(가장 늦은 날짜)
    print("\n=== 지원 기간 날짜 범위 ===")
    print("가장 이른 지원 시작일:", posted_parsed.min())
    print("가장 늦은 지원 시작일:", posted_parsed.max())
    print("가장 이른 지원 마감일:", closing_parsed.min())
    print("가장 늦은 지원 마감일:", closing_parsed.max())

전체 공고 수: 5

=== 회사별 공고 수 ===
company_name
㈜NAVER    2
GS리테일     1
에스코어      1
㈜슈프리마     1
Name: count, dtype: int64

=== 지역별 공고 수 ===
location
경기 성남시        3
서울 강남구 외 1    1
서울 송파구        1
Name: count, dtype: int64

=== 경력별 공고 수 ===
career
경력       3
경력3년↑    1
경력7년↑    1
Name: count, dtype: int64

=== 검색어별 공고 수 ===
search_keyword
ax    5
Name: count, dtype: int64

new_jobs_df가 없어 신규 공고 수는 확인하지 못했습니다.

=== 지원 기간 날짜 범위 ===
가장 이른 지원 시작일: 2026-07-01 00:00:00
가장 늦은 지원 시작일: 2026-09-21 00:00:00
가장 이른 지원 마감일: 2026-09-29 10:00:00
가장 늦은 지원 마감일: 2026-10-25 23:00:00

## 실행 결과 해석 / 분석 / 요약

- 셀이 에러 없이 실행되었다. (STEP 07-A → 07-B → 07-C → 07-E 순서로 실행)
- 아래 해석은 모두 **현재 수집된 5건 기준**이다. (검색어 `ax`, 1페이지 상위 5건)

| 항목 | 결과 |
|---|---|
| 전체 공고 수 | 5 |
| 회사별 공고 수 | ㈜NAVER 2 / GS리테일 1 / 에스코어 1 / ㈜슈프리마 1 |
| 지역별 공고 수 | 경기 성남시 3 / 서울 강남구 외 1 1 / 서울 송파구 1 |
| 경력별 공고 수 | 경력 3 / 경력3년↑ 1 / 경력7년↑ 1 |
| 검색어별 공고 수 | ax 5 |
| 신규 공고 수 | 이번 실행에서는 확인하지 못함 (아래 참고) |
| 가장 이른 지원 시작일 | 2026-07-01 (에스코어) |
| 가장 늦은 지원 시작일 | 2026-09-21 (GS리테일) |
| 가장 이른 지원 마감일 | 2026-09-29 10:00 (㈜NAVER 2건) |
| 가장 늦은 지원 마감일 | 2026-10-25 23:00 (㈜슈프리마) |

해석 (현재 5건 기준):
- 이번 샘플에서는 ㈜NAVER 공고가 2건으로 가장 많고, 나머지 회사는 1건씩이다.
- 이번 샘플에서는 경기 성남시 공고가 3건이다. (㈜NAVER 2건 + ㈜슈프리마 1건)
- 이번 샘플에서는 5건 모두 경력직 공고이고, 신입 공고는 없다.
- 이번 샘플의 지원 마감일은 2026-09-29 ~ 2026-10-25 사이에 있다.

특이사항:
- 표본이 5건뿐이라 이 결과를 채용 시장 전체의 경향으로 볼 수 없다.
- 경력 값은 화면 글자 그대로라서 `경력`, `경력3년↑`, `경력7년↑`가 **서로 다른 값**으로 세어졌다.
  "경력직 전체"로 묶어 세려면 값 정리 규칙이 필요하다. (후속 단계에서 검토)
- 지역 값 `서울 강남구 외 1`은 근무지가 여러 곳인 공고의 요약 문구라, 다른 지역 값과 형식이 다르다.
- 신규 공고 수: STEP 07-D는 실행할 때마다 `jobs_history.csv`를 다시 저장하기 때문에,
  이번 검증 실행에서는 07-D를 실행하지 않았다. 그래서 `new_jobs_df`가 없어 "확인하지 못했습니다"가 출력되었다.
  - 참고로 history 파일을 읽기만 해서 비교해 보면, 현재 5건은 모두 이미 history에 있다. (지금 07-D를 실행하면 신규 0건 예상)
  - 07-D까지 실행한 뒤 이 셀을 실행하면 신규 공고 수가 출력된다.
- 이번 5건에는 `2070-01-01` 같은 비정상적으로 먼 마감일이 없다.
- 원본 `df_unique_jobs`는 수정되지 않았다.
- 다음 단계 진행 가능 여부: 사용자가 결과를 확인하면 진행 가능하다.

#### 초보자 설명
- `value_counts()` → 같은 값이 **몇 번 나오는지 세는** 기능이다. 많이 나온 값부터 순서대로 보여 준다.
- `min()` → **가장 작은 값**이다. 날짜에서는 가장 이른 날짜가 된다.
- `max()` → **가장 큰 값**이다. 날짜에서는 가장 늦은 날짜가 된다.
- 날짜는 문자열 상태에서도 모양상 비교할 수 있지만, `pd.to_datetime()`으로 날짜 타입으로 바꾼 뒤 `min()`/`max()`를 쓰는 것이 정확하다.

# STEP 07-F. AX/AI 관련 공고 1차 필터링

## 작업 계획

이번 단계의 목적:
- 현재 수집된 채용공고(`df_unique_jobs`) 중에서 **공고 제목에 AX/AI 관련 키워드가 들어 있는 공고**를 Python으로 먼저 골라 본다.
- LLM/Gemini가 아니라 **단순한 문자열 검색**을 사용한다.
- 원칙: Python으로 먼저 후보를 좁히고, 나중에 Gemini가 내용 해석을 담당한다.

1차 필터 키워드:
- `AX`, `AI`, `인공지능`, `생성형 AI`, `생성형AI`, `LLM`
- `Machine Learning`, `머신러닝`, `Data Scientist`, `데이터 사이언티스트`
- `AI Engineer`, `AI 엔지니어`, `데이터 분석`

검색 방법:
- 대상은 우선 `job_title`(공고 제목)만 사용한다. 회사명이나 상세 본문은 후속 단계에서 검토한다.
- 대소문자 차이를 없애기 위해 제목과 키워드를 모두 소문자로 바꿔서 비교한다. (예: `Ax`, `ax`, `AX`를 같게 취급)
- 원본 `job_title` 값 자체는 바꾸지 않는다.
- 공고마다 **어떤 키워드에 매칭됐는지**(`matched_keywords`)도 함께 출력해서 사람이 이유를 확인할 수 있게 한다.

미리 알아 둘 점:
- 현재 실데이터는 검색어 자체가 `ax`이므로, 5건 대부분 또는 전부가 통과할 가능성이 높다.
- 그래서 이번 STEP의 목적은 "좋은 공고를 최종 판단"하는 것이 아니라 **키워드 기반 필터링 방법을 검증**하는 것이다.
- 키워드가 들어 있다고 원하는 AX 직무라는 뜻은 아니고, 반대로 제목에 키워드가 없어도 실제 업무는 AI/AX 관련일 수 있다.
  → 이번 결과는 **"1차 후보"**로만 해석한다.

DataFrame 역할 분리 (원본은 수정하지 않는다):
- `df_real_jobs` → 원본 실데이터
- `df_unique_jobs` → 중복 제거된 현재 공고 (새 컬럼도 추가하지 않는다)
- `df_filtered_jobs` → AX/AI 키워드 1차 필터 결과 (복사본이며, 여기에만 `matched_keywords` 컬럼을 추가한다)

이번 단계에서 하지 않는 것:
- Gemini API, 점수화, 추천 순위
- 상세 페이지 요청, 여러 페이지 / 여러 검색어 수집
- history CSV 갱신

완료 조건:
- 전체 공고 수, 필터 통과 공고 수, 제외 공고 수가 출력된다
- 공고별 회사명 / 제목 / 매칭 키워드를 사람이 확인할 수 있다
- `df_filtered_jobs`가 만들어지고, `df_unique_jobs`는 바뀌지 않는다

In [5]:
# ----- 0) df_unique_jobs가 있는지 먼저 확인 -----
if "df_unique_jobs" not in globals():
    print("df_unique_jobs가 없습니다. 이전 실데이터 STEP을 먼저 실행하세요.")
else:
    # ----- 1) 1차 필터 키워드 -----
    relevance_keywords = [
        "AX",
        "AI",
        "인공지능",
        "생성형 AI",
        "생성형AI",
        "LLM",
        "Machine Learning",
        "머신러닝",
        "Data Scientist",
        "데이터 사이언티스트",
        "AI Engineer",
        "AI 엔지니어",
        "데이터 분석",
    ]

    # ----- 2) 제목에 키워드가 하나라도 있는지 확인하는 함수 -----
    def contains_relevance_keyword(title):
        if not isinstance(title, str):  # 제목이 비어 있으면(None 등) 통과시키지 않는다
            return False
        title_lower = title.lower()     # 비교할 때만 소문자로 바꾼다 (원본 값은 그대로)
        # any(): 여러 조건 중 하나라도 True면 True
        return any(keyword.lower() in title_lower for keyword in relevance_keywords)

    # ----- 3) 제목에서 실제로 매칭된 키워드 목록을 찾는 함수 -----
    def find_matched_keywords(title):
        if not isinstance(title, str):
            return []
        title_lower = title.lower()
        return [keyword for keyword in relevance_keywords if keyword.lower() in title_lower]

    # ----- 4) 1차 필터링 -----
    # apply(): job_title의 각 값에 함수를 하나씩 적용해서 True/False 목록을 만든다
    # .copy(): 필터 결과를 원본과 분리된 새 DataFrame으로 만든다
    is_relevant = df_unique_jobs["job_title"].apply(contains_relevance_keyword)
    df_filtered_jobs = df_unique_jobs[is_relevant].copy()

    # 매칭 키워드는 복사본(df_filtered_jobs)에만 컬럼으로 추가한다 (df_unique_jobs에는 추가하지 않음)
    df_filtered_jobs["matched_keywords"] = df_filtered_jobs["job_title"].apply(find_matched_keywords)

    # ----- 5) 결과 출력 -----
    print("전체 공고 수:", len(df_unique_jobs))
    print("1차 필터 통과 공고 수:", len(df_filtered_jobs))
    print("제외된 공고 수:", len(df_unique_jobs) - len(df_filtered_jobs))

    display(df_filtered_jobs[["company_name", "job_title", "career", "location", "posted_date", "closing_date"]])

    # ----- 6) 공고별 매칭 이유 확인 (사람이 직접 검토) -----
    print("\n=== 공고별 매칭 키워드 (전체 공고 기준) ===")
    for _, row in df_unique_jobs.iterrows():
        matched = find_matched_keywords(row["job_title"])
        result = "통과" if matched else "제외"
        print(f"[{result}] {row['company_name']} | {row['job_title']}")
        print(f"        → 매칭 키워드: {matched if matched else '없음'}")

전체 공고 수: 5
1차 필터 통과 공고 수: 5
제외된 공고 수: 0

,company_name,job_title,career,location,posted_date,closing_date
0,GS리테일,"[GS리테일] 9·10월 통합공고(BIZ CLUB팀 경력사원, MD AX 담당, 물...",경력3년↑,서울 강남구 외 1,2026-09-21,2026-10-01 23:00
1,에스코어,AX 컨설턴트 채용,경력,서울 송파구,2026-07-01,2026-09-30 23:00
2,㈜NAVER,광고 프로덕트 기획 경력 채용(AX 광고 예산/과금 구조 설계 담당),경력,경기 성남시,2026-09-10,2026-09-29 10:00
3,㈜슈프리마,[슈프리마HQ] HRD & AX 담당자 모집,경력7년↑,경기 성남시,2026-08-26,2026-10-25 23:00
4,㈜NAVER,광고 프로덕트 기획 경력 채용(AX 광고 최적화 전략 담당),경력,경기 성남시,2026-09-10,2026-09-29 10:00

=== 공고별 매칭 키워드 (전체 공고 기준) ===
[통과] GS리테일 | [GS리테일] 9·10월 통합공고(BIZ CLUB팀 경력사원, MD AX 담당, 물류 AX 담당, 보안성 검토 담당)
        → 매칭 키워드: ['AX']
[통과] 에스코어 | AX 컨설턴트 채용
        → 매칭 키워드: ['AX']
[통과] ㈜NAVER | 광고 프로덕트 기획 경력 채용(AX 광고 예산/과금 구조 설계 담당)
        → 매칭 키워드: ['AX']
[통과] ㈜슈프리마 | [슈프리마HQ] HRD & AX 담당자 모집
        → 매칭 키워드: ['AX']
[통과] ㈜NAVER | 광고 프로덕트 기획 경력 채용(AX 광고 최적화 전략 담당)
        → 매칭 키워드: ['AX']

## 실행 결과 해석 / 분석 / 요약

- 셀이 에러 없이 실행되었다. (STEP 07-A → 07-B → 07-C → 07-F 순서로 실행)
- 전체 공고 수: 5
- 1차 필터 통과 공고 수: 5
- 제외된 공고 수: 0
- 사용한 필터 기준: `job_title`에 키워드 13개 중 하나라도 들어 있으면 통과 (소문자로 바꿔서 비교)
- 실제 매칭된 주요 키워드: **`AX` 하나뿐** — 5건 모두 `AX`로만 매칭되었고, 나머지 12개 키워드는 한 번도 매칭되지 않았다.
- 필터 결과 예시:

| company_name | 제목에서 매칭된 부분 | matched_keywords |
|---|---|---|
| GS리테일 | "MD **AX** 담당, 물류 **AX** 담당" | `['AX']` |
| 에스코어 | "**AX** 컨설턴트 채용" | `['AX']` |
| ㈜NAVER | "(**AX** 광고 예산/과금 구조 설계 담당)" | `['AX']` |
| ㈜슈프리마 | "HRD & **AX** 담당자 모집" | `['AX']` |
| ㈜NAVER | "(**AX** 광고 최적화 전략 담당)" | `['AX']` |

- 예상과 다른 부분: 없음. 검색어가 `ax`라서 전부 통과할 것으로 예상했고, 실제로 그랬다.
- 원본 보존: `df_unique_jobs`는 바뀌지 않았고 새 컬럼도 생기지 않았다. `matched_keywords`는 `df_filtered_jobs`에만 있다.
- 결과 DataFrame: `df_filtered_jobs` (5행 × 10열 = 기존 9개 컬럼 + `matched_keywords`)

해석 주의사항:
- 이번 결과는 **"1차 후보"**일 뿐이다. 제목에 `AX`가 있다고 우리가 원하는 AX 직무라는 뜻은 아니다.
  - 예: ㈜NAVER 2건은 "광고 프로덕트 기획" 직무이고, `AX`는 담당 업무 설명에 들어 있다.
  - 예: ㈜슈프리마는 "HRD & AX 담당자"로, 교육·인사(HRD)와 함께 묶인 직무이다.
- 반대로 제목에 키워드가 없어도 실제 업무는 AI/AX 관련일 수 있다. (이번에는 제목만 검사했다)
- 최종 의미 판단은 이후 Gemini 단계에서 한다.

한계 / 특이사항:
- 5건이 모두 통과해서 **"제외되는 경우"는 이번 데이터로 확인하지 못했다.** 검색어가 `ax` 하나라서 생긴 한계이다.
- 단순 포함 검색이라 짧은 키워드가 다른 단어 안에 들어 있어도 매칭될 수 있다.
  - 예: `ai`는 영어 단어 "m**ai**ntenance", "tr**ai**ning" 안에서도, `ax`는 "t**ax**", "m**ax**" 안에서도 매칭된다.
  - 이번 5건에서는 이런 잘못된 매칭이 없었지만, 검색어나 수집 범위를 넓히면 주의해야 한다.
- 키워드가 서로 겹친다. (예: `생성형 AI`, `AI Engineer`가 들어 있으면 `AI`도 함께 매칭된다) 통과 여부에는 영향이 없다.
- 다음 단계 진행 가능 여부: 사용자가 공고별 매칭 결과를 확인하면 진행 가능하다.

#### 초보자 설명
- `any()` → 여러 조건 중 **하나라도 True**인지 확인한다. 키워드 13개 중 하나만 들어 있어도 True가 된다.
- `apply()` → DataFrame/Series의 **각 값에 함수를 하나씩 적용**한다. 여기서는 공고 제목마다 `contains_relevance_keyword()`를 실행했다.
- `.copy()` → 필터링한 결과를 **원본과 분리된 새 DataFrame**으로 만든다. 그래서 `df_filtered_jobs`에 컬럼을 추가해도 `df_unique_jobs`는 바뀌지 않는다.

# STEP 07-G. 키워드 필터 오탐 검증 및 개선

## 작업 계획

STEP 07-F의 필터는 `keyword in title` 방식이다.
이 방식은 **글자가 포함되어 있는지만** 보기 때문에, 다른 단어 속에 우연히 들어간 글자도 매칭할 수 있다. (오탐 = false positive)
- 예: `ai` → "M**ai**ntenance", "Tr**ai**ning" / `ax` → "T**ax**", "M**ax**"

이번 단계에서는 **실데이터를 다시 크롤링하지 않고**, 직접 만든 테스트 제목으로 이 문제를 확인하고 매칭 규칙을 개선한다.
(STEP 07-F의 함수는 수정하지 않고, 새 함수 `find_matched_keywords_safe()`를 만든다)

테스트 제목:

| 구분 | 제목 | 기대 결과 |
|---|---|---|
| 매칭되어야 함 | AX 컨설턴트 채용 | True |
| 매칭되어야 함 | AI Engineer 모집 | True |
| 매칭되어야 함 | LLM 개발자 | True |
| 매칭되어야 함 | 생성형 AI 서비스 개발 | True |
| 매칭되어야 함 | 머신러닝 엔지니어 | True |
| 매칭되어야 함 | 데이터 분석 담당자 | True |
| 매칭되면 안 됨 | Tax Manager | False |
| 매칭되면 안 됨 | Max Performance Engineer | False |
| 매칭되면 안 됨 | Maintenance Engineer | False |
| 매칭되면 안 됨 | Training Manager | False |
| 추가 (한글이 바로 붙은 경우) | AX담당자 모집 | True |
| 추가 (한글이 바로 붙은 경우) | AI기반 서비스 기획 | True |

개선 방식 — 키워드 종류에 따라 검사 방법을 나눈다:
- **영문 키워드** (`AX`, `AI`, `LLM`, `Machine Learning`, `Data Scientist`, `AI Engineer`)
  → 정규식으로 "키워드 **앞뒤에 영문자·숫자가 붙어 있지 않을 때만**" 매칭한다.
  - `Tax`: `ax` 앞에 영문자 `T`가 붙어 있으므로 매칭 안 됨
  - `AX 담당`, `(AX`, `AX담당`: 앞뒤가 공백·괄호·한글이므로 매칭됨
- **한글이 들어 있는 키워드** (`인공지능`, `생성형 AI`, `생성형AI`, `머신러닝`, `데이터 분석`, `AI 엔지니어`, `데이터 사이언티스트`)
  → 기존처럼 포함 검색을 사용한다.

왜 흔히 쓰는 `\b`(단어 경계)를 그대로 쓰지 않는가:
- Python 정규식은 **한글도 "단어 글자"로 취급**한다.
- 그래서 `\bAX\b`는 `"AX 담당"`은 잡지만, 한글이 바로 붙은 `"AX담당"`은 놓친다.
- 이런 이유로 모든 키워드에 같은 정규식을 쓰지 않고, 영문 키워드에만 "영문자·숫자 경계"를 적용한다.
- 코드에서 기존 방식, `\b` 방식, 개선 방식을 나란히 비교해 확인한다.

실데이터 적용:
- `df_unique_jobs`가 **현재 메모리에 있을 때만** 새 함수를 적용해 `df_filtered_jobs_safe`에 저장한다.
- 없으면 데이터를 임의로 만들지 않고 안내만 출력한다.
- 원본 `df_unique_jobs`, `df_filtered_jobs`는 수정하지 않는다.

주의:
- 정규식이 직무 의미를 완벽히 판단해 주지는 않는다. 이번 목표는 **명백한 오탐(Tax / Max / Maintenance / Training)을 줄이는 것**이다.
- 직무 의미의 최종 판단은 이후 Gemini 단계에서 한다.

이번 단계에서 하지 않는 것:
- 웹 재요청, 크롤링 재실행, history 갱신
- Gemini API, 상세 페이지 수집, 점수화

완료 조건:
- 테스트 12개가 모두 기대 결과와 일치한다
- 기존 방식에서 오탐이 생기는 제목을 출력으로 확인한다

In [1]:
import re

# ----- 1) 키워드 (STEP 07-F와 같은 13개) -----
relevance_keywords = [
    "AX",
    "AI",
    "인공지능",
    "생성형 AI",
    "생성형AI",
    "LLM",
    "Machine Learning",
    "머신러닝",
    "Data Scientist",
    "데이터 사이언티스트",
    "AI Engineer",
    "AI 엔지니어",
    "데이터 분석",
]

# ----- 2) 테스트 데이터: (제목, 기대 결과) -----
test_titles = [
    ("AX 컨설턴트 채용", True),
    ("AI Engineer 모집", True),
    ("LLM 개발자", True),
    ("생성형 AI 서비스 개발", True),
    ("머신러닝 엔지니어", True),
    ("데이터 분석 담당자", True),
    ("Tax Manager", False),
    ("Max Performance Engineer", False),
    ("Maintenance Engineer", False),
    ("Training Manager", False),
    # 추가: 한글이 영문 키워드에 바로 붙은 경우 (\b 방식의 약점 확인용)
    ("AX담당자 모집", True),
    ("AI기반 서비스 기획", True),
]


# ----- 3) 기존 방식 (STEP 07-F와 같은 단순 포함 검색) — 비교용 -----
def find_matched_keywords_substring(title):
    title_lower = title.lower()
    return [k for k in relevance_keywords if k.lower() in title_lower]


# ----- 4) \b(단어 경계) 방식 — 비교용 -----
# Python에서는 한글도 "단어 글자"라서, "AX담당"처럼 한글이 바로 붙으면 경계로 인정되지 않는다
def find_matched_keywords_wordb(title):
    return [k for k in relevance_keywords
            if re.search(r"\b" + re.escape(k) + r"\b", title, re.IGNORECASE)]


# ----- 5) 개선 방식 -----
# 영문 키워드인지 확인: 알파벳·숫자·공백으로만 되어 있으면 영문 키워드로 본다
def is_english_keyword(keyword):
    return re.fullmatch(r"[A-Za-z0-9 ]+", keyword) is not None


def find_matched_keywords_safe(title):
    if not isinstance(title, str):
        return []
    matched = []
    for keyword in relevance_keywords:
        if is_english_keyword(keyword):
            # 영문 키워드: 앞뒤에 영문자·숫자가 "없을 때만" 매칭
            #   (?<![A-Za-z0-9]) → 바로 앞 글자가 영문자·숫자가 아니어야 함
            #   (?![A-Za-z0-9])  → 바로 뒤 글자가 영문자·숫자가 아니어야 함
            #   re.escape()      → 키워드 안의 특수문자를 글자 그대로 취급
            #   re.IGNORECASE    → 대소문자 구분 없이 비교
            pattern = r"(?<![A-Za-z0-9])" + re.escape(keyword) + r"(?![A-Za-z0-9])"
            if re.search(pattern, title, re.IGNORECASE):
                matched.append(keyword)
        else:
            # 한글이 들어 있는 키워드: 기존처럼 포함 검색
            if keyword.lower() in title.lower():
                matched.append(keyword)
    return matched


# ----- 6) 테스트 실행: 개선 방식이 기대 결과와 같은지 확인 -----
print("=== 개선 방식(find_matched_keywords_safe) 테스트 ===")
pass_count = 0
for title, expected in test_titles:
    matched = find_matched_keywords_safe(title)
    actual = len(matched) > 0
    result = "PASS" if actual == expected else "FAIL"
    if result == "PASS":
        pass_count += 1
    print(f"[{result}] {title}")
    print(f"    expected={expected}  actual={actual}  matched={matched}")
    if result == "FAIL":
        print("    → 실패 원인 확인 필요: 기대와 다른 키워드 매칭 결과")

print("\n전체 테스트:", len(test_titles))
print("통과:", pass_count)
print("실패:", len(test_titles) - pass_count)

# ----- 7) 세 방식 비교: 기존 방식에서 어떤 오탐/누락이 생기는지 확인 -----
print("\n=== 방식별 비교 (기대와 다르면 ✗) ===")
for title, expected in test_titles:
    row = []
    for name, func in [("기존 포함검색", find_matched_keywords_substring),
                       ("\\b 방식", find_matched_keywords_wordb),
                       ("개선 방식", find_matched_keywords_safe)]:
        matched = func(title)
        mark = "✓" if (len(matched) > 0) == expected else "✗"
        row.append(f"{name} {mark} {matched}")
    print(f"{title}  (기대={expected})")
    print("    " + " | ".join(row))

# ----- 8) 실데이터 적용 (df_unique_jobs가 메모리에 있을 때만) -----
print("\n=== 실데이터 적용 ===")
if "df_unique_jobs" not in globals():
    print("df_unique_jobs가 현재 메모리에 없어 실데이터 적용을 건너뜁니다.")
    print("실데이터에 적용하려면 STEP 07-A → 07-B → 07-C를 먼저 실행한 뒤 이 셀을 다시 실행하세요.")
else:
    safe_matches = df_unique_jobs["job_title"].apply(find_matched_keywords_safe)
    df_filtered_jobs_safe = df_unique_jobs[safe_matches.apply(len) > 0].copy()
    df_filtered_jobs_safe["matched_keywords"] = safe_matches[safe_matches.apply(len) > 0]

    print("전체 공고 수:", len(df_unique_jobs))
    print("개선 필터 통과 수:", len(df_filtered_jobs_safe))
    for title, company, matched in zip(df_unique_jobs["job_title"], df_unique_jobs["company_name"], safe_matches):
        print(f"[{'통과' if matched else '제외'}] {company} | {title}")
        print(f"        → 매칭 키워드: {matched if matched else '없음'}")

=== 개선 방식(find_matched_keywords_safe) 테스트 ===
[PASS] AX 컨설턴트 채용
    expected=True  actual=True  matched=['AX']
[PASS] AI Engineer 모집
    expected=True  actual=True  matched=['AI', 'AI Engineer']
[PASS] LLM 개발자
    expected=True  actual=True  matched=['LLM']
[PASS] 생성형 AI 서비스 개발
    expected=True  actual=True  matched=['AI', '생성형 AI']
[PASS] 머신러닝 엔지니어
    expected=True  actual=True  matched=['머신러닝']
[PASS] 데이터 분석 담당자
    expected=True  actual=True  matched=['데이터 분석']
[PASS] Tax Manager
    expected=False  actual=False  matched=[]
[PASS] Max Performance Engineer
    expected=False  actual=False  matched=[]
[PASS] Maintenance Engineer
    expected=False  actual=False  matched=[]
[PASS] Training Manager
    expected=False  actual=False  matched=[]
[PASS] AX담당자 모집
    expected=True  actual=True  matched=['AX']
[PASS] AI기반 서비스 기획
    expected=True  actual=True  matched=['AI']

전체 테스트: 12
통과: 12
실패: 0

=== 방식별 비교 (기대와 다르면 ✗) ===
AX 컨설턴트 채용  (기대=True)
    기존 포함검색 ✓ ['AX'] | \b 방식 ✓ ['AX'] | 개선 방식 ✓ ['AX']
AI Engineer 모집  (기대=True)
    기존 포함검색 ✓ ['AI', 'AI Engineer'] | \b 방식 ✓ ['AI', 'AI Engineer'] | 개선 방식 ✓ ['AI', 'AI Engineer']
LLM 개발자  (기대=True)
    기존 포함검색 ✓ ['LLM'] | \b 방식 ✓ ['LLM'] | 개선 방식 ✓ ['LLM']
생성형 AI 서비스 개발  (기대=True)
    기존 포함검색 ✓ ['AI', '생성형 AI'] | \b 방식 ✓ ['AI', '생성형 AI'] | 개선 방식 ✓ ['AI', '생성형 AI']
머신러닝 엔지니어  (기대=True)
    기존 포함검색 ✓ ['머신러닝'] | \b 방식 ✓ ['머신러닝'] | 개선 방식 ✓ ['머신러닝']
데이터 분석 담당자  (기대=True)
    기존 포함검색 ✓ ['데이터 분석'] | \b 방식 ✓ ['데이터 분석'] | 개선 방식 ✓ ['데이터 분석']
Tax Manager  (기대=False)
    기존 포함검색 ✗ ['AX'] | \b 방식 ✓ [] | 개선 방식 ✓ []
Max Performance Engineer  (기대=False)
    기존 포함검색 ✗ ['AX'] | \b 방식 ✓ [] | 개선 방식 ✓ []
Maintenance Engineer  (기대=False)
    기존 포함검색 ✗ ['AI'] | \b 방식 ✓ [] | 개선 방식 ✓ []
Training Manager  (기대=False)
    기존 포함검색 ✗ ['AI'] | \b 방식 ✓ [] | 개선 방식 ✓ []
AX담당자 모집  (기대=True)
    기존 포함검색 ✓ ['AX'] | \b 방식 ✗ [] | 개선 방식 ✓ ['AX']
AI기반 서비스 기획  (기대=True)
    기존 포함검색 ✓ ['AI'] | \b 방식 ✗ [] | 개선 방식 ✓ ['AI']

=== 실데이터 적용 ===
df_unique_jobs가 현재 메모리에 없어 실데이터 적용을 건너뜁니다.
실데이터에 적용하려면 STEP 07-A → 07-B → 07-C를 먼저 실행한 뒤 이 셀을 다시 실행하세요.

## 실행 결과 해석 / 분석 / 요약

- 셀이 에러 없이 실행되었다. (웹 요청 없음, 테스트 데이터만 사용)
- 테스트 케이스 수: 12 (요청된 10개 + 한글이 바로 붙은 경우 2개)
- 기대 결과와 일치한 수: 12
- 실패 수: 0

방식별 비교 결과:

| 제목 | 기대 | 기존 포함검색 | `\b` 방식 | 개선 방식 |
|---|---|---|---|---|
| Tax Manager | False | ✗ `['AX']` 오탐 | ✓ | ✓ |
| Max Performance Engineer | False | ✗ `['AX']` 오탐 | ✓ | ✓ |
| Maintenance Engineer | False | ✗ `['AI']` 오탐 | ✓ | ✓ |
| Training Manager | False | ✗ `['AI']` 오탐 | ✓ | ✓ |
| AX담당자 모집 | True | ✓ | ✗ 누락 | ✓ `['AX']` |
| AI기반 서비스 기획 | True | ✓ | ✗ 누락 | ✓ `['AI']` |
| 나머지 6개 (AX 컨설턴트 채용 등) | True | ✓ | ✓ | ✓ |

- 기존 substring 방식의 문제: 글자 포함 여부만 보기 때문에 `Tax`/`Max` 안의 `ax`, `Maintenance`/`Training` 안의 `ai`까지 매칭했다. → **4건 오탐**
- `\b` 방식의 문제: 오탐은 없앴지만, Python에서는 한글도 단어 글자로 취급되어 `AX담당자`, `AI기반`처럼 한글이 바로 붙은 경우를 놓쳤다. → **2건 누락**
- 개선 방식:
  - 영문 키워드(`AX`, `AI`, `LLM`, `Machine Learning`, `Data Scientist`, `AI Engineer`)는
    "앞뒤에 **영문자·숫자**가 붙어 있지 않을 때만" 매칭한다. (`(?<![A-Za-z0-9])키워드(?![A-Za-z0-9])`, 대소문자 무시)
  - 한글이 들어 있는 키워드는 기존처럼 포함 검색을 사용한다.
  - → 오탐 4건, 누락 2건 모두 해결
- Tax 오탐 여부: 없음 (개선 방식)
- Max 오탐 여부: 없음
- Maintenance 오탐 여부: 없음
- Training 오탐 여부: 없음

실데이터 적용:
- 실데이터 5건 필터 결과: **이번 실행에서는 적용하지 않았다.**
  - 이번 작업은 웹 재요청이 금지라서 STEP 07-A를 실행하지 않았고, 그래서 `df_unique_jobs`가 메모리에 없었다.
  - 코드는 데이터를 임의로 만들지 않고 "건너뜁니다" 안내만 출력했다.
  - 참고: history 파일의 실제 제목 5개를 **읽기만 해서** 새 함수에 넣어 보면 5건 모두 `['AX']`로 매칭된다. (기존 07-F 결과와 동일, 이 확인은 Notebook에 저장하지 않음)
- `df_unique_jobs` 원본 보존 여부: 이번 셀은 `df_unique_jobs`를 읽기만 하도록 작성했다. (이번 실행에서는 메모리에 없었음)
- `df_filtered_jobs_safe` 생성 여부: 이번 실행에서는 생성되지 않았다. STEP 07-A → 07-B → 07-C 실행 후 이 셀을 다시 실행하면 생성된다.
- `df_filtered_jobs`(STEP 07-F 결과)와 STEP 07-F 함수는 수정하지 않았다.

한계:
- 정규식은 글자 모양만 검사할 뿐 **직무 의미를 판단하지 않는다.** 이번 목표는 명백한 오탐(Tax / Max / Maintenance / Training)을 줄이는 것이었다.
- `OpenAI`처럼 영문자가 붙은 표현은 이제 `AI`로 매칭되지 않는다. 필요하면 키워드를 따로 추가해야 한다.
- 직무 의미의 최종 판단은 이후 Gemini 단계에서 한다.
- 다음 단계 진행 가능 여부: 사용자가 실데이터에 적용한 결과(`df_filtered_jobs_safe`)까지 확인하면 진행 가능하다.

#### 초보자 설명
- **substring**(부분 문자열) → 단순히 **글자가 포함되어 있는지만** 확인한다. `"ax" in "tax"`도 True가 된다.
- **regex**(정규식) → 문자열 **패턴을 더 구체적으로** 검사할 수 있다. 예: "앞 글자가 영문자가 아닐 것"
- **word boundary**(`\b`, 단어 경계) → 독립된 단어인지 구분할 때 도움이 된다.
  하지만 Python에서는 한글도 단어 글자로 보기 때문에, 한글 제목에서는 이번처럼 "영문자·숫자 경계"를 직접 지정하는 편이 더 정확하다.

# STEP 07-H. Gemini API 환경변수 준비

## 작업 계획

이번 단계에서는 **Gemini API를 호출하지 않는다.**
다음 단계에서 Gemini를 쓰기 전에, API 키를 안전하게 보관하고 읽어 오는 준비만 한다.

왜 필요한가:
- API Key는 **비밀번호와 비슷한 민감정보**이다.
- Notebook 코드에 직접 적으면, Notebook을 Git에 올리거나 다른 사람에게 공유할 때 키가 그대로 노출된다.
- 그래서 키는 코드가 아니라 **`.env` 파일**에 따로 저장하고, 코드에서는 이름(`GEMINI_API_KEY`)으로만 읽어 온다.

목표:
- API 키를 코드에 직접 쓰지 않기
- `.env`에 비밀값 저장 (사용자가 직접 작성)
- `python-dotenv`의 `load_dotenv()`로 환경변수 읽기
- Notebook에서 `GEMINI_API_KEY`가 **있는지 없는지만** 확인 (값은 출력하지 않는다)

준비된 파일 (프로젝트 루트 `chapter11/ax-job-agent/`):
- `.env.example` → 필요한 환경변수 이름만 적어 둔 샘플 (Git에 포함)
- `.gitignore` → `.env`, `.venv/`, `__pycache__/`, `.ipynb_checkpoints/`를 Git에서 제외
- `.env` → **사용자가 직접 만든다.** (Claude Code는 이 파일을 만들거나 값을 넣지 않는다)

코드에서 하는 일:
- Notebook은 `notebooks/` 폴더에서 실행되므로, 한 단계 위를 프로젝트 루트로 보고 `.env`를 찾는다.
- `.env`가 있으면 불러오고, 없으면 오류로 멈추지 않고 만드는 방법을 안내한다.
- 키는 "설정됨 / 미설정"으로만 출력한다. (키 값, 키 길이, 앞뒤 일부도 출력하지 않는다)

이번 단계에서 하지 않는 것:
- Gemini API 호출, API Key 생성·입력
- Slack / Gmail, 새 패키지 설치, 크롤링 재실행

성공 기준:
- `.env.example`이 있다
- `.gitignore`에서 `.env`가 제외된다
- Notebook에서 `.env`를 찾고 `GEMINI_API_KEY` 설정 여부를 확인할 수 있다
- 실제 키 값은 화면에 출력되지 않는다

In [9]:
from pathlib import Path
import os
from dotenv import load_dotenv

# ----- 1) 프로젝트 루트의 .env 경로 찾기 -----
# Notebook은 notebooks/ 폴더에서 실행되므로, 그 경우 한 단계 위를 프로젝트 루트로 사용한다
current_dir = Path.cwd()
project_root = current_dir.parent if current_dir.name == "notebooks" else current_dir
env_path = project_root / ".env"

print("프로젝트 루트:", project_root)
print(".env 파일 존재 여부:", env_path.exists())

# ----- 2) .env가 있으면 불러오기 -----
# load_dotenv(): .env 파일의 "이름=값"을 읽어서 Python 환경변수로 등록한다
if env_path.exists():
    load_dotenv(env_path)
else:
    print("\n.env 파일이 없습니다.")
    print("프로젝트 루트에 .env 파일을 만들고")
    print("GEMINI_API_KEY=본인의_API_키")
    print("형태로 입력하세요. (.env.example 파일을 복사해서 만들면 편합니다)")

# ----- 3) GEMINI_API_KEY 설정 여부만 확인 (값은 절대 출력하지 않는다) -----
gemini_api_key = os.getenv("GEMINI_API_KEY")
print("\nGEMINI_API_KEY 설정 여부:", "설정됨" if gemini_api_key else "미설정")

# 참고: .env가 없는데 "설정됨"이면, Windows 시스템 환경변수에 이미 등록된 값이다
if gemini_api_key and not env_path.exists():
    print("(참고: .env가 아니라 시스템 환경변수에서 읽은 값입니다)")

프로젝트 루트: c:\dev\claude-code-agent-course\chapter11\ax-job-agent
.env 파일 존재 여부: True

GEMINI_API_KEY 설정 여부: 설정됨

## 실행 결과 해석 / 분석 / 요약

- 셀이 에러 없이 실행되었다. (Gemini API 호출 없음, 웹 요청 없음)
- 프로젝트 루트 계산: `notebooks/`에서 실행 → 한 단계 위인 `chapter11/ax-job-agent`를 정상적으로 찾았다.
- `.env` 파일 존재 여부: **없음** — 아직 사용자가 만들지 않은 상태이다. 코드는 오류로 멈추지 않고 만드는 방법을 안내했다.
- `GEMINI_API_KEY` 설정 여부: **미설정** — `.env`가 없고, 시스템 환경변수에도 등록되어 있지 않다.
- API Key 값이 화면에 노출됐는지: **노출되지 않음** — 코드는 "설정됨 / 미설정"만 출력하고, 키 값·길이·일부 글자는 출력하지 않는다.
- `.env`가 Git 제외 대상인지: **예** — 프로젝트 루트 `.gitignore`에 `.env`를 추가했고, `git check-ignore`로 제외되는 것을 확인했다.
  (`.venv/`, `__pycache__/`, `.ipynb_checkpoints/`도 함께 제외)
- `.env.example` 존재 여부: **있음** — `GEMINI_API_KEY`, `SLACK_WEBHOOK_URL`, `GMAIL_USER`, `GMAIL_APP_PASSWORD` 이름만 빈 값으로 들어 있다. 이 파일은 Git에 포함된다.
- 다음 단계 진행 가능 여부: 준비 작업(파일·코드)은 완료되었다.
  사용자가 `.env`를 직접 만들고 키를 입력한 뒤, 이 셀을 다시 실행해 **"설정됨"**이 나오면 Gemini 연동 단계로 진행할 수 있다.

#### 사용자가 직접 할 일
1. 프로젝트 루트(`chapter11/ax-job-agent/`)에서 `.env.example`을 복사해 이름을 `.env`로 바꾼다.
2. `GEMINI_API_KEY=` 뒤에 본인의 API 키를 붙여 넣는다. (따옴표·공백 없이)
3. 이 셀을 다시 실행해 `.env 파일 존재 여부: True`, `GEMINI_API_KEY 설정 여부: 설정됨`인지 확인한다.

#### 초보자 설명
- `.env` → 실제 비밀값을 저장하는 **로컬 파일**이다. 내 컴퓨터에만 두고 Git에는 올리지 않는다.
- `.env.example` → 어떤 환경변수가 필요한지 보여 주는 **샘플 파일**이다. 값은 비워 두고 Git에 올린다.
- `.gitignore` → Git에 **올리지 않을 파일**을 지정하는 파일이다.
- `load_dotenv()` → `.env`의 값을 **Python 환경변수로 읽어 오는** 기능이다. 이후 `os.getenv("이름")`으로 꺼내 쓴다.

# STEP 07-I. Gemini API 최소 연결 테스트

## 작업 계획

STEP 07-H에서는 `GEMINI_API_KEY`가 **있는지**만 확인했다.
이번 단계에서는 그 키로 **실제로 Gemini API를 1번 호출**해서, 연결이 정상인지 확인한다.

이번 단계 목적:
- `GEMINI_API_KEY`가 실제 API 호출에 사용 가능한지 확인
- Gemini 서버와 통신이 되는지 확인
- 응답 텍스트를 정상적으로 받을 수 있는지 확인

사용 도구:
- Google 공식 Python SDK **`google-genai`** (`from google import genai`)
  - 예전 패키지인 `google-generativeai`는 사용하지 않는다.
- 모델: `gemini-3.6-flash` (Flash 계열)
  - 이 모델을 쓸 수 없다는 오류가 나오면, 다른 모델을 여러 번 시도하지 않고 오류를 기록한 뒤 사용 가능한 모델을 확인한다.

보내는 내용:
- 아주 짧은 연결 테스트 문장 **1개만** 보낸다. (비용과 호출 횟수를 최소화)

보안 원칙:
- API 키 값, 키 일부, 키 길이, `.env` 내용은 **절대 출력하지 않는다.**
- 오류가 나면 오류 종류와 메시지만 출력하되, 메시지 안에 키가 섞여 있을 경우를 대비해 키 부분은 `***`로 가린다.

아직 하지 않는 것:
- 채용공고 5건 요약
- 반복 호출
- JSON 구조화
- 비용이 커질 수 있는 긴 프롬프트
- 상세 페이지 내용 전달
- Slack / Gmail 연동

성공 기준:
- API 호출 오류 없음
- Gemini가 짧은 텍스트 응답을 반환
- API 키가 화면에 출력되지 않음

In [1]:
from pathlib import Path
import os
from dotenv import load_dotenv
from google import genai

# ----- 1) 프로젝트 루트의 .env 읽기 (STEP 07-H와 같은 방식) -----
current_dir = Path.cwd()
project_root = current_dir.parent if current_dir.name == "notebooks" else current_dir
env_path = project_root / ".env"

print(".env 파일 존재 여부:", env_path.exists())
if env_path.exists():
    load_dotenv(env_path)

# ----- 2) API 키 확인 (값은 절대 출력하지 않는다) -----
gemini_api_key = os.getenv("GEMINI_API_KEY")
print("GEMINI_API_KEY 설정 여부:", "설정됨" if gemini_api_key else "미설정")

MODEL_NAME = "gemini-3.6-flash"

if not gemini_api_key:
    print("\nGEMINI_API_KEY가 없어 API를 호출하지 않습니다.")
    print("프로젝트 루트의 .env 파일에 GEMINI_API_KEY=본인의_API_키 를 입력한 뒤 다시 실행하세요.")
else:
    # ----- 3) Gemini Client 생성 -----
    # client: Gemini API에 요청을 보내기 위한 연결 객체
    client = genai.Client(api_key=gemini_api_key)

    # ----- 4) 아주 짧은 프롬프트 1개만 전송 -----
    test_prompt = (
        "연결 테스트입니다. "
        "한국어로 'Gemini API 연결 성공'이라고 짧게 답해 주세요."
    )
    print("\n사용 모델:", MODEL_NAME)

    try:
        # generate_content(): 프롬프트를 보내고 응답을 받는 함수 (이 셀에서 1번만 호출)
        response = client.models.generate_content(
            model=MODEL_NAME,
            contents=test_prompt,
        )
        # response.text: Gemini가 만든 텍스트 결과
        print("\nGemini 응답:")
        print(response.text)
    except Exception as e:
        # 오류 메시지 안에 혹시 키가 들어 있으면 *** 로 가린 뒤 출력한다
        safe_message = str(e).replace(gemini_api_key, "***")
        print("\nGemini API 호출 실패")
        print("오류 종류:", type(e).__name__)
        print("오류 메시지:", safe_message[:500])

Direct use of automatic function calling (AFC) in Models.generate_content is not recommended. Instead, we recommend to use AFC in Chat.send_message. Similarly, direct use of AFC in Models.generate_content_stream is not recommended. Instead, we recommend to use AFC in Chat.send_message_stream.

.env 파일 존재 여부: True
GEMINI_API_KEY 설정 여부: 설정됨

사용 모델: gemini-3.6-flash

Gemini 응답:
Gemini API 연결 성공

## 실행 결과 해석 / 분석 / 요약

- 셀이 에러 없이 실행되었다. (API 호출 **1회**)
- google-genai 설치 여부: **설치됨** — 이번 STEP에서 프로젝트 가상환경에 `google-genai` 2.25.0을 설치했다. (구버전 `google-generativeai`는 사용하지 않음)
- .env 로드 여부: **로드됨** — 프로젝트 루트의 `.env`를 찾아 `load_dotenv()`로 읽었다.
- GEMINI_API_KEY 설정 여부: **설정됨**
- 사용한 모델: `gemini-3.6-flash`
- API 호출 성공 여부: **성공**
- 응답 텍스트 수신 여부: **수신됨** — 응답: `Gemini API 연결 성공`
- API 키 노출 여부: **노출되지 않음** — 출력에는 "설정됨"만 표시되고, 저장된 셀 출력에 키 문자열이 없는 것도 확인했다.
- 오류가 있었다면 오류 종류: 오류 없음.
  - 참고: 출력 맨 위의 `Direct use of automatic function calling (AFC) ...` 문구는 오류가 아니라 SDK가 보여 주는 **안내(경고) 메시지**이다.
    AFC는 Gemini가 Python 함수를 대신 호출하게 하는 기능인데, 이번 호출에서는 사용하지 않았으므로 결과에 영향이 없다.
- 다음 단계 진행 가능 여부: **진행 가능** — `.env → 키 로드 → Client 생성 → 짧은 프롬프트 1회 → response.text 수신` 흐름이 실제로 동작했다.

주의:
- 이 셀을 실행할 때마다 API가 1번 호출된다. 불필요하게 반복 실행하지 않는다.
- 채용공고 요약처럼 긴 내용을 보내는 작업은 다음 단계에서 호출 횟수와 입력 길이를 정해 진행한다.

#### 초보자 설명
- `client` → Gemini API에 요청을 보내기 위한 **연결 객체**이다. API 키를 넣어 한 번 만들어 두고 계속 사용한다.
- `generate_content()` → 프롬프트를 보내고 **응답을 받는 함수**이다. `model`에 사용할 모델, `contents`에 보낼 내용을 넣는다.
- `response.text` → Gemini가 생성한 **텍스트 결과**이다.

# STEP 09. 실제 채용공고 Gemini 요약 호출

## 작업 계획

STEP 09의 앞선 준비(07-H, 07-I)에서는 짧은 연결 테스트 문장만 보내 Gemini 연결을 확인했다.
이번에는 **실제로 수집한 채용공고 데이터**를 Gemini에 보내서 요약 응답을 받아 본다.

이번 STEP의 목적:
- 실제 채용공고 데이터를 Gemini에 보내 보기
- 연결 테스트를 넘어, 실제 데이터를 입력했을 때도 정상 응답이 오는지 검증하기
- Gemini가 **제공된 정보만 사용**하도록 제한하기

사용할 데이터 (웹 재요청 없음):
1. 현재 커널에 `df_unique_jobs`(STEP 07-A → 07-B → 07-C 결과)가 있으면 그것을 사용한다.
2. 없으면 `data/processed/jobs_history.csv`를 **읽기만** 해서 사용한다. (파일은 수정하지 않는다)
- 이 중 **앞 2건만** Gemini에 보낸다. (API 연동 검증이 목적이라 호출을 최소화)

Gemini에 보내는 정보 (현재 데이터에 실제로 있는 값만):
- `company_name`, `job_title`, `career`, `location`
- `posted_date`(= 지원 제출 시작일), `closing_date`(= 지원 제출 마감일)
- `search_keyword`, `job_url`

왜 "추측 금지"를 명시하는가:
- 아직 공고 **상세 페이지 본문은 수집하지 않았다.** 그래서 상세 업무, 기술 스택, 자격요건, 우대사항은 데이터에 없다.
- 생성형 AI는 정보가 없어도 그럴듯한 내용을 지어낼 수 있다.
- 그래서 프롬프트에 "제공된 정보만 사용하고, 확인할 수 없는 항목은 '확인 불가'라고 적으라"는 제약과 응답 형식을 함께 준다.

호출 규칙:
- 모델: `gemini-3.6-flash`
- 공고 1건당 1회 호출 → **최대 2회**
- 응답은 메모리 변수 `gemini_results`(리스트)에만 저장한다. (DataFrame·CSV로 저장하지 않음)
- API 키 값은 출력하지 않는다.

이번 STEP에서 하지 않는 것:
- 상세 페이지 요청, 웹 재요청
- 공고 5건 전체 처리
- 원문과 Gemini 결과 비교 평가, 정확도 판정 (→ STEP 10)
- 추천 점수, 저장 자동화

완료 기준:
- 실제 공고 1~2건을 Gemini에 전달
- 실제 응답을 정상 수신
- API Key 미노출
- 제공되지 않은 정보는 "확인 불가"로 처리

In [1]:
from pathlib import Path
import os
import pandas as pd
from dotenv import load_dotenv
from google import genai

MODEL_NAME = "gemini-3.6-flash"
MAX_JOBS_FOR_GEMINI = 2  # 이번 STEP에서는 최대 2건만 보낸다 (= 최대 2회 호출)

# ----- 1) 프로젝트 루트의 .env 로드 -----
current_dir = Path.cwd()
project_root = current_dir.parent if current_dir.name == "notebooks" else current_dir
env_path = project_root / ".env"
if env_path.exists():
    load_dotenv(env_path)

# API 키는 설정 여부만 출력한다 (값은 절대 출력하지 않음)
gemini_api_key = os.getenv("GEMINI_API_KEY")
print("GEMINI_API_KEY 설정 여부:", "설정됨" if gemini_api_key else "미설정")

# ----- 2) 데이터 준비 (웹 재요청 없음) -----
if "df_unique_jobs" in globals():
    source_df = df_unique_jobs.copy()
    data_source = "df_unique_jobs (현재 커널 메모리)"
else:
    # history CSV는 읽기만 한다 (저장하지 않음)
    history_path = project_root / "data" / "processed" / "jobs_history.csv"
    source_df = pd.read_csv(history_path)
    data_source = f"{history_path.name} (읽기 전용)"
print("데이터 출처:", data_source)
print("전체 공고 수:", len(source_df))

# 앞 2건만 선택
sample_jobs_for_gemini = source_df.head(MAX_JOBS_FOR_GEMINI).copy()
print("Gemini에 전달할 공고 수:", len(sample_jobs_for_gemini))


# ----- 3) 공고 1건으로 프롬프트 만들기 -----
def show_value(value):
    # 값이 비어 있으면(None/NaN) '정보 없음'으로 표시해서, 빈 값을 Gemini가 추측하지 않게 한다
    return "정보 없음" if pd.isna(value) else str(value)


def build_prompt(job):
    return f"""당신은 채용공고 정보를 정리하는 도우미입니다.

아래에 제공된 채용공고 정보만 사용하세요.
제공되지 않은 세부 업무, 기술 스택, 자격요건은 추측하지 마세요.
확인할 수 없는 항목은 '확인 불가'라고 적으세요.

[제공된 채용공고 정보]
- 회사명: {show_value(job["company_name"])}
- 공고 제목: {show_value(job["job_title"])}
- 경력: {show_value(job["career"])}
- 근무 지역: {show_value(job["location"])}
- 지원 시작일: {show_value(job["posted_date"])}
- 지원 마감일: {show_value(job["closing_date"])}
- 검색어: {show_value(job["search_keyword"])}
- 공고 URL: {show_value(job["job_url"])}

아래 형식 그대로 한국어로 답하세요.

[회사명]
...

[공고 제목]
...

[한줄 요약]
...

[확인 가능한 정보]
- 경력:
- 지역:
- 지원 시작일:
- 지원 마감일:
- 검색어:

[AX/AI 관련성]
- 제목에서 확인되는 범위만 설명

[확인 불가]
- 상세 업무
- 상세 기술 스택
- 자격요건
- 우대사항
"""


# ----- 4) Gemini 호출 (공고당 1회, 최대 2회) -----
gemini_results = []  # 응답은 메모리 변수에만 저장한다
call_count = 0
success_count = 0
fail_count = 0

if not gemini_api_key:
    print("\nGEMINI_API_KEY가 없어 API를 호출하지 않습니다. .env 파일을 확인하세요.")
else:
    client = genai.Client(api_key=gemini_api_key)

    for _, job in sample_jobs_for_gemini.iterrows():
        prompt = build_prompt(job)
        call_count += 1
        try:
            response = client.models.generate_content(model=MODEL_NAME, contents=prompt)
            summary = response.text
            success_count += 1
        except Exception as e:
            # 오류 메시지 안에 혹시 키가 들어 있으면 *** 로 가린다
            summary = None
            fail_count += 1
            print("\nGemini API 호출 실패:", type(e).__name__, str(e).replace(gemini_api_key, "***")[:300])

        gemini_results.append({
            "company_name": job["company_name"],
            "job_title": job["job_title"],
            "job_url": job["job_url"],
            "gemini_summary": summary,
        })

# ----- 5) 공고별 응답 출력 -----
for result in gemini_results:
    print("\n" + "=" * 30)
    print("회사:", result["company_name"])
    print("공고:", result["job_title"])
    print("=" * 30)
    print("\nGemini 응답:")
    print(result["gemini_summary"] if result["gemini_summary"] else "(응답 없음)")

print("\n사용 모델:", MODEL_NAME)
print("Gemini 호출 횟수:", call_count)
print("호출 성공:", success_count, "/ 호출 실패:", fail_count)

Direct use of automatic function calling (AFC) in Models.generate_content is not recommended. Instead, we recommend to use AFC in Chat.send_message. Similarly, direct use of AFC in Models.generate_content_stream is not recommended. Instead, we recommend to use AFC in Chat.send_message_stream.

GEMINI_API_KEY 설정 여부: 설정됨
데이터 출처: jobs_history.csv (읽기 전용)
전체 공고 수: 5
Gemini에 전달할 공고 수: 2

Gemini API 호출 실패: ServerError 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}

==============================
회사: GS리테일
공고: [GS리테일] 9·10월 통합공고(BIZ CLUB팀 경력사원, MD AX 담당, 물류 AX 담당, 보안성 검토 담당)
==============================

Gemini 응답:
(응답 없음)

==============================
회사: 에스코어
공고: AX 컨설턴트 채용
==============================

Gemini 응답:
[회사명]
에스코어

[공고 제목]
AX 컨설턴트 채용

[한줄 요약]
에스코어에서 서울 송파구 근무 조건으로 경력직 AX 컨설턴트를 채용합니다.

[확인 가능한 정보]
- 경력: 경력
- 지역: 서울 송파구
- 지원 시작일: 2026-07-01
- 지원 마감일: 2026-09-30 23:00
- 검색어: ax

[AX/AI 관련성]
- 공고 제목에 'AX 컨설턴트'가 명시되어 있어 AX(AI Transformation) 관련 컨설팅 직무임을 확인할 수 있습니다.

[확인 불가]
- 상세 업무: 확인 불가
- 상세 기술 스택: 확인 불가
- 자격요건: 확인 불가
- 우대사항: 확인 불가

사용 모델: gemini-3.6-flash
Gemini 호출 횟수: 2
호출 성공: 1 / 호출 실패: 1

## 실행 결과 해석 / 분석 / 요약

- 셀이 멈추지 않고 끝까지 실행되었다. (웹 요청 없음, history CSV는 읽기만 함)
- 데이터 출처: `jobs_history.csv` (읽기 전용) — 실행 커널에 `df_unique_jobs`가 없어서 history 파일을 사용했다.
- Gemini에 전달한 공고 수: **2건** (앞 2건: GS리테일, 에스코어)
- Gemini API 호출 횟수: **2회** (공고당 1회, 최대 2회 규칙 준수 — 재시도 없음)
- 호출 성공 건수: **1건** (에스코어)
- 호출 실패 건수: **1건** (GS리테일)
- 사용 모델: `gemini-3.6-flash`
- API Key 노출 여부: **노출되지 않음** — "설정됨"만 출력했고, 저장된 셀 출력에 키 문자열이 없는 것을 확인했다.

각 공고 응답 수신 여부:

| 공고 | 결과 | 내용 |
|---|---|---|
| GS리테일 — [GS리테일] 9·10월 통합공고(...) | ❌ 실패 | `ServerError 503 UNAVAILABLE` — "This model is currently experiencing high demand. ... Please try again later." |
| 에스코어 — AX 컨설턴트 채용 | ✅ 수신 | 요청한 형식([회사명] ~ [확인 불가])대로 응답 |

- "확인 불가" 처리 여부: 응답을 받은 에스코어 공고에서 **상세 업무 / 상세 기술 스택 / 자격요건 / 우대사항 4개 모두 "확인 불가"**로 적혔다.
  제공한 정보(경력, 지역, 지원 시작일·마감일, 검색어)는 [확인 가능한 정보]에 들어갔다.
- 예상과 다른 부분:
  - GS리테일 호출이 **503 오류**로 실패했다. 이것은 코드나 API 키 문제가 아니라, Gemini 서버에 요청이 몰려 **일시적으로** 응답하지 못한 경우이다.
    (같은 셀에서 바로 다음 에스코어 호출은 성공했다)
  - 이번 STEP은 최대 2회 호출 규칙이 있어서 재시도하지 않았다.
- STEP 09 완료 조건 충족 여부:
  - 실제 공고 1~2건을 Gemini에 전달 → **충족** (2건 전달)
  - 실제 응답을 정상 수신 → **충족** (1건 수신)
  - API Key 미노출 → **충족**
  - 제공되지 않은 정보는 "확인 불가"로 처리 → **충족** (응답을 받은 1건 기준)
  - → 완료 조건은 충족했다. 다만 2건 중 1건은 서버 과부하로 응답을 받지 못했다.

참고:
- 이 셀에서는 Gemini 응답이 **정확한지 평가하지 않는다.** 원본 데이터와 응답을 한 줄씩 비교하는 검증은 STEP 10에서 한다.
- 출력 맨 위의 `Direct use of automatic function calling (AFC) ...` 문구는 오류가 아니라 SDK 안내 메시지이다. (이번 호출은 AFC 미사용)
- 이 셀을 다시 실행하면 Gemini가 다시 최대 2회 호출된다. GS리테일 응답이 필요하면 시간을 두고 한 번만 다시 실행한다.
- 응답은 메모리 변수 `gemini_results`에만 있고, 파일로 저장하지 않았다.

# STEP 10. Gemini 결과 검증

## 작업 계획

STEP 09에서 Gemini가 만든 요약을 **원본 채용공고 데이터와 직접 비교**해서, Gemini의 말을 믿어도 되는지 확인한다.

핵심 질문:
- ❌ "Gemini가 자연스럽게 말했는가?"
- ✅ **"Gemini의 말이 원본 데이터로 확인 가능한가?"**

검증 대상:
- STEP 09에서 응답을 받은 **에스코어 / AX 컨설턴트 채용** 1건
- GS리테일은 STEP 09에서 서버 과부하(503)로 응답을 받지 못했으므로 검증 대상에서 제외한다. (검증 실패로 보지 않음)
- Gemini 응답은 새로 만들지 않고, STEP 09 셀에 저장된 응답 원문을 그대로 사용한다.

원본 데이터:
- `data/processed/jobs_history.csv`의 에스코어 행 (**읽기만** 한다)
- 확인할 필드: `company_name`, `job_title`, `career`, `location`, `posted_date`, `closing_date`, `search_keyword`, `job_url`

판정 기준:

| 판정 | 뜻 |
|---|---|
| 일치 | 원본 값과 Gemini 값이 글자 그대로 같다 |
| 의미상 일치 | 글자는 다르지만 뜻이 원본에서 벗어나지 않는다 (사람이 판단) |
| 검증 불가 | 원본 데이터에 해당 정보가 없어서 맞는지 틀린지 확인할 수 없다 |
| 불일치 | 원본과 다르다 |

- "일치"는 코드가 글자를 자동으로 비교해 판정한다.
- 글자가 다른 항목은 복잡한 자동 판정을 만들지 않고, **사람이 읽고 판단한 판정과 그 이유**를 표에 함께 적는다.

검증 불가 항목:
- 상세 업무, 세부 기술 스택, 자격요건, 우대사항은 상세 페이지를 수집하지 않아 원본에 없다.
  → Gemini가 이 항목들을 "확인 불가"라고 적었는지만 확인한다.

이번 단계에서 하지 않는 것:
- Gemini API 호출, STEP 09 재실행, GS리테일 재시도
- 웹 요청, 상세 페이지 요청
- 보고서 생성 (STEP 11)

완료 조건:
- 원본 CSV와 Gemini 응답을 항목별로 비교했다
- 일치 / 의미상 일치 / 검증 불가 / 불일치를 구분했다
- 과도한 해석과 환각(원본에 없는 사실을 지어낸 것) 의심 내용을 확인했다
- 사람이 표를 보고 최종 결과를 검토할 수 있다

In [1]:
from pathlib import Path
import pandas as pd

# ----- 1) 원본 데이터 읽기 (history CSV는 읽기만 한다) -----
current_dir = Path.cwd()
project_root = current_dir.parent if current_dir.name == "notebooks" else current_dir
history_path = project_root / "data" / "processed" / "jobs_history.csv"
history_df = pd.read_csv(history_path)

source_job = history_df[history_df["company_name"] == "에스코어"].iloc[0]
print("검증할 공고:", source_job["company_name"], "/", source_job["job_title"])
print("원본 job_url:", source_job["job_url"])

# ----- 2) 검증할 Gemini 응답 (STEP 09 셀 출력에 저장된 원문에서 옮겨 적은 값) -----
# API를 다시 호출하지 않는다
NO_SOURCE = "(원본 데이터에 없음)"

validation_items = [
    # --- 원본 필드와 직접 비교하는 항목: 글자가 같으면 코드가 "일치"로 판정 ---
    {"item": "회사명", "source": source_job["company_name"], "gemini": "에스코어"},
    {"item": "공고 제목", "source": source_job["job_title"], "gemini": "AX 컨설턴트 채용"},
    {"item": "경력 ([확인 가능한 정보])", "source": source_job["career"], "gemini": "경력"},
    {"item": "지역", "source": source_job["location"], "gemini": "서울 송파구"},
    {"item": "지원 시작일", "source": source_job["posted_date"], "gemini": "2026-07-01"},
    {"item": "지원 마감일", "source": source_job["closing_date"], "gemini": "2026-09-30 23:00"},
    {"item": "검색어", "source": source_job["search_keyword"], "gemini": "ax"},

    # --- 글자가 달라서 사람이 판단한 항목: manual_verdict와 reason을 직접 적는다 ---
    {"item": "경력 ([한줄 요약])", "source": source_job["career"], "gemini": "경력직",
     "manual_verdict": "의미상 일치", "reason": "원본 '경력'을 '경력직'으로 표현 — 뜻이 벗어나지 않음"},
    {"item": "한줄 요약", "source": "회사·제목·지역·경력 필드",
     "gemini": "에스코어에서 서울 송파구 근무 조건으로 경력직 AX 컨설턴트를 채용합니다.",
     "manual_verdict": "의미상 일치", "reason": "회사명·지역·경력·제목만 조합, 새 사실 없음"},
    {"item": "AX/AI 관련성", "source": source_job["job_title"], "gemini": "AX 관련 컨설팅 직무",
     "manual_verdict": "의미상 일치", "reason": "제목 'AX 컨설턴트'에 근거한 합리적 요약 (실제 컨설팅 분야는 알 수 없음)"},
    {"item": "AX 약어 풀이", "source": NO_SOURCE, "gemini": "AX(AI Transformation)",
     "manual_verdict": "검증 불가", "reason": "원본에 약어 뜻이 없음 — Gemini가 일반 지식으로 덧붙인 해석"},

    # --- 원본에 없는 정보: Gemini가 '확인 불가'로 적었는지 확인 ---
    {"item": "상세 업무", "source": NO_SOURCE, "gemini": "확인 불가",
     "manual_verdict": "검증 불가", "reason": "상세 페이지 미수집 — Gemini가 추측하지 않고 '확인 불가' 처리"},
    {"item": "상세 기술 스택", "source": NO_SOURCE, "gemini": "확인 불가",
     "manual_verdict": "검증 불가", "reason": "상세 페이지 미수집 — Gemini가 추측하지 않고 '확인 불가' 처리"},
    {"item": "자격요건", "source": NO_SOURCE, "gemini": "확인 불가",
     "manual_verdict": "검증 불가", "reason": "상세 페이지 미수집 — Gemini가 추측하지 않고 '확인 불가' 처리"},
    {"item": "우대사항", "source": NO_SOURCE, "gemini": "확인 불가",
     "manual_verdict": "검증 불가", "reason": "상세 페이지 미수집 — Gemini가 추측하지 않고 '확인 불가' 처리"},
]

# ----- 3) 판정 -----
# 글자가 완전히 같으면 "일치", 아니면 사람이 적어 둔 판정(manual_verdict)을 사용
# 사람이 판정을 적지 않았는데 글자가 다르면 "불일치"
rows = []
for v in validation_items:
    if str(v["source"]) == str(v["gemini"]):
        verdict, reason = "일치", "원본과 글자 그대로 같음 (자동 비교)"
    else:
        verdict = v.get("manual_verdict", "불일치")
        reason = v.get("reason", "원본과 다름")
    rows.append({"검증 항목": v["item"], "원본": v["source"], "Gemini": v["gemini"],
                 "판정": verdict, "판정 이유": reason})

validation_df = pd.DataFrame(rows)

# ----- 4) 결과 출력 -----
pd.set_option("display.max_colwidth", 60)
display(validation_df)

print("\n=== 판정별 개수 ===")
print("검증 항목 수:", len(validation_df))
print(validation_df["판정"].value_counts())
print("\n불일치 항목:", validation_df.loc[validation_df["판정"] == "불일치", "검증 항목"].tolist() or "없음")

검증할 공고: 에스코어 / AX 컨설턴트 채용
원본 job_url: https://www.jobkorea.co.kr/Recruit/GI_Read/49589368

,검증 항목,원본,Gemini,판정,판정 이유
0,회사명,에스코어,에스코어,일치,원본과 글자 그대로 같음 (자동 비교)
1,공고 제목,AX 컨설턴트 채용,AX 컨설턴트 채용,일치,원본과 글자 그대로 같음 (자동 비교)
2,경력 ([확인 가능한 정보]),경력,경력,일치,원본과 글자 그대로 같음 (자동 비교)
3,지역,서울 송파구,서울 송파구,일치,원본과 글자 그대로 같음 (자동 비교)
4,지원 시작일,2026-07-01,2026-07-01,일치,원본과 글자 그대로 같음 (자동 비교)
5,지원 마감일,2026-09-30 23:00,2026-09-30 23:00,일치,원본과 글자 그대로 같음 (자동 비교)
6,검색어,ax,ax,일치,원본과 글자 그대로 같음 (자동 비교)
7,경력 ([한줄 요약]),경력,경력직,의미상 일치,원본 '경력'을 '경력직'으로 표현 — 뜻이 벗어나지 않음
8,한줄 요약,회사·제목·지역·경력 필드,에스코어에서 서울 송파구 근무 조건으로 경력직 AX 컨설턴트를 채용합니다.,의미상 일치,"회사명·지역·경력·제목만 조합, 새 사실 없음"
9,AX/AI 관련성,AX 컨설턴트 채용,AX 관련 컨설팅 직무,의미상 일치,제목 'AX 컨설턴트'에 근거한 합리적 요약 (실제 컨설팅 분야는 알 수 없음)
10,AX 약어 풀이,(원본 데이터에 없음),AX(AI Transformation),검증 불가,원본에 약어 뜻이 없음 — Gemini가 일반 지식으로 덧붙인 해석
11,상세 업무,(원본 데이터에 없음),확인 불가,검증 불가,상세 페이지 미수집 — Gemini가 추측하지 않고 '확인 불가' 처리
12,상세 기술 스택,(원본 데이터에 없음),확인 불가,검증 불가,상세 페이지 미수집 — Gemini가 추측하지 않고 '확인 불가' 처리
13,자격요건,(원본 데이터에 없음),확인 불가,검증 불가,상세 페이지 미수집 — Gemini가 추측하지 않고 '확인 불가' 처리
14,우대사항,(원본 데이터에 없음),확인 불가,검증 불가,상세 페이지 미수집 — Gemini가 추측하지 않고 '확인 불가' 처리

=== 판정별 개수 ===
검증 항목 수: 15
판정
일치        7
검증 불가     5
의미상 일치    3
Name: count, dtype: int64

불일치 항목: 없음

## 실행 결과 해석 / 분석 / 요약

- 셀이 에러 없이 실행되었다. (Gemini API 호출 없음, 웹 요청 없음, history CSV는 읽기만 함)
- 검증한 공고: **에스코어 / AX 컨설턴트 채용** (`.../GI_Read/49589368`) — STEP 09에서 응답을 받은 1건
  - GS리테일은 STEP 09에서 503(서버 과부하)으로 응답이 없어 검증 대상에서 제외했다. (검증 실패가 아님)
- 검증한 항목 수: **15개**

| 판정 | 개수 | 항목 |
|---|---:|---|
| 일치 | 7 | 회사명, 공고 제목, 경력([확인 가능한 정보]), 지역, 지원 시작일, 지원 마감일, 검색어 |
| 의미상 일치 | 3 | 경력([한줄 요약] "경력직"), 한줄 요약, AX/AI 관련성 |
| 검증 불가 | 5 | AX 약어 풀이, 상세 업무, 상세 기술 스택, 자격요건, 우대사항 |
| 불일치 | 0 | 없음 |

- 원본에 없는 사실을 Gemini가 추가했는지:
  - 채용 조건(회사·제목·경력·지역·날짜·검색어)에 대해서는 **새로 지어낸 사실이 없다.** 한줄 요약도 원본 필드만 조합했다.
  - 다만 [AX/AI 관련성]에서 `AX(AI Transformation)`처럼 **약어 뜻을 덧붙였다.** 이 뜻은 원본 데이터에 없으므로 "검증 불가"로 분류했다.
    (일반적으로 쓰이는 약어 풀이지만, 이 공고에서 AX를 그 뜻으로 쓰는지는 원본으로 확인할 수 없다)
- AX/AI 관련성 설명이 원본 범위를 넘었는지:
  - "AX 관련 컨설팅 직무"라는 설명은 **제목 'AX 컨설턴트'에 근거한 합리적 요약** 수준이다.
  - 실제 컨설팅 분야, 기술 스택, AI 프로젝트 내용은 원본에 없어 검증할 수 없다. Gemini도 그런 내용을 덧붙이지는 않았다.
  - 약어 풀이(`AI Transformation`)만 원본 범위를 살짝 넘는 해석이다.
- "확인 불가" 처리가 적절했는지:
  - 상세 업무 / 상세 기술 스택 / 자격요건 / 우대사항 4개를 모두 "확인 불가"로 적었다.
  - 상세 페이지를 수집하지 않은 현재 데이터 범위를 **지킨 처리**이다.
- 환각으로 의심되는 내용:
  - 원본과 **다른 사실(불일치)은 없다.**
  - 원본 밖의 내용은 약어 풀이 1건뿐이며, 이는 틀린 사실이라기보다 "원본으로 확인할 수 없는 해석"으로 기록한다.
- 참고: 원본의 `job_url`은 Gemini 응답 형식에 포함되지 않아 비교 항목에서 뺐다.

제한 사항:
- 이 결과는 **이번 검증한 에스코어 1건에서의 결과**이다. 1건만으로 Gemini가 항상 정확하다고 결론 내릴 수 없다.
- "의미상 일치"와 "검증 불가" 판정은 코드가 자동으로 한 것이 아니라 **사람이 읽고 판단한 결과**이다. 표의 "판정 이유"를 보고 최종 검토한다.
- 이번에는 제목만 있는 정보로 검증했으므로, 상세 페이지 내용을 넣는 경우에는 별도 검증이 필요하다.

STEP 10 완료 여부:
- 원본 CSV와 Gemini 응답 비교 → 완료
- 사실 일치 여부 확인 → 완료 (불일치 0)
- 확인 불가 항목 구분 → 완료
- 과도한 해석 여부 확인 → 완료 (약어 풀이 1건을 "검증 불가"로 기록)
- 환각 의심 내용 확인 → 완료 (원본과 다른 사실 없음)
- 사람이 최종 결과 검토 가능 → 표로 출력
- → **STEP 10 완료 조건 충족.** 다음 공식 STEP은 STEP 11 Markdown 보고서 생성이다.

# STEP 11. Markdown 보고서 생성

## 작업 계획

지금까지 검증한 결과를 **사람이 읽기 쉬운 Markdown 보고서 1개**로 모은다.
새 데이터를 수집하거나 Gemini를 다시 부르지 않고, 이미 확인된 데이터와 결과만 사용한다.

생성할 파일:
- `reports/ax_job_report.md` (프로젝트 루트 기준, `reports/` 폴더가 없으면 만든다)

사용할 근거:
- 공고 데이터: `data/processed/jobs_history.csv` (**읽기만** 한다)
  - 회사별·지역별·경력별 공고 수, 날짜 범위, 필터 결과는 이 CSV로 **다시 계산**한다.
  - 이전 STEP에서 본 숫자를 그대로 적어 넣지 않고, 현재 CSV의 실제 값을 쓴다.
- Gemini 설명: STEP 09에서 응답을 받은 **에스코어 1건**의 응답 원문 (STEP 09 셀 출력에서 옮겨 적음)
- 검증 결과: STEP 10의 판정 결과 (15개 항목)

가장 중요한 원칙 — **사실과 AI 설명을 구분한다**:
- **[데이터 기반 사실]**: pandas로 계산한 숫자와 원본 값 (공고 수, 회사별 수, 날짜 범위 등)
- **[Gemini 생성 설명]**: Gemini가 만든 문장 (요약, AX 관련성 설명)
- 보고서에서 두 가지가 섞여 사실처럼 보이지 않도록, 구역마다 이름표를 붙이고 Gemini 내용은 인용(`>`) 블록으로 따로 표시한다.

보고서 구조:
1. 분석 기준 / 2. 현재 수집 데이터 요약 / 3. AX/AI 관련 공고 필터 결과 / 4. 주요 공고
5. Gemini 분석 예시 / 6. Gemini 검증 결과 / 7. 제한 사항 / 8. 다음 단계

문체 원칙:
- 현재 데이터는 5건뿐이므로 "시장 전체", "대부분의 기업"처럼 일반화하지 않는다.
- "현재 수집된 5건 기준으로", "이번 샘플에서는"처럼 범위를 제한해서 쓴다.

이번 단계에서 하지 않는 것:
- 웹 요청, Gemini API 호출, STEP 09/10 재실행
- Slack / Gmail 발송 (STEP 12 이후)

완료 조건:
- `reports/ax_job_report.md`가 생성된다
- 실데이터 요약, 주요 공고, Gemini 분석 예시, STEP 10 검증 결과, 제한 사항이 모두 들어 있다
- pandas 사실과 Gemini 설명이 구분되어 있다
- 파일을 사람이 직접 열어 읽을 수 있다

In [1]:
from pathlib import Path
import re
import pandas as pd

# ----- 1) 기존 데이터 읽기 (history CSV는 읽기만 한다) -----
current_dir = Path.cwd()
project_root = current_dir.parent if current_dir.name == "notebooks" else current_dir
history_path = project_root / "data" / "processed" / "jobs_history.csv"
jobs_df = pd.read_csv(history_path)
print("읽은 공고 수:", len(jobs_df))

# ----- 2) pandas 집계 (현재 CSV 실제 값 기준) -----
total_jobs = len(jobs_df)
company_counts = jobs_df["company_name"].value_counts()
location_counts = jobs_df["location"].value_counts()
career_counts = jobs_df["career"].value_counts()
keyword_counts = jobs_df["search_keyword"].value_counts()


# 날짜 범위: 비교는 날짜 타입으로 하고, 보고서에는 원본 문자열을 그대로 적는다
def date_range(column):
    parsed = pd.to_datetime(jobs_df[column], errors="coerce")
    return jobs_df.loc[parsed.idxmin(), column], jobs_df.loc[parsed.idxmax(), column]


posted_min, posted_max = date_range("posted_date")
closing_min, closing_max = date_range("closing_date")

# AX/AI 1차 필터 결과 다시 계산 (STEP 07-G 개선 규칙과 같은 방식)
relevance_keywords = ["AX", "AI", "인공지능", "생성형 AI", "생성형AI", "LLM", "Machine Learning", "머신러닝",
                      "Data Scientist", "데이터 사이언티스트", "AI Engineer", "AI 엔지니어", "데이터 분석"]


def find_matched_keywords_for_report(title):
    matched = []
    for keyword in relevance_keywords:
        if re.fullmatch(r"[A-Za-z0-9 ]+", keyword):  # 영문 키워드: 앞뒤에 영문자·숫자가 없을 때만
            if re.search(r"(?<![A-Za-z0-9])" + re.escape(keyword) + r"(?![A-Za-z0-9])", title, re.IGNORECASE):
                matched.append(keyword)
        elif keyword.lower() in title.lower():       # 한글 키워드: 포함 검색
            matched.append(keyword)
    return matched


matched_series = jobs_df["job_title"].apply(find_matched_keywords_for_report)
filter_pass_count = (matched_series.apply(len) > 0).sum()
matched_keyword_counts = matched_series.explode().value_counts()


# ----- 3) Markdown 조각 만드는 도우미 함수 -----
def counts_to_lines(counts):
    # value_counts 결과를 "- 값: N건" 목록으로 바꾼다
    return "\n".join(f"- {name}: {count}건" for name, count in counts.items())


def md_cell(value):
    # 표 안에서 '|' 문자가 칸을 깨뜨리지 않도록 바꾼다
    return str(value).replace("|", "/")


job_table_lines = ["| 회사명 | 공고 제목 | 경력 | 지역 | 지원 시작일 | 지원 마감일 | 공고 URL |",
                   "|---|---|---|---|---|---|---|"]
for _, job in jobs_df.iterrows():
    job_table_lines.append(
        f"| {md_cell(job['company_name'])} | {md_cell(job['job_title'])} | {md_cell(job['career'])} "
        f"| {md_cell(job['location'])} | {job['posted_date']} | {job['closing_date']} | [링크]({job['job_url']}) |"
    )
job_table = "\n".join(job_table_lines)

# ----- 4) Gemini 설명 (STEP 09 셀 출력에 저장된 에스코어 응답 원문 — API 재호출 없음) -----
gemini_escore = {
    "company_name": "에스코어",
    "job_title": "AX 컨설턴트 채용",
    "summary": "에스코어에서 서울 송파구 근무 조건으로 경력직 AX 컨설턴트를 채용합니다.",
    "confirmed": ["경력: 경력", "지역: 서울 송파구", "지원 시작일: 2026-07-01",
                  "지원 마감일: 2026-09-30 23:00", "검색어: ax"],
    "ax_relevance": "공고 제목에 'AX 컨설턴트'가 명시되어 있어 AX(AI Transformation) 관련 컨설팅 직무임을 확인할 수 있습니다.",
    "unknown": ["상세 업무: 확인 불가", "상세 기술 스택: 확인 불가", "자격요건: 확인 불가", "우대사항: 확인 불가"],
}

# STEP 10 검증 결과 (STEP 10 셀 출력 기준)
validation_summary = {"검증 항목": 15, "일치": 7, "의미상 일치": 3, "불일치": 0, "검증 불가": 5}


def quote_lines(lines):
    # Gemini 내용은 인용(>) 블록으로 표시해서 데이터 기반 사실과 구분한다
    return "\n".join(f"> - {line}" for line in lines)


# ----- 5) 보고서 Markdown 만들기 -----
report_md = f"""# AX 채용 분석 보고서

> 이 보고서는 **현재 수집된 {total_jobs}건 기준**입니다. 채용 시장 전체의 경향을 나타내지 않습니다.
>
> - **[데이터 기반 사실]** 표시: 수집 데이터를 pandas로 계산한 값
> - **[Gemini 생성 설명]** 표시: Gemini가 만든 문장 (STEP 10에서 원본과 비교 검증)
> - **[STEP 10 검증 결과]** 표시: Gemini 응답을 원본과 비교한 판정 (일부 판정은 사람이 판단)

## 1. 분석 기준

**[데이터 기반 사실]**

- 검색어: {", ".join(keyword_counts.index)}
- 분석 대상 공고 수: {total_jobs}건
- 수집 기준: JobKorea 검색 결과 1페이지의 상위 {total_jobs}건 (검색 결과 페이지에 보이는 정보만 사용, 상세 페이지 미수집)
- 데이터 파일: `data/processed/jobs_history.csv`
- 지원 시작일 범위: {posted_min} ~ {posted_max}
- 지원 마감일 범위: {closing_min} ~ {closing_max}

## 2. 현재 수집 데이터 요약

**[데이터 기반 사실]** — 현재 수집된 {total_jobs}건 기준

전체 공고 수: {total_jobs}건

회사별 공고 수:

{counts_to_lines(company_counts)}

지역별 공고 수:

{counts_to_lines(location_counts)}

경력별 공고 수:

{counts_to_lines(career_counts)}

- 경력 값은 화면 문구 그대로라 `경력`, `경력3년↑` 등이 따로 집계되었습니다.
- `서울 강남구 외 1`처럼 근무지가 여러 곳인 공고는 요약 문구 그대로 집계했습니다.

## 3. AX/AI 관련 공고 필터 결과

**[데이터 기반 사실]**

- 필터 통과 공고 수: {filter_pass_count}건 / 전체 {total_jobs}건
- 사용한 기준: 공고 제목(`job_title`)에 AX/AI 관련 키워드 {len(relevance_keywords)}개 중 하나 이상 포함
  - 영문 키워드는 앞뒤에 영문자·숫자가 없을 때만 매칭, 한글 키워드는 포함 검색
- 매칭된 키워드: {", ".join(f"{k} {v}건" for k, v in matched_keyword_counts.items())}
- 오탐 개선 테스트: 12개 중 12개 통과 (Tax / Max / Maintenance / Training 오탐 해결)

이 필터는 **1차 후보 선별용**입니다. 제목에 키워드가 있다고 원하는 AX 직무라는 뜻은 아니며,
이번 샘플은 검색어가 `ax`라서 모든 공고가 통과했습니다.

## 4. 주요 공고

**[데이터 기반 사실]** — 현재 수집된 {total_jobs}건 전체

{job_table}

- 지원 시작일 = `applicationPeriod.start`, 지원 마감일 = `applicationPeriod.end` (원본 값 그대로)

## 5. Gemini 분석 예시

**[Gemini 생성 설명]**

아래 내용은 Gemini가 생성한 설명이며,
STEP 10에서 원본 데이터와 비교 검증했습니다.

대상: {gemini_escore["company_name"]} / {gemini_escore["job_title"]} (모델: gemini-3.6-flash)

> **한줄 요약**
>
> {gemini_escore["summary"]}
>
> **확인 가능한 정보**
>
{quote_lines(gemini_escore["confirmed"])}
>
> **AX/AI 관련성**
>
> {gemini_escore["ax_relevance"]}
>
> **확인 불가**
>
{quote_lines(gemini_escore["unknown"])}

## 6. Gemini 검증 결과

**[STEP 10 검증 결과]** — 에스코어 1건의 Gemini 응답을 원본 CSV와 비교한 결과
("일치"는 글자 비교, "의미상 일치"·"검증 불가"는 사람이 판단)

| 구분 | 개수 |
|---|---:|
{chr(10).join(f"| {k} | {v} |" for k, v in validation_summary.items())}

- 원본과 다른 사실(불일치)은 발견되지 않았습니다.
- AX 약어 풀이(`AI Transformation`) → 원본으로 확인할 수 없어 **검증 불가**
- 상세 업무 / 기술 스택 / 자격요건 / 우대사항 → 상세 페이지 데이터가 없으므로 **검증 불가** (Gemini도 "확인 불가"로 처리)

## 7. 제한 사항

- 현재 데이터는 {total_jobs}건뿐입니다.
- 검색어는 `ax` 1개뿐입니다.
- 검색 결과 한 페이지의 일부 공고만 사용했습니다.
- 공고 상세 페이지 본문은 아직 수집하지 않았습니다.
- Gemini 검증은 에스코어 1건 기준입니다.
- GS리테일 공고의 Gemini 호출은 503(서버 과부하)으로 응답을 받지 못했습니다.
- 현재 결과를 전체 채용시장 경향으로 일반화하면 안 됩니다.

## 8. 다음 단계

- 다음 공식 STEP: **STEP 12 — Slack 발송** (아직 구현하지 않음)
"""

# ----- 6) reports 폴더 만들고 저장 -----
reports_dir = project_root / "reports"
reports_dir.mkdir(parents=True, exist_ok=True)
report_path = reports_dir / "ax_job_report.md"
report_path.write_text(report_md, encoding="utf-8")

# ----- 7) 저장 결과 확인 -----
print("보고서 생성 경로:", report_path)
print("보고서 문자 수:", len(report_md))
print("파일 존재 여부:", report_path.exists())
print("\n=== 보고서 앞부분 ===")
print(report_md[:1500])

읽은 공고 수: 5
보고서 생성 경로: C:\dev\claude-code-agent-course\chapter11\ax-job-agent\reports\ax_job_report.md
보고서 문자 수: 3331
파일 존재 여부: True

=== 보고서 앞부분 ===
# AX 채용 분석 보고서

> 이 보고서는 **현재 수집된 5건 기준**입니다. 채용 시장 전체의 경향을 나타내지 않습니다.
>
> - **[데이터 기반 사실]** 표시: 수집 데이터를 pandas로 계산한 값
> - **[Gemini 생성 설명]** 표시: Gemini가 만든 문장 (STEP 10에서 원본과 비교 검증)
> - **[STEP 10 검증 결과]** 표시: Gemini 응답을 원본과 비교한 판정 (일부 판정은 사람이 판단)

## 1. 분석 기준

**[데이터 기반 사실]**

- 검색어: ax
- 분석 대상 공고 수: 5건
- 수집 기준: JobKorea 검색 결과 1페이지의 상위 5건 (검색 결과 페이지에 보이는 정보만 사용, 상세 페이지 미수집)
- 데이터 파일: `data/processed/jobs_history.csv`
- 지원 시작일 범위: 2026-07-01 ~ 2026-09-21
- 지원 마감일 범위: 2026-09-29 10:00 ~ 2026-10-25 23:00

## 2. 현재 수집 데이터 요약

**[데이터 기반 사실]** — 현재 수집된 5건 기준

전체 공고 수: 5건

회사별 공고 수:

- ㈜NAVER: 2건
- GS리테일: 1건
- 에스코어: 1건
- ㈜슈프리마: 1건

지역별 공고 수:

- 경기 성남시: 3건
- 서울 강남구 외 1: 1건
- 서울 송파구: 1건

경력별 공고 수:

- 경력: 3건
- 경력3년↑: 1건
- 경력7년↑: 1건

- 경력 값은 화면 문구 그대로라 `경력`, `경력3년↑` 등이 따로 집계되었습니다.
- `서울 강남구 외 1`처럼 근무지가 여러 곳인 공고는 요약 문구 그대로 집계했습니다.

## 3. AX/AI 관련 공고 필터 결과

**[데이터 기반 사실]**

- 필터 통과 공고 수: 5건 / 전체 5건
- 사용한 기준: 공고 제목(`job_title`)에 AX/AI 관련 키워드 13개 중 하나 이상 포함
  - 영문 키워드는 앞뒤에 영문자·숫자가 없을 때만 매칭, 한글 키워드는 포함 검색
- 매칭된 키워드: AX 5건
- 오탐 개선 테스트: 12개 중 12개 통과 (Tax / Max / Maintenance / Training 오탐 해결)

이 필터는 **1차 후보 선별용**입니다. 제목에 키워드가 있다고 원하는 AX 직무라는 뜻은 아니며,
이번 샘플은 검색어가 `ax`라서 모든 공고가 통과했습니다.

## 4. 주요 공고

**[데이터 기반 사실]** — 현재 수집된 5건 전체

| 회사명 | 공고 제목 | 경력 | 지역 | 지원 시작일 | 지원 마감일 | 공고 URL |
|---|---|---|---|---|---|---|
| GS리테일 | [GS리테일] 9·10월 통합공고(BIZ CLUB팀 경력사원, MD AX 담당, 물류 AX 담당, 보안성 검토 담당) | 경력3년↑ | 서울 강남구 외 1 | 2026-09-21 | 2026-10-01 23:00 | [링크](https://www.jobkorea.co.kr/Recruit/GI_Read/50032017

## 실행 결과 해석 / 분석 / 요약

- 셀이 에러 없이 실행되었다. (웹 요청 없음, Gemini API 호출 없음, history CSV는 읽기만 함)
- 보고서 생성 여부: **생성됨**
- 생성 파일 경로: `reports/ax_job_report.md` (`reports/` 폴더는 이번에 새로 만들어짐)
- 보고서 문자 수: **3331자**
- 분석 대상 공고 수: **5건** (`jobs_history.csv` 기준)
- pandas 사실 포함 여부: **포함** — 전체 공고 수, 회사별·지역별·경력별·검색어별 공고 수, 지원 시작일·마감일 범위, 필터 통과 수를 현재 CSV로 다시 계산해 넣었다.
  - 다시 계산한 값이 이전 STEP(07-E, 07-F)에서 확인한 값과 같았다. (회사별 NAVER 2 등, 시작일 2026-07-01 ~ 2026-09-21, 마감일 2026-09-29 10:00 ~ 2026-10-25 23:00, 필터 5/5)
- Gemini 설명 포함 여부: **포함** — 5장에 에스코어 응답(한줄 요약, 확인 가능한 정보, AX 관련성, 확인 불가)을 넣었다. STEP 09 셀에 저장된 원문을 그대로 옮겼다.
- Gemini 검증 결과 포함 여부: **포함** — 6장에 STEP 10 결과(15개 중 일치 7, 의미상 일치 3, 불일치 0, 검증 불가 5)와 검증 불가 사유를 넣었다.
- 제한 사항 포함 여부: **포함** — 7장에 7개 항목 (5건, 검색어 1개, 1페이지 일부, 상세 페이지 미수집, Gemini 검증 1건, GS리테일 503, 일반화 금지)
- 사실과 AI 설명 구분 여부: **구분함**
  - 각 장 첫 줄에 이름표를 붙였다: **[데이터 기반 사실]** / **[Gemini 생성 설명]** / **[STEP 10 검증 결과]**
  - Gemini 문장은 인용(`>`) 블록 안에만 넣고, "아래 내용은 Gemini가 생성한 설명이며, STEP 10에서 원본 데이터와 비교 검증했습니다." 문구를 붙였다.
  - STEP 10 판정 중 "의미상 일치"·"검증 불가"는 사람이 판단한 것이라, pandas 사실과 다른 이름표를 붙였다.
- 문체: "시장 전체", "대부분의 기업" 같은 일반화 표현은 쓰지 않고 "현재 수집된 5건 기준"으로 제한했다.
- STEP 11 완료 조건 충족 여부: **충족** — 파일 생성, 실데이터 요약, 주요 공고 5건 표, Gemini 분석 예시, STEP 10 검증 결과, 제한 사항, 사실/AI 설명 구분이 모두 들어 있다.
  사용자가 `reports/ax_job_report.md`를 직접 열어 읽어 보고 최종 확인한다.

참고:
- 이 셀을 다시 실행하면 보고서 파일을 같은 이름으로 덮어써서 다시 만든다.
- Gemini 응답과 STEP 10 판정 개수는 이전 셀 출력에서 옮겨 적은 값이다. (메모리 변수가 없어도 실행되도록 하기 위함)

# STEP 12. Slack 발송

## 작업 계획

STEP 11에서 만든 보고서 `reports/ax_job_report.md`를 **Slack 채널로 1번 보내서**, 실제로 도착하는지 확인한다.

Slack Incoming Webhook이란:
- Slack이 채널마다 만들어 주는 **전송용 주소(URL)**이다.
- 이 주소로 메시지를 보내면(`requests.post`) 해당 채널에 글이 올라간다.
- 이 URL을 아는 사람은 누구나 그 채널에 글을 쓸 수 있으므로 **API 키처럼 비밀값**으로 다룬다.
  → `.env`의 `SLACK_WEBHOOK_URL`에 저장하고, 화면에는 "설정됨 / 미설정"만 출력한다.

이번 단계에서 할 일:
1. `.env`에서 Slack Webhook URL 설정 여부 확인 (미설정이면 요청하지 않고 멈춘다)
2. `reports/ax_job_report.md` 읽기 (파일은 수정하지 않는다)
3. Slack으로 보낼 메시지 만들기
   - 단순한 `{"text": 메시지}` 형태만 사용한다. (복잡한 Slack Block Kit은 쓰지 않음)
   - Slack은 일반 Markdown 링크 `[링크](URL)`를 링크로 보여 주지 않을 수 있어서,
     **링크 부분만** Slack 형식 `<URL|링크>`로 바꾼다. (다른 Markdown 문법은 바꾸지 않음)
4. Webhook 요청 **1회** 전송 (자동 재시도 없음)
5. HTTP 응답(상태 코드, 응답 본문) 확인
6. 실제 Slack 채널에 도착했는지 **사람이 직접 확인**

이번 단계에서 하지 않는 것:
- Gmail
- Gemini 호출
- 웹 크롤링
- 보고서 다시 생성
- main.py
- GitHub Actions

완료 기준:
- Webhook 호출 성공 (HTTP 응답 확인)
- 실제 Slack 메시지 도착
- 한글 정상 표시
- 공고 링크 클릭 확인
- 비밀값(Webhook URL) 미노출

주의:
- 코드에서 HTTP 200이 나와도 자동으로 완료 처리하지 않는다. 최종 확인은 사람이 Slack 채널에서 한다.
- 이 셀을 실행할 때마다 Slack에 메시지가 1번 올라간다.

In [1]:
from pathlib import Path
import os
import re
import requests
from dotenv import load_dotenv

# ----- 1) 프로젝트 루트의 .env 로드 -----
current_dir = Path.cwd()
project_root = current_dir.parent if current_dir.name == "notebooks" else current_dir
env_path = project_root / ".env"
if env_path.exists():
    load_dotenv(env_path)

# Webhook URL은 설정 여부만 출력한다 (값은 절대 출력하지 않음)
slack_webhook_url = os.getenv("SLACK_WEBHOOK_URL")
print("SLACK_WEBHOOK_URL 설정 여부:", "설정됨" if slack_webhook_url else "미설정")

# ----- 2) 보고서 읽기 (파일은 수정하지 않는다) -----
report_path = project_root / "reports" / "ax_job_report.md"
if not report_path.exists():
    raise FileNotFoundError("reports/ax_job_report.md가 없습니다. STEP 11을 먼저 실행하세요.")

report_text = report_path.read_text(encoding="utf-8")
print("보고서 파일:", report_path.relative_to(project_root))
print("보고서 문자 수:", len(report_text))


# ----- 3) Markdown 링크만 Slack 링크 형식으로 바꾸기 -----
# [표시문구](https://...)  →  <https://...|표시문구>
def convert_markdown_links_to_slack(text):
    pattern = r"\[([^\]]+)\]\((https?://[^\)]+)\)"
    return re.sub(pattern, r"<\2|\1>", text)


slack_report_text = convert_markdown_links_to_slack(report_text)
print("Slack 링크로 바꾼 개수:", len(re.findall(r"<https?://[^|>]+\|[^>]+>", slack_report_text)))

slack_message = f"""*AX 채용 분석 보고서*

STEP 11에서 생성한 Markdown 보고서입니다.

{slack_report_text}
"""
print("Slack 메시지 문자 수:", len(slack_message))

# ----- 4) Slack 요청 (Webhook URL이 있을 때만, 1회만) -----
slack_request_count = 0

if not slack_webhook_url:
    print("\nSLACK_WEBHOOK_URL이 설정되지 않아 Slack 요청을 보내지 않습니다.")
    print("프로젝트 루트의 .env 파일에 SLACK_WEBHOOK_URL=본인의_Webhook_URL 을 입력한 뒤 다시 실행하세요.")
else:
    try:
        slack_request_count += 1
        response = requests.post(slack_webhook_url, json={"text": slack_message}, timeout=10)
        print("\nSlack HTTP 상태 코드:", response.status_code)
        print("Slack 응답 본문:", response.text)
    except Exception as e:
        # 오류 메시지 안에 Webhook URL이 들어 있으면 *** 로 가린다
        safe_message = str(e).replace(slack_webhook_url, "***")
        print("\nSlack 요청 실패")
        print("오류 종류:", type(e).__name__)
        print("오류 메시지:", safe_message[:300])

print("\nSlack 요청 횟수:", slack_request_count)

SLACK_WEBHOOK_URL 설정 여부: 미설정
보고서 파일: reports\ax_job_report.md
보고서 문자 수: 3331
Slack 링크로 바꾼 개수: 5
Slack 메시지 문자 수: 3375

SLACK_WEBHOOK_URL이 설정되지 않아 Slack 요청을 보내지 않습니다.
프로젝트 루트의 .env 파일에 SLACK_WEBHOOK_URL=본인의_Webhook_URL 을 입력한 뒤 다시 실행하세요.

Slack 요청 횟수: 0

## 실행 결과 해석 / 분석 / 요약

- 셀이 에러 없이 실행되었다.
- SLACK_WEBHOOK_URL 설정 여부: **미설정** — `.env`에 `SLACK_WEBHOOK_URL=` 줄은 있지만 값이 비어 있다.
- 보고서 파일 읽기 성공 여부: **성공** — `reports/ax_job_report.md` (파일은 수정하지 않음)
- 보고서 문자 수: **3331자** (Slack 메시지로 만들면 제목 포함 3375자)
- Markdown 링크 변환: 공고 링크 **5개**를 `[링크](URL)` → `<URL|링크>` 형식으로 바꿨다.
- Slack 요청 횟수: **0회** — Webhook URL이 없어서 요청을 보내지 않고 멈췄다.
- HTTP 상태 코드: 없음 (요청하지 않음)
- Slack 응답: 없음 (요청하지 않음)
- API/Webhook 비밀값 노출 여부: **노출 없음** — "미설정"만 출력했다.
- 실제 Slack 채널 도착 확인 여부: **아직 확인 불가** (전송하지 않음)
- 한글 표시 확인 여부: 아직 확인 불가
- 링크 클릭 확인 여부: 아직 확인 불가
- 메시지 잘림 여부: 아직 확인 불가
- STEP 12 완료 여부: **미완료 (IN_PROGRESS)**

참고 — 미리 알아 둘 점:
- 가짜 Webhook 주소로 코드 흐름만 따로 점검했을 때(실제 전송 없음), 요청이 1회에서 멈추고 링크 5개가 모두 Slack 형식으로 바뀌는 것을 확인했다.
- Slack의 단순 `text` 메시지는 Markdown **표(`| ... |`)를 표로 그리지 않는다.**
  4장 "주요 공고"와 6장 "검증 결과"는 `|` 기호가 그대로 보일 수 있다. 이번 STEP은 링크만 바꾸기로 했으므로 그대로 두었다.
- Markdown 제목(`#`, `##`)과 굵게(`**`) 표시도 Slack에서는 기호 그대로 보일 수 있다.

다음에 할 일:
1. Slack에서 Incoming Webhook을 만들고, 프로젝트 루트 `.env`의 `SLACK_WEBHOOK_URL=` 뒤에 URL을 붙여 넣는다.
2. 이 셀을 **한 번만** 다시 실행한다. (실행할 때마다 Slack에 메시지가 1번 올라간다)
3. 출력에서 `Slack HTTP 상태 코드: 200`, `Slack 응답 본문: ok`인지 확인한다.
4. Slack 채널에서 도착 여부, 한글, 제목, 링크 클릭, 잘림 여부를 직접 확인한다.

# STEP 12. Slack 메시지 포맷 보완

## 작업 계획

앞의 STEP 12 셀에서는 `reports/ax_job_report.md`의 **일반 Markdown 전체**를 Slack으로 보냈다.
메시지는 채널에 잘 도착했고 한글도 정상이었지만, Slack 화면에서 다음 문법이 그대로 기호로 보였다.
- `#`, `##` 제목
- `**굵게**`
- Markdown 표 (`| ... |`)
- 일부 Markdown 링크, 역슬래시

왜 이런 일이 생기는가:
- Slack은 일반 Markdown이 아니라 **Slack 전용 문법(mrkdwn)**을 쓴다.
- 그래서 보고서 파일을 그대로 보내지 않고, **Slack에서 읽기 좋은 요약 메시지**를 따로 만들어 1번 다시 보낸다.

Slack 메시지에 쓸 문법 (최소한만):

| 쓰는 것 | 뜻 |
|---|---|
| `*굵게*` | 별표 1개로 감싸면 굵게 |
| `•` | 목록 기호 (글자 그대로 사용) |
| `<URL\|표시문구>` | 클릭 가능한 링크 |

쓰지 않는 것: `#` 제목, `**굵게**`, Markdown 표, `[링크](URL)`

- 회사명·공고 제목 안의 `&`, `<`, `>`는 Slack에서 특수 문자라서 `&amp;`, `&lt;`, `&gt;`로 바꿔 넣는다. (Slack 화면에는 원래 글자로 보인다)

메시지 내용 (보고서 핵심만):
- 분석 기준, 회사별·지역별 공고 수 → `data/processed/jobs_history.csv`를 **읽기만** 해서 다시 계산
- Gemini 검증 결과 → STEP 10 결과 (일치 7 / 의미상 일치 3 / 불일치 0 / 검증 불가 5)
- 주요 공고 → 현재 데이터 **순서 그대로** 5건 (추천 순위를 만들지 않음), 회사명·제목·링크만
- 제한 사항

이번 단계에서 하지 않는 것:
- 기존 STEP 12 셀 수정, 보고서 재생성
- Gemini 호출, JobKorea 요청
- Gmail, main.py, GitHub Actions

완료 기준:
- Slack 요청 **1회** (자동 재시도 없음)
- 실제 Slack 채널 도착, 한글 정상
- 제목·섹션 구분이 읽기 좋고, 공고 링크가 클릭된다
- `#`, `**`, Markdown 표 같은 일반 Markdown 문법이 보이지 않는다
- Webhook URL 미노출
- HTTP 200이 나와도 자동 완료 처리하지 않는다. 사람이 Slack 화면에서 확인한 뒤 완료한다.

In [ ]:
from pathlib import Path
import os
import pandas as pd
import requests
from dotenv import load_dotenv

# ----- 1) 프로젝트 루트의 .env 로드 -----
current_dir = Path.cwd()
project_root = current_dir.parent if current_dir.name == "notebooks" else current_dir
env_path = project_root / ".env"
if env_path.exists():
    load_dotenv(env_path)

# Webhook URL은 설정 여부만 출력한다 (값은 절대 출력하지 않음)
slack_webhook_url = os.getenv("SLACK_WEBHOOK_URL")
print("SLACK_WEBHOOK_URL 설정 여부:", "설정됨" if slack_webhook_url else "미설정")

# ----- 2) 데이터 읽기 (history CSV는 읽기만 한다) -----
history_path = project_root / "data" / "processed" / "jobs_history.csv"
history_df = pd.read_csv(history_path)

total_jobs = len(history_df)
keywords = ", ".join(history_df["search_keyword"].unique())
company_counts = history_df["company_name"].value_counts()
location_counts = history_df["location"].value_counts()


# 날짜 범위: 비교는 날짜 타입으로, 메시지에는 원본 문자열을 그대로 쓴다
def date_range(column):
    parsed = pd.to_datetime(history_df[column], errors="coerce")
    return history_df.loc[parsed.idxmin(), column], history_df.loc[parsed.idxmax(), column]


posted_min, posted_max = date_range("posted_date")
closing_min, closing_max = date_range("closing_date")


# ----- 3) Slack 메시지 조각 만들기 -----
def slack_escape(text):
    # Slack mrkdwn에서 특수 문자인 &, <, > 를 Slack 방식으로 바꾼다 (화면에는 원래 글자로 보임)
    return str(text).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def counts_to_bullets(counts):
    return "\n".join(f"• {slack_escape(name)}: {count}건" for name, count in counts.items())


# 주요 공고: 현재 데이터 순서 그대로 최대 5건 (추천 순위를 만들지 않음)
MAX_JOBS_IN_SLACK = 5
job_lines = []

for _, row in history_df.head(5).iterrows():
    job_lines.append(
        f"• {row['company_name']} — {row['job_title']}\n"
        f"  지원 시작: {row['posted_date']}\n"
        f"  지원 마감: {row['closing_date']}\n"
        f"  <{row['job_url']}|공고 보기>"
    )

jobs_text = "\n".join(job_lines)

# STEP 10 검증 결과 (STEP 10 셀 출력 기준)
validation_summary = {"일치": 7, "의미상 일치": 3, "불일치": 0, "검증 불가": 5}
validation_text = "\n".join(f"• {k}: {v}" for k, v in validation_summary.items())

# ----- 4) Slack 요약 메시지 만들기 (Slack mrkdwn 최소 문법만 사용) -----
slack_message = f"""
*AX 채용 분석 보고서*
현재 수집된 {total_jobs}건 기준 요약입니다. (전체 보고서: reports 폴더의 ax_job_report.md)

*분석 기준*
• 검색어: {slack_escape(keywords)}
• 분석 대상: {total_jobs}건
• 지원 시작일: {posted_min} ~ {posted_max}
• 지원 마감일: {closing_min} ~ {closing_max}

*회사별 공고 수*
{counts_to_bullets(company_counts)}

*지역별 공고 수*
{counts_to_bullets(location_counts)}

*Gemini 검증* (STEP 10, 15개 항목)
• 검증 공고: 에스코어 / AX 컨설턴트 채용
{validation_text}

*주요 공고* (수집 순서, {len(job_lines)}건)
{jobs_text}

*제한 사항*
• 현재 {total_jobs}건 기준
• 검색어 {slack_escape(keywords)} 1개
• 상세페이지 미수집
• Gemini 검증은 에스코어 1건 기준
• 전체 채용시장으로 일반화하지 않음
""".strip()

print("Slack 요약 메시지 문자 수:", len(slack_message))
print("주요 공고 포함 건수:", len(job_lines))

# ----- 5) Slack 요청 (Webhook URL이 있을 때만, 1회만) -----
slack_request_count = 0

if not slack_webhook_url:
    print("\nSLACK_WEBHOOK_URL이 설정되지 않아 Slack 요청을 보내지 않습니다.")
else:
    try:
        slack_request_count += 1
        response = requests.post(slack_webhook_url, json={"text": slack_message}, timeout=10)
        print("\nSlack HTTP 상태 코드:", response.status_code)
        print("Slack 응답 본문:", response.text)
    except Exception as e:
        # 오류 메시지 안에 Webhook URL이 들어 있으면 *** 로 가린다
        safe_message = str(e).replace(slack_webhook_url, "***")
        print("\nSlack 요청 실패")
        print("오류 종류:", type(e).__name__)
        print("오류 메시지:", safe_message[:300])

print("Slack 요청 횟수:", slack_request_count)

SLACK_WEBHOOK_URL 설정 여부: 설정됨
Slack 요약 메시지 문자 수: 1047
주요 공고 포함 건수: 5

Slack HTTP 상태 코드: 200
Slack 응답 본문: ok
Slack 요청 횟수: 1

## 실행 결과 해석 / 분석 / 요약

- 셀이 에러 없이 실행되었다. (Gemini 호출·JobKorea 요청 없음, 보고서·history CSV는 읽기만 함)
- SLACK_WEBHOOK_URL 설정 여부: **설정됨**
- Slack 요약 메시지 문자 수: **1047자** (1차 전송의 전체 보고서 3375자보다 짧음)
- 주요 공고 포함 건수: **5건** (현재 데이터 순서 그대로, 추천 순위 없음)
- Slack 요청 횟수: **1회** (자동 재시도 없음)
- HTTP 상태 코드: **200**
- Slack 응답 본문: **ok**
- Webhook URL 노출 여부: **노출 없음** — 저장된 셀 출력에 Webhook URL이 없는 것을 확인했다.

1차 전송과 비교:

| 구분 | 1차 전송 (앞의 STEP 12 셀) | 이번 보완 전송 |
|---|---|---|
| 보낸 내용 | 보고서 Markdown 전체 | Slack용 요약 메시지 |
| 문자 수 | 3375자 | 1047자 |
| 문법 | 일반 Markdown (`#`, `**`, 표) | Slack mrkdwn (`*굵게*`, `•`, `<URL\|공고 보기>`) |
| Slack 화면 문제 | 제목·굵게·표 기호가 그대로 보임 | 사용자 확인 필요 |

- 전송 전 점검: 메시지에 줄 시작 `#`, `**`, Markdown 표, `[링크](URL)` 형식이 **없는 것**을 확인했다.
- `HRD & AX`의 `&`는 Slack 규칙에 따라 `&amp;`로 바꿔 보냈다. (Slack 화면에는 `&`로 보여야 한다)

사용자가 Slack 채널에서 직접 확인할 항목:
1. 메시지가 실제 도착했는가
2. 제목(*AX 채용 분석 보고서*)이 굵게 보이는가
3. 섹션 구분이 읽기 좋은가
4. 한글이 정상인가
5. 공고 링크("공고 보기")가 클릭되는가
6. Markdown 표가 더 이상 그대로 보이지 않는가
7. `#`, `##`, `**` 같은 일반 Markdown 문법이 그대로 보이지 않는가
8. 메시지가 잘리지 않았는가 (마지막 "제한 사항"까지 보이는가)

- STEP 12 완료 여부: **IN_PROGRESS** — HTTP 200 / ok는 "Slack이 요청을 받았다"는 뜻일 뿐이다. 위 8개 항목을 사람이 확인한 뒤 완료 처리한다.
- 주의: 이 셀을 다시 실행하면 Slack에 메시지가 1번 더 올라간다.

# STEP 12. Slack 메시지 포맷 보완 (공고별 상세 정보)

## 작업 계획

앞의 보완 전송에서는 회사별·지역별 공고 수와 공고 제목·링크만 보냈다.
이번에는 `data/processed/jobs_history.csv`에 저장된 **각 공고의 정보를 가능한 한 모두** Slack 메시지에 보여 준다.

공고 1건당 표시할 정보 (CSV 컬럼 9개 전부):

| 표시 이름 | CSV 컬럼 |
|---|---|
| 번호 + 회사명 (굵게) | `company_name` |
| 공고 제목 | `job_title` |
| 경력 | `career` |
| 지역 | `location` |
| 지원 시작일 | `posted_date` |
| 지원 마감일 | `closing_date` |
| 검색어 | `search_keyword` |
| 수집 시각 | `collected_at` |
| 공고 보기 (링크) | `job_url` |

원칙:
- 공고 순서는 **CSV 순서 그대로** 사용한다. 번호(1, 2, 3 …)는 순서 표시일 뿐 **추천 순위가 아니다.**
- 5건 모두 표시한다.
- Slack mrkdwn만 사용한다: `*굵게*`, `•` 목록, `<URL|공고 보기>` 링크
  - `#`, `##`, `**`, Markdown 표, `[링크](URL)`는 쓰지 않는다.
- 회사명·제목 등의 `&`, `<`, `>`는 앞의 보완 셀과 같이 Slack 규칙대로 바꿔 넣는다.
- CSV와 보고서 파일은 **읽기만** 한다.

이번 단계에서 하지 않는 것:
- 기존 셀 수정, 보고서 수정, history CSV 수정
- Gemini 호출, JobKorea 요청
- Gmail, main.py, src, GitHub Actions

완료 기준:
- Slack 요청 **1회** (자동 재시도 없음), HTTP 상태 코드·응답 본문 확인
- Webhook URL 미노출
- 사람이 Slack 화면에서 공고별 정보가 읽기 좋게 보이는지 확인한 뒤 STEP 12를 완료 처리한다. (그 전까지 IN_PROGRESS)

In [1]:
from pathlib import Path
import os
import pandas as pd
import requests
from dotenv import load_dotenv

# ----- 1) 프로젝트 루트의 .env 로드 -----
current_dir = Path.cwd()
project_root = current_dir.parent if current_dir.name == "notebooks" else current_dir
env_path = project_root / ".env"
if env_path.exists():
    load_dotenv(env_path)

# Webhook URL은 설정 여부만 출력한다 (값은 절대 출력하지 않음)
slack_webhook_url = os.getenv("SLACK_WEBHOOK_URL")
print("SLACK_WEBHOOK_URL 설정 여부:", "설정됨" if slack_webhook_url else "미설정")

# ----- 2) 데이터 읽기 (history CSV는 읽기만 한다) -----
history_path = project_root / "data" / "processed" / "jobs_history.csv"
history_df = pd.read_csv(history_path)
total_jobs = len(history_df)
print("공고 수:", total_jobs)


def slack_escape(text):
    # Slack mrkdwn에서 특수 문자인 &, <, > 를 Slack 방식으로 바꾼다 (화면에는 원래 글자로 보임)
    return str(text).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


# ----- 3) 공고별 상세 정보 블록 만들기 (CSV 순서 그대로, 번호는 순서 표시일 뿐 추천 순위가 아님) -----
job_blocks = []
for i, (_, row) in enumerate(history_df.iterrows(), start=1):
    job_blocks.append(
        f"*{i}. {slack_escape(row['company_name'])}*\n"
        f"• 공고 제목: {slack_escape(row['job_title'])}\n"
        f"• 경력: {slack_escape(row['career'])}\n"
        f"• 지역: {slack_escape(row['location'])}\n"
        f"• 지원 시작일: {row['posted_date']}\n"
        f"• 지원 마감일: {row['closing_date']}\n"
        f"• 검색어: {slack_escape(row['search_keyword'])}\n"
        f"• 수집 시각: {row['collected_at']}\n"
        f"• <{row['job_url']}|공고 보기>"
    )
jobs_text = "\n\n".join(job_blocks)

# STEP 10 검증 결과 (STEP 10 셀 출력 기준)
validation_summary = {"일치": 7, "의미상 일치": 3, "불일치": 0, "검증 불가": 5}
validation_text = "\n".join(f"• {k}: {v}" for k, v in validation_summary.items())
keyword_text = slack_escape(", ".join(history_df["search_keyword"].unique()))

# ----- 4) Slack 메시지 만들기 (Slack mrkdwn 최소 문법만 사용) -----
slack_message = f"""
*AX 채용 분석 보고서*

현재 수집된 {total_jobs}건 기준입니다. (공고 번호는 수집 순서이며 추천 순위가 아닙니다)

*공고별 상세 정보*

{jobs_text}

*Gemini 검증*
• 검증 공고: 에스코어 / AX 컨설턴트 채용
{validation_text}

*제한 사항*
• 현재 {total_jobs}건 기준
• 검색어 {keyword_text} 1개
• 상세페이지 미수집
• Gemini 검증은 에스코어 1건 기준
• 전체 채용시장으로 일반화하지 않음
""".strip()

print("Slack 메시지 문자 수:", len(slack_message))
print("표시한 공고 수:", len(job_blocks))

# ----- 5) Slack 요청 (Webhook URL이 있을 때만, 1회만) -----
slack_request_count = 0

if not slack_webhook_url:
    print("\nSLACK_WEBHOOK_URL이 설정되지 않아 Slack 요청을 보내지 않습니다.")
else:
    try:
        slack_request_count += 1
        response = requests.post(slack_webhook_url, json={"text": slack_message}, timeout=10)
        print("\nSlack HTTP 상태 코드:", response.status_code)
        print("Slack 응답 본문:", response.text)
    except Exception as e:
        # 오류 메시지 안에 Webhook URL이 들어 있으면 *** 로 가린다
        safe_message = str(e).replace(slack_webhook_url, "***")
        print("\nSlack 요청 실패")
        print("오류 종류:", type(e).__name__)
        print("오류 메시지:", safe_message[:300])

print("Slack 요청 횟수:", slack_request_count)

SLACK_WEBHOOK_URL 설정 여부: 설정됨
공고 수: 5
Slack 메시지 문자 수: 1393
표시한 공고 수: 5

Slack HTTP 상태 코드: 200
Slack 응답 본문: ok
Slack 요청 횟수: 1

## 실행 결과 해석 / 분석 / 요약

- 셀이 에러 없이 실행되었다. (Gemini 호출·JobKorea 요청 없음, 보고서·history CSV는 읽기만 함 — 체크섬 동일)
- SLACK_WEBHOOK_URL 설정 여부: **설정됨**
- Slack 메시지 문자 수: **1393자**
- 표시한 공고 수: **5건** — CSV 순서 그대로 (1. GS리테일, 2. 에스코어, 3. ㈜NAVER, 4. ㈜슈프리마, 5. ㈜NAVER)
  - 번호는 수집 순서이며 추천 순위가 아니라는 안내 문장을 메시지 첫 부분에 넣었다.
- 공고당 표시 항목: CSV 컬럼 **9개 전부** (회사명, 공고 제목, 경력, 지역, 지원 시작일, 지원 마감일, 검색어, 수집 시각, 공고 링크)
- Slack 요청 횟수: **1회** (자동 재시도 없음)
- HTTP 상태 코드: **200**
- Slack 응답 본문: **ok**
- Webhook URL 노출 여부: **노출 없음** — 저장된 셀 출력에 Webhook URL이 없는 것을 확인했다.
- 전송 전 점검 (가짜 요청, 네트워크 없음): 줄 시작 `#`, `**`, Markdown 표, `[링크](URL)` **없음**, `<URL|공고 보기>` 링크 **5개**

Slack 전송 기록 (STEP 12 전체):

| 전송 | 내용 | 문자 수 | 결과 |
|---|---|---:|---|
| 1차 | 보고서 Markdown 전체 | 3375 | 도착·한글 정상, Markdown 기호가 그대로 보임 (사용자 확인) |
| 보완 1 | Slack용 요약 (공고 제목·링크) | 1047 | 200 ok |
| 보완 2 (이번) | 공고별 상세 정보 (9개 항목) | 1393 | 200 ok — 사용자 화면 확인 필요 |

참고:
- 모든 공고의 수집 시각이 `2026-09-23 14:00:39`로 같다. history CSV는 STEP 07-D 실행 때 한 번에 저장되었기 때문이다.
- `HRD & AX`의 `&`는 Slack 규칙대로 `&amp;`로 바꿔 보냈다. (화면에는 `&`로 보여야 한다)

사용자가 Slack 채널에서 확인할 항목:
1. 메시지가 도착했는가
2. 공고 5건이 번호와 회사명(굵게)으로 구분되어 보이는가
3. 각 공고의 9개 항목이 모두 보이는가
4. 한글과 `&`가 정상으로 보이는가
5. "공고 보기" 링크 5개가 클릭되는가
6. `#`, `**`, 표 기호가 보이지 않는가
7. 메시지가 끝("제한 사항")까지 잘리지 않았는가

- STEP 12 완료 여부: **IN_PROGRESS** — 사용자가 Slack 화면을 확인한 뒤 완료 처리한다.
- 주의: 이 셀을 다시 실행하면 Slack에 메시지가 1번 더 올라간다.

# STEP 12. Slack 메시지 포맷 보완 (공고 URL 표시)

## 작업 계획

앞의 셀(공고별 상세 정보)에서는 공고 링크를 `<URL|공고 보기>` 형태로만 보냈다.
Slack 화면에는 "공고 보기"라는 글자만 보이고 실제 주소는 보이지 않는다.

이번에는 각 공고마다 **실제 공고 URL 문자열도 함께** 보여 준다.

공고 1건 표시 형식:
- `*번호. 회사명*` (굵게)
- 공고 제목 / 경력 / 지역 / 지원 시작일 / 지원 마감일 / 검색어 / 수집 시각
- **공고 URL: https://...** ← 이번에 추가 (history CSV의 `job_url` 값 그대로)
- `<URL|공고 보기>` 링크 (기존 그대로)

원칙:
- 5건 모두, CSV 순서 그대로 표시한다. 번호는 순서 표시일 뿐 추천 순위가 아니다.
- URL은 `data/processed/jobs_history.csv`의 값을 그대로 쓴다. (CSV는 읽기만 한다)
- Slack mrkdwn 최소 문법만 사용한다. (`#`, `**`, Markdown 표, `[링크](URL)` 사용 안 함)
- Slack은 메시지 안의 URL 문자열을 자동으로 링크로 바꿔 보여 줄 수 있다.

이번 단계에서 하지 않는 것:
- 기존 셀 수정, 보고서·history CSV 수정
- Gemini 호출, JobKorea 요청, Gmail

완료 기준:
- Slack 요청 **1회** (자동 재시도 없음), HTTP 상태 코드·응답 본문 확인
- Webhook URL 미노출
- 사용자가 Slack 화면에서 URL 문자열과 링크가 모두 보이는지 확인한 뒤 STEP 12를 완료 처리한다. (그 전까지 IN_PROGRESS)

In [ ]:
from pathlib import Path
import os
import pandas as pd
import requests
from dotenv import load_dotenv

# ----- 1) 프로젝트 루트의 .env 로드 -----
current_dir = Path.cwd()
project_root = current_dir.parent if current_dir.name == "notebooks" else current_dir
env_path = project_root / ".env"
if env_path.exists():
    load_dotenv(env_path)

# Webhook URL은 설정 여부만 출력한다 (값은 절대 출력하지 않음)
slack_webhook_url = os.getenv("SLACK_WEBHOOK_URL")
print("SLACK_WEBHOOK_URL 설정 여부:", "설정됨" if slack_webhook_url else "미설정")

# ----- 2) 데이터 읽기 (history CSV는 읽기만 한다) -----
history_path = project_root / "data" / "processed" / "jobs_history.csv"
history_df = pd.read_csv(history_path)
total_jobs = len(history_df)
print("공고 수:", total_jobs)


def slack_escape(text):
    # Slack mrkdwn에서 특수 문자인 &, <, > 를 Slack 방식으로 바꾼다 (화면에는 원래 글자로 보임)
    return str(text).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


# ----- 3) 공고별 상세 정보 블록 만들기 (CSV 순서 그대로, 번호는 순서 표시일 뿐 추천 순위가 아님) -----
# 이번 보완: "공고 보기" 링크와 함께 실제 URL 문자열도 표시한다
job_blocks = []
for i, (_, row) in enumerate(history_df.iterrows(), start=1):
    job_url = row["job_url"]  # history CSV 값을 그대로 사용
    job_blocks.append(
        f"*{i}. {slack_escape(row['company_name'])}*\n"
        f"• 공고 제목: {slack_escape(row['job_title'])}\n"
        f"• 경력: {slack_escape(row['career'])}\n"
        f"• 지역: {slack_escape(row['location'])}\n"
        f"• 지원 시작일: {row['posted_date']}\n"
        f"• 지원 마감일: {row['closing_date']}\n"
        f"• 검색어: {slack_escape(row['search_keyword'])}\n"
        f"• 수집 시각: {row['collected_at']}\n"
        f"• 공고 URL: {job_url}\n"
    )
jobs_text = "\n\n".join(job_blocks)

# STEP 10 검증 결과 (STEP 10 셀 출력 기준)
validation_summary = {"일치": 7, "의미상 일치": 3, "불일치": 0, "검증 불가": 5}
validation_text = "\n".join(f"• {k}: {v}" for k, v in validation_summary.items())
keyword_text = slack_escape(", ".join(history_df["search_keyword"].unique()))

# ----- 4) Slack 메시지 만들기 (Slack mrkdwn 최소 문법만 사용) -----
slack_message = f"""
*AX 채용 분석 보고서*

현재 수집된 {total_jobs}건 기준입니다. (공고 번호는 수집 순서이며 추천 순위가 아닙니다)

*공고별 상세 정보*

{jobs_text}

*Gemini 검증*
• 검증 공고: 에스코어 / AX 컨설턴트 채용
{validation_text}

*제한 사항*
• 현재 {total_jobs}건 기준
• 검색어 {keyword_text} 1개
• 상세페이지 미수집
• Gemini 검증은 에스코어 1건 기준
• 전체 채용시장으로 일반화하지 않음
""".strip()

print("Slack 메시지 문자 수:", len(slack_message))
print("표시한 공고 수:", len(job_blocks))

# ----- 5) Slack 요청 (Webhook URL이 있을 때만, 1회만) -----
slack_request_count = 0

if not slack_webhook_url:
    print("\nSLACK_WEBHOOK_URL이 설정되지 않아 Slack 요청을 보내지 않습니다.")
else:
    try:
        slack_request_count += 1
        response = requests.post(slack_webhook_url, json={"text": slack_message}, timeout=10)
        print("\nSlack HTTP 상태 코드:", response.status_code)
        print("Slack 응답 본문:", response.text)
    except Exception as e:
        # 오류 메시지 안에 Webhook URL이 들어 있으면 *** 로 가린다
        safe_message = str(e).replace(slack_webhook_url, "***")
        print("\nSlack 요청 실패")
        print("오류 종류:", type(e).__name__)
        print("오류 메시지:", safe_message[:300])

print("Slack 요청 횟수:", slack_request_count)

SLACK_WEBHOOK_URL 설정 여부: 설정됨
공고 수: 5
Slack 메시지 문자 수: 1703
표시한 공고 수: 5

Slack HTTP 상태 코드: 200
Slack 응답 본문: ok
Slack 요청 횟수: 1

## 실행 결과 해석 / 분석 / 요약

- 셀이 에러 없이 실행되었다. (Gemini 호출·JobKorea 요청 없음, 보고서·history CSV는 읽기만 함 — 체크섬 동일)
- SLACK_WEBHOOK_URL 설정 여부: **설정됨**
- Slack 메시지 문자 수: **1703자** (앞의 공고별 상세 메시지 1393자 + URL 줄 5개)
- 표시한 공고 수: **5건** — CSV 순서 그대로 (번호는 수집 순서, 추천 순위 아님)
- 공고당 표시 항목: 회사명, 공고 제목, 경력, 지역, 지원 시작일, 지원 마감일, 검색어, 수집 시각, **공고 URL 문자열**(이번 추가), "공고 보기" 링크
- 전송 전 점검 (가짜 요청, 네트워크 없음):
  - 메시지에 표시된 공고 URL 5개가 history CSV의 `job_url` 값·순서와 **완전히 같음**
  - `<URL|공고 보기>` 링크 5개, 줄 시작 `#`·`**`·Markdown 표 없음
- Slack 요청 횟수: **1회** (자동 재시도 없음)
- HTTP 상태 코드: **200**
- Slack 응답 본문: **ok**
- Webhook URL 노출 여부: **노출 없음** — 저장된 셀 출력에 Webhook URL이 없는 것을 확인했다.

Slack 전송 기록 (STEP 12 전체):

| 전송 | 내용 | 문자 수 | 결과 |
|---|---|---:|---|
| 1차 | 보고서 Markdown 전체 | 3375 | 도착·한글 정상, Markdown 기호가 그대로 보임 (사용자 확인) |
| 보완 1 | Slack용 요약 (공고 제목·링크) | 1047 | 200 ok |
| 보완 2 | 공고별 상세 정보 (9개 항목) | 1393 | 200 ok |
| 보완 3 (이번) | 공고별 상세 정보 + 공고 URL 문자열 | 1703 | 200 ok — 사용자 화면 확인 필요 |

사용자가 Slack 채널에서 확인할 항목:
1. 메시지가 도착했는가
2. 각 공고에 "공고 URL: https://..." 줄과 "공고 보기" 링크가 **둘 다** 보이는가
3. URL 문자열과 "공고 보기" 링크가 모두 클릭되는가 (Slack은 URL 문자열을 자동으로 링크로 바꿔 줄 수 있다)
4. 한글·`&`가 정상이고, `#`·`**`·표 기호가 보이지 않는가
5. 메시지가 끝("제한 사항")까지 잘리지 않았는가
   - Slack이 URL마다 **링크 미리보기**를 붙이면 메시지가 길어 보일 수 있다. 너무 길면 알려 주면 된다.

- STEP 12 완료 여부: **IN_PROGRESS** — 사용자가 Slack 화면을 확인한 뒤 완료 처리한다.
- 주의: 이 셀을 다시 실행하면 Slack에 메시지가 1번 더 올라간다.

# STEP 13. Gmail 발송

## 작업 계획

STEP 11에서 만든 보고서 `reports/ax_job_report.md`를 **Gmail로 1번 보내서**, 실제 받은편지함에 도착하는지 확인한다.
이번 테스트에서는 **보내는 사람과 받는 사람을 같은 Gmail 계정**으로 한다. (자기 자신에게 발송)

Gmail 발송에 필요한 값 (`.env`에 저장):
- `GMAIL_USER` → 보내는 Gmail 주소
- `GMAIL_APP_PASSWORD` → Google 계정에서 발급한 **앱 비밀번호(App Password)**
  - 일반 Google 로그인 비밀번호가 **아니다.** 일반 비밀번호는 사용하지 않는다.
  - 앱 비밀번호는 2단계 인증을 켠 Google 계정에서 발급할 수 있는 16자리 비밀번호이다.
- 둘 다 비밀값이므로 화면에는 "설정됨 / 미설정"만 출력한다. (주소·비밀번호·일부 글자·길이 모두 출력하지 않음)

이번 단계에서 할 일:
1. `.env`에서 Gmail 인증정보 설정 여부 확인 — 하나라도 없으면 **연결하지 않고 멈춘다**
2. `reports/ax_job_report.md` 읽기 (파일은 수정하지 않는다)
3. 이메일 제목과 본문 만들기
   - 제목: `[AX Job Agent] AX 채용 분석 보고서`
   - 본문: 안내 문장 + 보고서 Markdown을 **일반 텍스트(Plain Text)** 그대로 (HTML 메일은 만들지 않음)
4. Gmail SMTP 서버(`smtp.gmail.com`, 포트 465)에 **SMTP_SSL**(암호화 연결)로 접속
5. 자기 자신에게 **1회** 발송 (자동 재시도 없음)
6. 실제 Gmail 받은편지함에서 사람이 확인

용어:
- **SMTP**: 이메일을 보내는 표준 방식(프로토콜)
- **SMTP_SSL**: 처음부터 암호화된 연결로 SMTP 서버에 접속하는 방식
- **EmailMessage**: Python 표준 라이브러리로 제목·보내는 사람·받는 사람·본문을 담는 이메일 객체

이번 단계에서 하지 않는 것:
- Slack 재전송
- Gemini 호출
- JobKorea 요청
- 보고서 재생성
- STEP 14
- main.py
- GitHub Actions

완료 기준:
- Gmail 발송 **1회** 성공
- 실제 받은편지함 도착, 제목·본문 한글 정상, 본문 전체와 공고 URL 표시
- 인증정보 미노출
- SMTP 성공만으로 완료 처리하지 않는다. 사람이 Gmail에서 확인한 뒤 완료한다.

In [1]:
from pathlib import Path
import os
import smtplib
from email.message import EmailMessage
from dotenv import load_dotenv

# ----- 1) 프로젝트 루트의 .env 로드 -----
project_root = Path.cwd()
if project_root.name == "notebooks":
    project_root = project_root.parent

env_path = project_root / ".env"
if env_path.exists():
    load_dotenv(env_path)

# 인증정보는 설정 여부만 출력한다 (주소·비밀번호·일부 글자·길이 모두 출력하지 않음)
gmail_user = os.getenv("GMAIL_USER")
gmail_app_password = os.getenv("GMAIL_APP_PASSWORD")
print("GMAIL_USER 설정 여부:", "설정됨" if gmail_user else "미설정")
print("GMAIL_APP_PASSWORD 설정 여부:", "설정됨" if gmail_app_password else "미설정")

# ----- 2) 보고서 읽기 (파일은 수정하지 않는다) -----
report_path = project_root / "reports" / "ax_job_report.md"
if not report_path.exists():
    raise FileNotFoundError("reports/ax_job_report.md가 없습니다. STEP 11을 먼저 실행하세요.")

report_text = report_path.read_text(encoding="utf-8")
print("보고서 문자 수:", len(report_text))

# ----- 3) 이메일 제목과 본문 만들기 (Plain Text) -----
email_subject = "[AX Job Agent] AX 채용 분석 보고서"
email_body = f"""안녕하세요.

AX 채용정보 Agent에서 생성한 분석 보고서입니다.

아래 내용은 현재 수집된 데이터 기준입니다.

---

{report_text}
"""
print("이메일 제목:", email_subject)
print("이메일 본문 문자 수:", len(email_body))

# ----- 4) Gmail 발송 (인증정보가 모두 있을 때만, 1회만) -----
gmail_send_count = 0

if not (gmail_user and gmail_app_password):
    print("\nGmail 인증정보가 준비되지 않아 발송하지 않습니다.")
    print("프로젝트 루트의 .env에 GMAIL_USER와 GMAIL_APP_PASSWORD(앱 비밀번호)를 입력한 뒤 다시 실행하세요.")
else:
    # EmailMessage: 제목·보내는 사람·받는 사람·본문을 담는 이메일 객체
    # 이번 테스트는 자기 자신에게 보낸다 (다른 주소를 코드에 적지 않음)
    msg = EmailMessage()
    msg["Subject"] = email_subject
    msg["From"] = gmail_user
    msg["To"] = gmail_user
    msg.set_content(email_body)  # 한글이 들어 있으면 자동으로 UTF-8로 인코딩된다

    try:
        # SMTP_SSL: 처음부터 암호화된 연결로 Gmail SMTP 서버(포트 465)에 접속
        with smtplib.SMTP_SSL("smtp.gmail.com", 465, timeout=15) as smtp:
            smtp.login(gmail_user, gmail_app_password)
            smtp.send_message(msg)
        gmail_send_count = 1
        print("\nGmail SMTP 발송: 성공")
    except Exception as e:
        # 오류 메시지 안에 주소나 비밀번호가 들어 있으면 *** 로 가린다 (자동 재시도하지 않음)
        safe_message = str(e)
        for secret in (gmail_user, gmail_app_password):
            safe_message = safe_message.replace(secret, "***")
        print("\nGmail SMTP 발송: 실패")
        print("오류 종류:", type(e).__name__)
        print("오류 메시지:", safe_message[:300])

print("Gmail 발송 횟수:", gmail_send_count)

GMAIL_USER 설정 여부: 미설정
GMAIL_APP_PASSWORD 설정 여부: 미설정
보고서 문자 수: 3331
이메일 제목: [AX Job Agent] AX 채용 분석 보고서
이메일 본문 문자 수: 3403

Gmail 인증정보가 준비되지 않아 발송하지 않습니다.
프로젝트 루트의 .env에 GMAIL_USER와 GMAIL_APP_PASSWORD(앱 비밀번호)를 입력한 뒤 다시 실행하세요.
Gmail 발송 횟수: 0

## 실행 결과 해석 / 분석 / 요약

- 셀이 에러 없이 실행되었다. (Slack 재전송·Gemini 호출·JobKorea 요청 없음, 보고서는 읽기만 함 — 체크섬 동일)
- GMAIL_USER 설정 여부: **미설정** — `.env`에 `GMAIL_USER=` 줄은 있지만 값이 비어 있다.
- GMAIL_APP_PASSWORD 설정 여부: **미설정** — `.env`에 `GMAIL_APP_PASSWORD=` 줄은 있지만 값이 비어 있다.
- 보고서 읽기 성공 여부: **성공** — `reports/ax_job_report.md`
- 보고서 문자 수: **3331자** (안내 문장을 더한 이메일 본문은 3403자)
- 이메일 제목: `[AX Job Agent] AX 채용 분석 보고서`
- Gmail 발송 횟수: **0회** — 인증정보가 없어서 SMTP에 연결하지 않고 멈췄다.
- SMTP 성공 여부: 해당 없음 (연결하지 않음)
- 오류 여부: 없음
- 인증정보 노출 여부: **노출 없음** — "설정됨 / 미설정"만 출력했다.
- 실제 Gmail 도착 여부: 사용자 확인 필요 (아직 발송하지 않음)
- 제목 정상 여부: 사용자 확인 필요
- 한글 정상 여부: 사용자 확인 필요
- 본문 전체 표시 여부: 사용자 확인 필요
- 공고 URL 표시 여부: 사용자 확인 필요
- STEP 13 현재 상태: **IN_PROGRESS** — 코드 준비 완료, Gmail 인증정보 설정 대기

참고 — 발송 코드 사전 점검 (가짜 계정·가짜 SMTP 서버, 네트워크 연결 없음):
- 인증정보가 있을 때 `smtp.gmail.com:465`에 SMTP_SSL로 1회만 발송하는 흐름을 확인했다.
- 한글 제목이 원래대로 복원되고, 본문은 UTF-8로 인코딩되며, 보고서 전체와 공고 URL 5개가 본문에 들어가는 것을 확인했다.
- 보내는 사람과 받는 사람이 같은 주소(`GMAIL_USER`)로 설정되는 것을 확인했다.

다음에 할 일:
1. Google 계정에서 2단계 인증을 켜고 **앱 비밀번호**(16자리)를 발급한다. (일반 로그인 비밀번호는 사용하지 않는다)
2. 프로젝트 루트 `.env`에 `GMAIL_USER=본인 Gmail 주소`, `GMAIL_APP_PASSWORD=앱 비밀번호`를 입력한다.
3. 이 셀을 **한 번만** 다시 실행한다. (실행할 때마다 메일이 1통 발송된다)
4. 출력이 `Gmail SMTP 발송: 성공`, `Gmail 발송 횟수: 1`인지 확인한다.
5. Gmail에서 도착, 제목, 한글, 본문 전체, 공고 URL, 중복 메일 여부, 스팸함 여부를 확인한다.

# STEP 14. 함수화

## 작업 계획

지금까지 Notebook에서 검증한 코드를 **재사용 가능한 함수**로 `src/` 폴더에 분리한다.

역할 구분:
- **Notebook** → 실험 / 검증 / 기록
- **`src/`** → 재사용 가능한 운영 코드 (이번 STEP)
- **`main.py`** → 다음 STEP 15에서 전체 순서를 연결

만든 파일 (`src/`):

| 파일 | 대표 함수 | 옮겨 온 Notebook 로직 |
|---|---|---|
| `__init__.py` | (빈 파일) | `src`를 Python 패키지로 인식 |
| `crawler.py` | `collect_jobs()` | STEP 07-A 실데이터 수집 |
| `preprocess.py` | `clean_jobs()`, `find_new_jobs()`, `update_history()` | STEP 06, 07-C, 07-D |
| `analyzer.py` | `analyze_jobs()`, `find_matched_keywords_safe()`, `filter_relevant_jobs()` | STEP 07-E, 07-F, 07-G |
| `gemini_client.py` | `summarize_with_gemini()` | STEP 09 |
| `reporter.py` | `create_report()`, `save_report()` | STEP 11 |
| `notifier.py` | `build_slack_message()`, `send_slack()`, `send_email()` | STEP 12, 13 |

가장 중요한 원칙 — 이번 작업은 **리팩터링**이다. 새로운 동작을 추가하지 않는다.
- `posted_date` = 지원 제출 시작일(`applicationPeriod.start`), `closing_date` = 지원 제출 마감일(`applicationPeriod.end`), `createdAt` 미사용
- 공고 식별 기준은 `job_url`, history는 `job_url` 기준 (`keep="last"`)
- 영문 키워드 안전 매칭 규칙 유지 (Tax/Max/Maintenance/Training 오탐 방지)
- Gemini는 제공된 정보만 사용 ("확인 불가")
- Slack 메시지는 사용자가 최종 확인한 형식 유지 (공고 URL 1회만 표시)
- 인증정보(API 키, Webhook URL, Gmail 주소·앱 비밀번호)는 코드에 쓰지 않고 인자로 받는다
- 함수는 결과를 **반환**한다. 파일 저장이 필요한 부분(`save_report`, history 저장)은 따로 분리한다.

이번 검증 방법:
- 외부 네트워크 없이, `data/processed/jobs_history.csv`(읽기 전용)로 **로컬 데이터 함수**만 실제 실행해 확인한다.
- 외부 요청 함수(`collect_jobs`, `summarize_with_gemini`, `send_slack`, `send_email`)는 **import와 호출 가능 여부(`callable`)만** 확인한다.
- `create_report()`는 문자열만 만들고, 기존 `reports/ax_job_report.md`는 덮어쓰지 않는다.

이번 STEP에서 하지 않는 것:
- 실제 웹 요청, Gemini API 호출, Slack 발송, Gmail 발송
- `main.py` 생성 (STEP 15)
- GitHub Actions

완료 조건:
- `src/` 7개 파일 생성, 모든 모듈 import 성공
- 로컬 데이터 함수 검증 성공, 안전 키워드 테스트 성공
- 실제 외부 요청 0회, history CSV·기존 보고서 변경 없음

In [1]:
import sys
from pathlib import Path
import pandas as pd

# ----- 0) src를 import할 수 있도록 프로젝트 루트를 경로에 추가 -----
project_root = Path.cwd()
if project_root.name == "notebooks":
    project_root = project_root.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from src.crawler import collect_jobs
from src.preprocess import clean_jobs, find_new_jobs
from src.analyzer import analyze_jobs, find_matched_keywords_safe, filter_relevant_jobs
from src.gemini_client import summarize_with_gemini
from src.reporter import create_report, save_report
from src.notifier import build_slack_message, send_slack, send_email

print("src import 성공: True")

# 로컬 데이터만 사용한다 (history CSV는 읽기만 함)
history_df = pd.read_csv(project_root / "data" / "processed" / "jobs_history.csv")
history_before = history_df.copy()

# ----- A) clean_jobs -----
cleaned_df = clean_jobs(history_df)
print("\n[clean_jobs]")
print("입력:", len(history_df), "/ 출력:", len(cleaned_df),
      "/ 중복 URL:", cleaned_df.duplicated(subset=["job_url"]).sum(),
      "/ 컬럼 유지:", cleaned_df.columns.tolist() == history_df.columns.tolist())

# ----- B) analyze_jobs -----
analysis = analyze_jobs(cleaned_df)
print("\n[analyze_jobs]")
print("전체 공고:", analysis["total_jobs"])
print("회사별:", analysis["company_counts"])
print("지역별:", analysis["location_counts"])
print("경력별:", analysis["career_counts"])
print("검색어별:", analysis["keyword_counts"])
print("지원 시작일:", analysis["posted_date_min"], "~", analysis["posted_date_max"])
print("지원 마감일:", analysis["closing_date_min"], "~", analysis["closing_date_max"])

# ----- C) find_matched_keywords_safe (STEP 07-G 대표 테스트) -----
keyword_tests = [
    ("AX 담당자", "AX", True), ("AX담당자", "AX", True),
    ("AI 기반", "AI", True), ("AI기반", "AI", True),
    ("Tax", "AX", False), ("Max", "AX", False),
    ("Maintenance", "AI", False), ("Training", "AI", False),
]
passed = sum((keyword in find_matched_keywords_safe(title)) == expected
             for title, keyword, expected in keyword_tests)
print("\n[키워드 안전 매칭 테스트]", passed, "/", len(keyword_tests), "통과")

# ----- D) filter_relevant_jobs -----
filtered_df = filter_relevant_jobs(cleaned_df)
print("\n[관련 공고 필터] 전체:", len(cleaned_df), "/ 통과:", len(filtered_df),
      "/ 매칭:", filtered_df["matched_keywords"].tolist())

# ----- E) find_new_jobs (history 자신과 비교하면 신규 0건이어야 함) -----
new_jobs_df = find_new_jobs(cleaned_df, history_df)
print("\n[신규 공고 테스트] 현재 vs 동일 history → 신규", len(new_jobs_df), "건")

# ----- F) create_report (문자열만 생성, 파일 저장 안 함) -----
validation_summary = {
    "target": "에스코어 / AX 컨설턴트 채용", "scope": "에스코어 1건", "total_items": 15,
    "counts": {"일치": 7, "의미상 일치": 3, "불일치": 0, "검증 불가": 5},
}
report_text = create_report(cleaned_df, analysis, gemini_summary=None, validation_summary=validation_summary)
section_titles = ["# AX 채용 분석 보고서", "## 1. 분석 기준", "## 2. 현재 수집 데이터 요약", "## 3. AX/AI 관련 공고 필터 결과",
                  "## 4. 주요 공고", "## 5. Gemini 분석 예시", "## 6. Gemini 검증 결과", "## 7. 제한 사항", "## 8. 다음 단계"]
print("\n[create_report] 반환 타입:", type(report_text).__name__, "/ 문자 수:", len(report_text),
      "/ 주요 제목 9개 포함:", all(t in report_text for t in section_titles))

# ----- G) build_slack_message (문자열만 생성, 발송 안 함) -----
slack_message = build_slack_message(cleaned_df, validation_summary)
print("\n[build_slack_message] 문자 수:", len(slack_message))
print("공고 5건 포함:", all(f"*{i}. " in slack_message for i in range(1, len(cleaned_df) + 1)))
print("지원 시작일 포함:", slack_message.count("• 지원 시작일:") == len(cleaned_df))
print("지원 마감일 포함:", slack_message.count("• 지원 마감일:") == len(cleaned_df))
print("공고 URL 포함:", all(url in slack_message for url in cleaned_df["job_url"]))
print("'공고 보기' 중복 링크 없음:", "공고 보기" not in slack_message)

# ----- H) 외부 요청 함수는 실행하지 않고 호출 가능 여부만 확인 -----
print("\n[외부 함수 callable] (실행하지 않음)")
for func in [collect_jobs, summarize_with_gemini, send_slack, send_email, save_report]:
    print(f"{func.__name__}: {callable(func)}")

# ----- I) 로컬 데이터가 바뀌지 않았는지 확인 -----
print("\nhistory_df 원본 보존:", history_df.equals(history_before))

src import 성공: True

[clean_jobs]
입력: 5 / 출력: 5 / 중복 URL: 0 / 컬럼 유지: True

[analyze_jobs]
전체 공고: 5
회사별: {'㈜NAVER': 2, 'GS리테일': 1, '에스코어': 1, '㈜슈프리마': 1}
지역별: {'경기 성남시': 3, '서울 강남구 외 1': 1, '서울 송파구': 1}
경력별: {'경력': 3, '경력3년↑': 1, '경력7년↑': 1}
검색어별: {'ax': 5}
지원 시작일: 2026-07-01 ~ 2026-09-21
지원 마감일: 2026-09-29 10:00 ~ 2026-10-25 23:00

[키워드 안전 매칭 테스트] 8 / 8 통과

[관련 공고 필터] 전체: 5 / 통과: 5 / 매칭: [['AX'], ['AX'], ['AX'], ['AX'], ['AX']]

[신규 공고 테스트] 현재 vs 동일 history → 신규 0 건

[create_report] 반환 타입: str / 문자 수: 2514 / 주요 제목 9개 포함: True

[build_slack_message] 문자 수: 1398
공고 5건 포함: True
지원 시작일 포함: True
지원 마감일 포함: True
공고 URL 포함: True
'공고 보기' 중복 링크 없음: True

[외부 함수 callable] (실행하지 않음)
collect_jobs: True
summarize_with_gemini: True
send_slack: True
send_email: True
save_report: True

history_df 원본 보존: True

## 실행 결과 해석 / 분석 / 요약

- 셀이 에러 없이 실행되었다.
- 생성한 src 파일: `__init__.py`, `crawler.py`, `preprocess.py`, `analyzer.py`, `gemini_client.py`, `reporter.py`, `notifier.py` (7개)
- import 성공 여부: **성공** — 6개 모듈의 함수를 모두 import했다.

로컬 데이터 함수 검증 (`jobs_history.csv` 5건, 읽기 전용):

| 함수 | 결과 |
|---|---|
| `clean_jobs()` | 입력 5 → 출력 5, 중복 URL 0, 컬럼 9개 그대로 |
| `analyze_jobs()` | 전체 5 / 회사별 NAVER 2·GS리테일 1·에스코어 1·슈프리마 1 / 지역별 경기 성남시 3·서울 강남구 외 1 1·서울 송파구 1 / 경력별 경력 3·경력3년↑ 1·경력7년↑ 1 / 검색어 ax 5 |
| (날짜 범위) | 지원 시작일 2026-07-01 ~ 2026-09-21, 지원 마감일 2026-09-29 10:00 ~ 2026-10-25 23:00 |
| `find_matched_keywords_safe()` | 대표 테스트 **8/8 통과** (AX 담당자·AX담당자·AI 기반·AI기반 매칭 / Tax·Max·Maintenance·Training 미매칭) |
| `filter_relevant_jobs()` | 전체 5 → 통과 5 (모두 `['AX']`) |
| `find_new_jobs()` | 현재 데이터 vs 같은 history → **신규 0건** |
| `create_report()` | `str` 반환, 2514자, 주요 제목 9개(보고서 제목 + 1~8장) 모두 포함 — 파일 저장 안 함 |
| `build_slack_message()` | 1398자, 공고 5건·지원 시작일·지원 마감일·공고 URL 포함, "공고 보기" 중복 링크 없음 — 발송 안 함 |

- 분석 결과는 이전 STEP(07-E, 11)의 값과 모두 같다.
- `create_report()` 결과가 STEP 11 보고서(3331자)보다 짧은 이유: 이번 검증에서는 Gemini 결과(`gemini_summary`)를 넣지 않았고, 검증 결과의 부가 설명(notes)도 넣지 않았기 때문이다. 실제 실행에서는 `summarize_with_gemini()` 결과를 넘겨 5장을 채운다.
- `build_slack_message()` 결과는 사용자가 최종 확인한 Slack 메시지(STEP 12 공고 URL 표시 셀, 사용자 수정본)와 **글자까지 같다.** (별도 비교로 확인)

외부 함수 callable 확인 (실행하지 않음):
- `collect_jobs`: True / `summarize_with_gemini`: True / `send_slack`: True / `send_email`: True / `save_report`: True

- 실제 외부 요청 횟수: **0회** — 검증할 때 네트워크 연결을 막고 시도 횟수를 셌으며, 0회였다. (JobKorea·Gemini·Slack·Gmail 모두 호출 안 함)
- 기존 history CSV 변경 여부: **변경 없음** (파일 체크섬 동일, 메모리의 `history_df`도 원본 그대로)
- 기존 report 변경 여부: **변경 없음** (`reports/ax_job_report.md` 체크섬 동일)

참고 — 네트워크 없이 추가로 확인한 것 (Notebook에는 저장하지 않음):
- `crawler.py`의 파싱 함수를 이전에 저장해 둔 실제 검색 결과 HTML에 적용한 결과가 history CSV와 같다. (수집 시각 제외)
- `gemini_client.build_prompt()`가 STEP 09 프롬프트와 같다. 가짜 client로 `summarize_with_gemini()`가 공고당 1회씩, 최대 2회만 호출하는 것을 확인했다.
- 가짜 서버로 `send_slack()` / `send_email()`이 1회만 보내고, 오류 메시지 속 Webhook URL·Gmail 주소·비밀번호를 `***`로 가리는 것을 확인했다.

- STEP 14 완료 여부: **완료 조건 충족** — src 7개 파일 생성, import 성공, 로컬 함수 검증 성공, 안전 키워드 8/8, 외부 요청 0회, CSV·보고서 변경 없음.
- 다음 공식 STEP: STEP 15 main.py 통합 (src 함수들을 전체 실행 순서로 연결)

# STEP 15. main.py 통합

## 작업 계획

STEP 14에서 만든 `src/` 함수들을 프로젝트 루트의 **`main.py`**에서 실행 순서대로 연결한다.

`main.py`의 역할:
- 설정 읽기 (`.env`, 경로, 검색어·개수·모델)
- `src` 함수 호출과 실행 순서 연결, 결과 전달
- 최소한의 상태 출력
- 크롤링 파싱, 키워드 정규식, 보고서 조립, Slack/Gmail 세부 구현은 **다시 만들지 않고** `src` 함수를 그대로 쓴다.

실행 순서 (`main()` 안):

| 순서 | 단계 | 사용하는 함수 |
|---|---|---|
| 1 | 환경변수 로드 (설정 여부만 출력) | `load_dotenv` |
| 2 | 채용공고 수집 | `collect_jobs()` |
| 3 | 전처리 | `clean_jobs()` |
| 4 | 기존 history 읽기 → 신규 공고 판별 → history 업데이트 | `find_new_jobs()`, `update_history()` |
| 5 | 관련 공고 필터링 | `filter_relevant_jobs()` |
| 6 | 기본 분석 | `analyze_jobs()` |
| 7 | Gemini 요약 | `summarize_with_gemini()` |
| 8 | 보고서 문자열 생성 | `create_report()` |
| 9 | Slack 메시지 생성 | `build_slack_message()` |
| 10 | 파일 저장 (history, 보고서) | `to_csv`, `save_report()` |
| 11 | Slack 발송 | `send_slack()` |
| 12 | Gmail 발송 | `send_email()` |

데이터 역할 (변수 이름으로 구분):
- `current_df` → 이번 수집 전체 (전처리 후)
- `new_jobs_df` → history와 비교한 신규 공고
- `filtered_df` → 관련 공고 (분석·Gemini 요약 대상)
- `report_jobs_df`, `notify_jobs_df` → 보고서·Slack 대상 (현재는 `current_df`, Notebook 흐름 유지)

`dry_run` 모드 — `main(dry_run=True)`:
- JobKorea 요청, Gemini 호출, Slack·Gmail 발송, history·report **파일 저장을 하지 않는다.**
- JobKorea 대신 기존 `jobs_history.csv`를 이번 수집 데이터로 사용해, 순서와 데이터 전달만 확인한다.
- 실제 전체 실행 `main(dry_run=False)`는 다음 STEP 16에서 검증한다.

이번 STEP에서 하지 않는 것:
- 실제 JobKorea 요청, Gemini 호출, Slack·Gmail 발송
- history·report 파일 저장
- STEP 16 실제 전체 실행, GitHub Actions

완료 조건:
- `main.py` 생성, `src` 함수 연결
- `main(dry_run=True)` 실행 성공 (로컬 데이터 흐름, 보고서·Slack 문자열 생성)
- 실제 외부 요청 0회, history·report 파일 변경 없음 (실행 전후 체크섬 비교), 비밀값 노출 없음

In [1]:
import sys
import hashlib
import inspect
from pathlib import Path

# ----- 0) main.py를 import할 수 있도록 프로젝트 루트를 경로에 추가 -----
project_root = Path.cwd()
if project_root.name == "notebooks":
    project_root = project_root.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))


# 파일 내용이 바뀌었는지 확인하기 위한 체크섬(MD5)
def file_checksum(path):
    return hashlib.md5(Path(path).read_bytes()).hexdigest()


watched_files = {
    "history CSV": project_root / "data" / "processed" / "jobs_history.csv",
    "report": project_root / "reports" / "ax_job_report.md",
}
checksums_before = {name: file_checksum(path) for name, path in watched_files.items()}

# ----- 1) main import -----
from main import main

print("main import 성공: True")
print("main() 시그니처:", inspect.signature(main))

# ----- 2) dry_run 실행 (외부 요청·파일 저장 없음) -----
print()
result = main(dry_run=True)

# ----- 3) 결과 확인 -----
print("\n=== dry_run 결과 ===")
for key in ["current_count", "history_count", "new_count", "updated_history_count",
            "filtered_count", "report_length", "slack_length", "gemini_calls", "slack_sent", "email_sent"]:
    print(f"{key}: {result[key]}")
print("analysis 회사별:", result["analysis"]["company_counts"])

# ----- 4) 파일이 바뀌지 않았는지 확인 (실행 전후 체크섬 비교) -----
print("\n=== 파일 변경 여부 ===")
for name, path in watched_files.items():
    print(f"{name} 체크섬 동일:", checksums_before[name] == file_checksum(path))

# ----- 5) main.py 구조 확인 -----
main_source = (project_root / "main.py").read_text(encoding="utf-8")
print("\n=== main.py 구조 ===")
print("def main(dry_run=False) 존재:", "def main(dry_run=False):" in main_source)
print('if __name__ == "__main__" 존재:', 'if __name__ == "__main__":' in main_source)
print("src 함수 import:", all(f"from src.{m} import" in main_source
                             for m in ["crawler", "preprocess", "analyzer", "gemini_client", "reporter", "notifier"]))
print("비밀값 형식 문자열 없음:", not any(s in main_source for s in ["hooks.slack.com/services/", "@gmail.com", "AIza"]))

main import 성공: True
main() 시그니처: (dry_run=False)

=== AX Job Agent (DRY RUN) ===
[1] 환경변수: GEMINI_API_KEY 설정됨, SLACK_WEBHOOK_URL 설정됨, GMAIL_USER 설정됨, GMAIL_APP_PASSWORD 설정됨
[2] 데이터 준비: history CSV를 입력으로 사용 (5건) — JobKorea 요청 생략
[3] 전처리 완료: 5건
[4] 신규 공고: 0건 (기존 이력 5건 → 업데이트 후 5건)
[5] 관련 공고: 5건
[6] 분석 완료: 전체 5건
[7] Gemini 요약: 생략 (DRY RUN)
[8] 보고서 문자열 생성 완료: 2662자
[9] Slack 메시지 생성 완료: 1398자
[DRY RUN] 외부 호출(Gemini·Slack·Gmail)과 파일 저장(history·report) 생략

=== dry_run 결과 ===
current_count: 5
history_count: 5
new_count: 0
updated_history_count: 5
filtered_count: 5
report_length: 2662
slack_length: 1398
gemini_calls: 0
slack_sent: False
email_sent: False
analysis 회사별: {'㈜NAVER': 2, 'GS리테일': 1, '에스코어': 1, '㈜슈프리마': 1}

=== 파일 변경 여부 ===
history CSV 체크섬 동일: True
report 체크섬 동일: True

=== main.py 구조 ===
def main(dry_run=False) 존재: True
if __name__ == "__main__" 존재: True
src 함수 import: True
비밀값 형식 문자열 없음: True

## 실행 결과 해석 / 분석 / 요약

- 셀이 에러 없이 실행되었다.
- `main.py` 생성: 프로젝트 루트 `chapter11/ax-job-agent/main.py`
- main import 성공 여부: **성공**, 시그니처 `main(dry_run=False)`
- `main(dry_run=True)` 실행: **성공** — 1~9단계가 순서대로 실행되고 `[DRY RUN]` 안내 후 결과(dict)를 반환했다.

| 단계 | dry_run 결과 |
|---|---|
| [1] 환경변수 | 4개 모두 "설정됨" (값은 출력하지 않음) |
| [2] 데이터 준비 | history CSV 5건을 이번 수집 데이터 대신 사용 (JobKorea 요청 생략) |
| [3] `clean_jobs` | 5건 → 5건 |
| [4] `find_new_jobs` / `update_history` | 신규 **0건** (같은 데이터끼리 비교), 이력 5건 → 5건 |
| [5] `filter_relevant_jobs` | 5건 통과 |
| [6] `analyze_jobs` | 전체 5건, 회사별 NAVER 2 / GS리테일 1 / 에스코어 1 / 슈프리마 1 (이전 STEP과 동일) |
| [7] `summarize_with_gemini` | 호출 안 함 (0회) |
| [8] `create_report` | 문자열 2662자 생성 (파일 저장 안 함) |
| [9] `build_slack_message` | 1398자 생성 (사용자 최종 Slack 형식, 발송 안 함) |

- 실제 JobKorea 요청 횟수: **0회**
- 실제 Gemini 호출 횟수: **0회**
- 실제 Slack 발송 횟수: **0회**
- 실제 Gmail 발송 횟수: **0회**
  - 검증할 때 네트워크 연결을 막고, `collect_jobs`·`summarize_with_gemini`·`send_slack`·`send_email`·`save_report`·`to_csv`가 불리면 기록되도록 해 두었다. 네트워크 연결 시도 0회, 함수 호출 0회였다. (감시 장치는 Notebook에 저장하지 않음)
- history CSV 체크섬 변경 여부: **변경 없음**
- report 체크섬 변경 여부: **변경 없음**
- 비밀값 노출 여부: **노출 없음** — 환경변수는 "설정됨/미설정"만 출력했고, `main.py`에 비밀값 형식 문자열이 없다.
- `main.py` 구조: `def main(dry_run=False)`, `if __name__ == "__main__":` 존재, 6개 src 모듈 import — HTML 파싱·정규식·보고서 조립·발송 세부 로직은 `main.py`에 다시 쓰지 않았다.
- 보고서 문자 수(2662자)가 STEP 11 보고서(3331자)와 다른 이유: dry_run에서는 Gemini를 호출하지 않아 5장(Gemini 분석 예시)이 "결과 없음"으로 들어가기 때문이다.

데이터 역할 (main.py 변수):
- `current_df` = 이번 수집 전체 / `new_jobs_df` = 신규 공고 / `filtered_df` = 관련 공고(분석·Gemini 대상)
- 보고서·Slack 대상(`report_jobs_df`, `notify_jobs_df`)은 **이번 수집 전체**로 두었다. Notebook(STEP 07-E ~ 12)이 현재 공고 전체를 대상으로 했기 때문이다.

STEP 16에서 확인해야 할 점:
- 실제 실행에서 Gemini는 `filtered_df`의 앞 2건(GS리테일, 에스코어)을 요약하고, 보고서 5장에는 **성공한 첫 응답**이 들어간다.
- 그런데 보고서 5장에는 "STEP 10에서 원본 데이터와 비교 검증했습니다" 문구가 고정되어 있다. 새 응답은 아직 검증하지 않았으므로 실제 실행 결과를 보고 표현을 확인해야 한다.

- STEP 15 완료 여부: **완료 조건 충족**
- 다음 공식 STEP: STEP 16 로컬 전체 실행 검증 (`main(dry_run=False)` 실제 실행)

# STEP 16. 로컬 전체 실행 검증

## 작업 계획

처음으로 `python main.py`를 **실제 실행 모드로 1회** 실행해서, 아래 전체 흐름이 로컬에서 끝까지 성공하는지 검증한다.

```text
JobKorea 수집 → 전처리 → history 비교/갱신 → 필터 → 분석 → Gemini → 보고서 저장 → Slack → Gmail
```

실행 전에 고친 점 — 보고서의 검증 문구 (`src/reporter.py`):
- 전에는 보고서 5장에 "STEP 10에서 원본 데이터와 비교 검증했습니다"가 고정되어 있었다.
- STEP 10에서 검증한 것은 **에스코어 1건의 당시 Gemini 응답**뿐이다. 이번 실행에서 새로 받는 응답은 아직 검증하지 않았다.
- 그래서 두 가지를 나눠 표시한다.
  - 5장 **[Gemini 생성 설명]**: "이번 실행에서 Gemini가 생성한 설명입니다. 이 응답은 아직 원본 데이터와 비교 검증하지 않았습니다."
  - 6장 **[과거 검증 기록]**: "STEP 10에서 에스코어 공고의 당시 Gemini 응답을 원본과 비교한 기록이며, 이번 실행의 새 응답을 검증했다는 뜻은 아닙니다."

실행 방법:
- 실제 실행은 **Terminal에서 `python main.py` 1회만** 한다. (자동 재시도 없음)
- 이 Notebook 코드 셀에서는 main.py를 다시 실행하지 않는다. 다시 실행하면 Gemini·Slack·Gmail이 또 호출되기 때문이다.
- 코드 셀은 실행 결과 파일(`jobs_history.csv`, `reports/ax_job_report.md`)을 **읽기만** 해서 검증한다.

유지한 동작:
- 보고서·Slack 대상은 이번 수집 전체(`current_df`), 신규 공고(`new_jobs_df`)는 개수 확인용 (Notebook 흐름 유지)
- Gemini는 관련 공고 앞 2건, 공고당 1회, 자동 재시도 없음 / Slack 1회 / Gmail 1회

실행 후 확인할 것:
- 수집 건수, 컬럼 9개, 결측, `job_url` 중복, 지원 시작일·마감일
- history 실행 전/후 건수, 신규 공고 수, 같은 URL 중복 누적 여부
- 보고서 8개 장, 이번 Gemini 결과와 과거 STEP 10 기록 구분, 일반화 금지 문구
- Slack·Gmail은 코드 결과(HTTP 200, SMTP 성공)만으로 끝내지 않고 **사람이 실제 도착을 확인**한다.

완료 조건:
- `python main.py`가 끝까지 성공
- 사용자가 Slack 채널과 Gmail 받은편지함에서 실제 도착을 확인 (확인 전까지 IN_PROGRESS)

In [1]:
# STEP 16 검증 — python main.py 실행 결과 파일을 "읽기만" 한다
# (이 셀에서는 main.py를 다시 실행하지 않는다: Gemini·Slack·Gmail 재호출 방지)
import hashlib
from pathlib import Path
import pandas as pd

project_root = Path.cwd()
if project_root.name == "notebooks":
    project_root = project_root.parent

history_path = project_root / "data" / "processed" / "jobs_history.csv"
report_path = project_root / "reports" / "ax_job_report.md"


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


# ----- 1) history CSV 확인 -----
history_df = pd.read_csv(history_path)
print("[history CSV]")
print("행 수:", len(history_df), "/ 컬럼 수:", history_df.shape[1])
print("컬럼:", history_df.columns.tolist())
print("결측 합계:", int(history_df.isna().sum().sum()))
print("job_url 중복:", history_df["job_url"].duplicated().sum())
print("수집 시각:", history_df["collected_at"].unique().tolist())
display(history_df[["company_name", "posted_date", "closing_date", "job_url"]])

# ----- 2) 보고서 확인 -----
report_text = report_path.read_text(encoding="utf-8")
section_titles = ["# AX 채용 분석 보고서", "## 1. 분석 기준", "## 2. 현재 수집 데이터 요약", "## 3. AX/AI 관련 공고 필터 결과",
                  "## 4. 주요 공고", "## 5. Gemini 분석 예시", "## 6. Gemini 검증 결과", "## 7. 제한 사항", "## 8. 다음 단계"]
print("\n[보고서]")
print("문자 수:", len(report_text))
print("제목 + 8개 장 포함:", all(t in report_text for t in section_titles))
print("이번 Gemini 결과 표현('이번 실행에서 Gemini가 생성한 설명'):", "이번 실행에서 Gemini가 생성한 설명" in report_text)
print("과거 검증 기록 표현('[과거 검증 기록]'):", "[과거 검증 기록]" in report_text)
print("잘못된 옛 문구('STEP 10에서 원본 데이터와 비교 검증했습니다') 없음:",
      "STEP 10에서 원본 데이터와 비교 검증했습니다" not in report_text)
print("일반화 금지 문구 포함:", "전체 채용시장 경향으로 일반화하면 안 됩니다" in report_text)
print("공고 URL 5개 포함:", all(url in report_text for url in history_df["job_url"]))
print("Gemini 호출 실패 기록:", [line for line in report_text.splitlines() if "Gemini 호출은 실패" in line][:2])

# ----- 3) 파일 체크섬 (실행 후 상태 기록) -----
print("\n[SHA256]")
print("history:", sha256(history_path))
print("report :", sha256(report_path))

[history CSV]
행 수: 5 / 컬럼 수: 9
컬럼: ['company_name', 'job_title', 'career', 'location', 'posted_date', 'closing_date', 'job_url', 'search_keyword', 'collected_at']
결측 합계: 0
job_url 중복: 0
수집 시각: ['2026-09-23 16:31:15']

,company_name,posted_date,closing_date,job_url
0,GS리테일,2026-09-21,2026-10-01 23:00,https://www.jobkorea.co.kr/Recruit/GI_Read/500...
1,에스코어,2026-07-01,2026-09-30 23:00,https://www.jobkorea.co.kr/Recruit/GI_Read/495...
2,㈜NAVER,2026-09-10,2026-09-29 10:00,https://www.jobkorea.co.kr/Recruit/GI_Read/499...
3,㈜슈프리마,2026-08-26,2026-10-25 23:00,https://www.jobkorea.co.kr/Recruit/GI_Read/498...
4,㈜NAVER,2026-09-10,2026-09-29 10:00,https://www.jobkorea.co.kr/Recruit/GI_Read/499...

[보고서]
문자 수: 3674
제목 + 8개 장 포함: True
이번 Gemini 결과 표현('이번 실행에서 Gemini가 생성한 설명'): True
과거 검증 기록 표현('[과거 검증 기록]'): True
잘못된 옛 문구('STEP 10에서 원본 데이터와 비교 검증했습니다') 없음: True
일반화 금지 문구 포함: True
공고 URL 5개 포함: True
Gemini 호출 실패 기록: ["- 에스코어 공고의 Gemini 호출은 실패했습니다. (ServerError: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}})"]

[SHA256]
history: 98e2e8ba892dc4b0d1ec29e9d00d857503aecc9acd3454070ba50a45e306ca5a
report : 868fb846ee90d4ccd5426dbefc92515b3405cf1501eaa2a314715f578b9728c4

## 실행 결과 해석 / 분석 / 요약

실행 명령 (Terminal, **1회**, 프로젝트 루트): `python main.py` → 종료 코드 **0** (12단계 모두 완료)

```text
[1] 환경변수: GEMINI_API_KEY 설정됨, SLACK_WEBHOOK_URL 설정됨, GMAIL_USER 설정됨, GMAIL_APP_PASSWORD 설정됨
[2] 데이터 준비: JobKorea 수집 5건
[3] 전처리 완료: 5건
[4] 신규 공고: 0건 (기존 이력 5건 → 업데이트 후 5건)
[5] 관련 공고: 5건
[6] 분석 완료: 전체 5건
[7] Gemini 요약: 호출 2회, 성공 1건
[8] 보고서 문자열 생성 완료: 3674자
[9] Slack 메시지 생성 완료: 1398자
[10] 저장 완료: data\processed\jobs_history.csv, reports\ax_job_report.md
[11] Slack 발송: HTTP 200 / ok
[12] Gmail 발송: 성공
```

| 항목 | 결과 |
|---|---|
| python main.py 실행 성공 여부 | **성공** (중간에 멈추지 않고 끝까지 실행) |
| 실제 수집 건수 | 5건 — 컬럼 9개, 결측 0, `job_url` 중복 0 |
| 수집된 공고 | 이전과 같은 5건 (GS리테일, 에스코어, NAVER 2, 슈프리마), 지원 시작일·마감일도 이전과 같음 |
| 신규 공고 건수 | **0건** (5건 모두 이미 history에 있음) |
| history 실행 전/후 | 5건 → 5건 (같은 URL 중복 누적 없음, `collected_at`만 `2026-09-23 14:00:39` → `16:31:15`로 갱신) |
| 관련 공고 수 | 5건 |
| Gemini 호출 수 | 2회 (자동 재시도 없음) |
| Gemini 성공 / 실패 | 성공 1 (GS리테일) / 실패 1 (에스코어: `ServerError 503 UNAVAILABLE` — 서버 과부하) |
| 보고서 저장 여부 | 저장됨 — `reports/ax_job_report.md` |
| 보고서 문자 수 | 3674자, 제목 + 8개 장 모두 포함 |
| Slack HTTP 결과 | 1회, **HTTP 200 / ok** |
| Gmail SMTP 결과 | 1회, **발송 성공** |
| 사용자 Slack 확인 | **필요** |
| 사용자 Gmail 확인 | **필요** |
| 비밀값 노출 여부 | **노출 없음** (출력은 설정 여부만, 보고서·history·코드에 비밀값 없음 확인) |

보고서 확인:
- 5장 **[Gemini 생성 설명]**: 이번 실행에서 받은 GS리테일 응답을 "이번 실행에서 Gemini가 생성한 설명, 아직 검증 전"으로 표시했다. 응답에서도 상세 업무·기술 스택·자격요건·우대사항은 "확인 불가"로 유지되었다.
- 6장 **[과거 검증 기록]**: STEP 10의 에스코어 당시 응답 검증 기록이라고 표시하고, 이번 새 응답을 검증했다는 뜻이 아님을 적었다.
- 옛 문구 "STEP 10에서 원본 데이터와 비교 검증했습니다"는 보고서에 없다.
- 7장: 에스코어 Gemini 호출 실패(503)가 제한 사항에 그대로 기록되었고, 일반화 금지 문구가 있다.
- 공고 URL 5개가 모두 들어 있다.

참고:
- 이번에는 STEP 09와 반대로 GS리테일이 성공하고 에스코어가 503으로 실패했다. 서버 상태에 따라 달라지는 일시적 오류이며, `main.py`는 이 실패 때문에 멈추지 않았다.
- 출력 맨 위 `Direct use of automatic function calling (AFC) ...`는 오류가 아니라 SDK 안내 메시지이다.
- Gemini 응답의 정확성 전체 검증은 이번 STEP의 목적이 아니다. (STEP 10과 다름)
- 보고서 8장 "다음 단계"는 `create_report()` 기본값인 "Slack / Gmail 발송"으로 적혀 있다. 이번 실행에서 이미 발송했으므로 문구가 실제와 맞지 않는다. (후속 수정 후보)
- 이 셀은 결과 파일을 읽기만 했다. (main.py 재실행 없음, 네트워크 연결 0회)

- STEP 16 현재 상태: **IN_PROGRESS** — `python main.py`는 끝까지 성공했다. 사용자가 Slack 채널과 Gmail 받은편지함에서 실제 도착을 확인하면 DONE으로 바꾼다.

# STEP 17. GitHub Actions 수동 실행

## 작업 계획

로컬에서 성공한 `python main.py`(STEP 16)를 이번에는 **GitHub Actions**에서 수동으로 1회 실행한다.

```text
GitHub Actions (수동 Run workflow)
→ Python 설치 → requirements.txt 설치 → GitHub Secrets를 환경변수로 주입
→ chapter11/ax-job-agent/main.py 실행 → 수집 → 분석 → Gemini → 보고서 → Slack → Gmail
```

GitHub Actions란:
- GitHub가 빌려주는 컴퓨터(runner)에서 정해 둔 명령을 자동으로 실행해 주는 기능이다.
- 실행 방법은 **workflow 파일**(YAML)에 적는다.
- 이번에는 사람이 버튼을 눌러 실행하는 **`workflow_dispatch`(수동 실행)**만 사용한다. 주간 자동 실행(`schedule`)은 STEP 18이다.

준비한 파일:

| 파일 | 위치 | 역할 |
|---|---|---|
| `ax-job-agent.yml` | 저장소 루트 `.github/workflows/` | workflow 정의 (이름: `AX Job Agent - Manual Run`) |
| `requirements.txt` | 프로젝트 루트 `chapter11/ax-job-agent/` | runner에 설치할 패키지 목록 |

- workflow 파일은 GitHub 규칙상 **저장소 루트**의 `.github/workflows/`에 있어야 한다. (프로젝트 폴더 안에 두면 동작하지 않는다)
- 실행 위치(`working-directory`)는 `chapter11/ax-job-agent`로 지정한다.

인증정보:
- GitHub에는 로컬 `.env`가 없다. (`.gitignore`로 제외되어 올라가지 않는다)
- 대신 **GitHub Repository Secrets**에 4개를 등록하고, workflow가 환경변수로 넣어 준다.
  - `GEMINI_API_KEY`, `SLACK_WEBHOOK_URL`, `GMAIL_USER`, `GMAIL_APP_PASSWORD`
- `main.py`의 `load_dotenv()`는 `.env`가 없으면 아무것도 하지 않고, 이미 들어온 환경변수를 그대로 쓴다. (로컬에서 확인)
- Secret 값은 파일·Notebook·문서·채팅에 쓰지 않는다. GitHub는 로그에 Secret 값이 나오면 `***`로 가린다.

알아 둘 점:
- runner에서 갱신된 history CSV와 보고서는 **실행이 끝나면 사라진다.** 이번 STEP에서는 자동 commit/push를 하지 않는다. (history를 어떻게 유지할지는 STEP 18에서 판단)
- runner는 GitHub의 서버 IP에서 실행되므로, JobKorea가 로컬과 다르게 응답(보안정책 페이지 등)할 수 있다. 그래도 우회하지 않고 결과를 그대로 기록한다.
- Gemini 503은 개별 공고 실패로 기록되고 파이프라인은 계속 진행된다. (자동 재시도 없음)
- workflow 권한은 읽기 전용(`contents: read`)이다.

이번 셀에서 하는 일:
- GitHub Actions를 실행하지 않는다. 준비한 파일을 **로컬에서 정적 검증**만 한다. (외부 요청 0회)

이번 STEP에서 하지 않는 것:
- `schedule`(주간 실행), STEP 18
- workflow에서 git commit/push
- Claude Code의 commit/push (사용자가 직접 올림)

완료 조건 (DONE):
- 사용자가 Secrets 4개 등록 → push → Run workflow **1회** 실행
- workflow 전체 성공, Slack·Gmail 실제 도착 확인, 로그에 비밀값 노출 없음

In [1]:
# STEP 17 정적 검증 — GitHub Actions를 실행하지 않고, 준비한 파일만 읽어서 확인한다 (외부 요청 없음)
import ast
import re
from pathlib import Path
import yaml

project_root = Path.cwd()
if project_root.name == "notebooks":
    project_root = project_root.parent
repo_root = project_root.parent.parent  # claude-code-agent-course/

workflow_path = repo_root / ".github" / "workflows" / "ax-job-agent.yml"
requirements_path = project_root / "requirements.txt"
main_path = project_root / "main.py"

# ----- 1) 파일 존재 -----
print("[파일 존재]")
for name, path in [("workflow", workflow_path), ("requirements.txt", requirements_path), ("main.py", main_path)]:
    print(f"{name}: {path.exists()}  ({path.relative_to(repo_root)})")

# ----- 2) workflow 내용 -----
workflow_text = workflow_path.read_text(encoding="utf-8")
workflow = yaml.safe_load(workflow_text)
triggers = workflow.get("on", workflow.get(True))  # YAML에서 on: 은 True로 읽힐 수 있다
job = workflow["jobs"]["run-agent"]
run_commands = [step.get("run", "") for step in job["steps"]]
secret_names = ["GEMINI_API_KEY", "SLACK_WEBHOOK_URL", "GMAIL_USER", "GMAIL_APP_PASSWORD"]

print("\n[workflow]")
print("YAML 문법 정상 (파싱 성공): True")
print("이름:", workflow["name"])
print("workflow_dispatch 존재:", "workflow_dispatch" in triggers)
# 주석 속 단어가 아니라 실제 트리거 설정(schedule: 키)이 있는지 확인한다
print("schedule 없음:", "schedule" not in triggers and not re.search(r"(?m)^\s*schedule\s*:", workflow_text))
print("권한:", workflow.get("permissions"))
print("runner:", job["runs-on"])
print("Python 버전:", [s["with"]["python-version"] for s in job["steps"] if "setup-python" in s.get("uses", "")])
print("working-directory:", job["defaults"]["run"]["working-directory"])
print("Secret 4개 주입:", all(job["env"].get(n) == f"${{{{ secrets.{n} }}}}" for n in secret_names))
print("python main.py 실행:", any(cmd.strip() == "python main.py" for cmd in run_commands))
print("pip install -r requirements.txt:", any("pip install -r requirements.txt" in cmd for cmd in run_commands))
print("git commit/push 명령 없음:", not re.search(r"git\s+(commit|push)", workflow_text))
print("write 권한 없음:", "write" not in str(workflow.get("permissions")))

# ----- 3) 비밀값 형식 문자열이 파일에 없는지 -----
secret_patterns = [r"hooks\.slack\.com/services/", r"AIza[0-9A-Za-z_\-]{10,}", r"[A-Za-z0-9._%+-]+@gmail\.com"]
checked_files = [workflow_path, requirements_path, main_path] + sorted((project_root / "src").glob("*.py"))
leaks = [str(p.name) for p in checked_files for pat in secret_patterns if re.search(pat, p.read_text(encoding="utf-8"))]
print("\n[비밀값 형식 문자열] 없음:", not leaks, leaks or "")

# ----- 4) main.py / src 의 외부 패키지 import가 requirements.txt에 모두 있는지 -----
import_to_package = {"pandas": "pandas", "requests": "requests", "bs4": "beautifulsoup4",
                     "dotenv": "python-dotenv", "google": "google-genai"}
imported = set()
for path in [main_path] + sorted((project_root / "src").glob("*.py")):
    for node in ast.walk(ast.parse(path.read_text(encoding="utf-8"))):
        if isinstance(node, ast.Import):
            imported |= {a.name.split(".")[0] for a in node.names}
        elif isinstance(node, ast.ImportFrom) and node.module and node.level == 0:
            imported.add(node.module.split(".")[0])
third_party = sorted(m for m in imported if m in import_to_package)
requirements = [line.strip() for line in requirements_path.read_text(encoding="utf-8").splitlines()
                if line.strip() and not line.startswith("#")]
print("\n[requirements.txt]", requirements)
print("코드의 외부 패키지 import:", third_party)
print("모두 requirements.txt에 있음:", all(import_to_package[m] in requirements for m in third_party))
print("Notebook 전용 패키지(jupyter, ipykernel) 제외:", not any(p in requirements for p in ["jupyter", "ipykernel"]))

# ----- 5) 보고서 8장 기본 문구 (함수 기본값만 확인, 보고서를 만들지 않음) -----
import sys
import inspect
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))
from src.reporter import create_report
print("\n[reporter 8장 기본 문구]", inspect.signature(create_report).parameters["next_step_text"].default)

[파일 존재]
workflow: True  (.github\workflows\ax-job-agent.yml)
requirements.txt: True  (chapter11\ax-job-agent\requirements.txt)
main.py: True  (chapter11\ax-job-agent\main.py)

[workflow]
YAML 문법 정상 (파싱 성공): True
이름: AX Job Agent - Manual Run
workflow_dispatch 존재: True
schedule 없음: True
권한: {'contents': 'read'}
runner: ubuntu-latest
Python 버전: ['3.14']
working-directory: chapter11/ax-job-agent
Secret 4개 주입: True
python main.py 실행: True
pip install -r requirements.txt: True
git commit/push 명령 없음: True
write 권한 없음: True

[비밀값 형식 문자열] 없음: True

[requirements.txt] ['pandas', 'requests', 'beautifulsoup4', 'python-dotenv', 'google-genai']
코드의 외부 패키지 import: ['bs4', 'dotenv', 'google', 'pandas', 'requests']
모두 requirements.txt에 있음: True
Notebook 전용 패키지(jupyter, ipykernel) 제외: True

[reporter 8장 기본 문구] GitHub Actions에서 자동 실행 검증

## 실행 결과 해석 / 분석 / 요약

- 셀이 에러 없이 실행되었다. (GitHub Actions 실행 없음, 외부 요청 **0회** — 네트워크 연결 시도 0회 확인)

정적 검증 결과:

| 항목 | 결과 |
|---|---|
| workflow 파일 | `.github/workflows/ax-job-agent.yml` (저장소 루트) — 존재, YAML 파싱 성공 |
| workflow 이름 | `AX Job Agent - Manual Run` |
| 트리거 | `workflow_dispatch` 있음, `schedule` **없음** |
| 권한 | `contents: read` (write 권한 없음) |
| runner / Python | `ubuntu-latest` / `3.14` |
| working-directory | `chapter11/ax-job-agent` |
| Secret 주입 | `GEMINI_API_KEY`, `SLACK_WEBHOOK_URL`, `GMAIL_USER`, `GMAIL_APP_PASSWORD` → `${{ secrets.이름 }}` 4개 |
| 실행 명령 | `pip install -r requirements.txt` → `python main.py` |
| git commit/push | 없음 |
| 비밀값 형식 문자열 | workflow, requirements.txt, main.py, src 전체에 없음 |
| requirements.txt | `pandas`, `requests`, `beautifulsoup4`, `python-dotenv`, `google-genai` — 코드가 import하는 외부 패키지 5개와 일치, jupyter·ipykernel 제외 |
| 보고서 8장 기본 문구 | "GitHub Actions에서 자동 실행 검증" (기존 "Slack / Gmail 발송"에서 수정) |

- 참고: 첫 실행에서는 "schedule 없음"이 False로 나왔다. workflow 주석("주간 schedule은 STEP 18에서 추가")에 들어 있는 단어를 검사가 잡았기 때문이다. 실제 트리거와 `schedule:` 키만 보도록 검사를 고친 뒤 True를 확인했다.
- `.env` 없는 환경: `load_dotenv()`는 `.env`가 없으면 오류 없이 넘어가고, 이미 주입된 환경변수를 그대로 둔다. (로컬에서 확인) → GitHub Secrets 값을 `os.getenv()`로 읽을 수 있다.
- history CSV·보고서: runner 안에서만 갱신되고 실행이 끝나면 사라진다. 이번 STEP에서는 자동 commit/push를 하지 않는다. (history를 계속 유지하는 방법은 STEP 18에서 판단)
- actions 버전: 이 저장소의 기존 workflow들과 같은 `actions/checkout@v4`, `actions/setup-python@v5`를 사용했다.

GitHub에서 실행할 때 달라질 수 있는 점:
- runner는 GitHub 서버 IP에서 실행되므로, JobKorea가 로컬과 다르게 보안정책 페이지를 줄 수 있다. 그 경우 `collect_jobs()`가 오류를 내며 workflow가 실패한다. **우회하지 않고** 결과를 그대로 기록한다.
- Gemini 503은 개별 공고 실패로 기록되고 파이프라인은 계속 진행된다. (자동 재시도 없음)

- STEP 17 현재 상태: **IN_PROGRESS** — workflow·requirements 준비 완료, GitHub Secrets 등록과 수동 실행 대기
- DONE 조건: Secrets 4개 등록 → push → Run workflow **1회** → workflow 성공 → Slack·Gmail 실제 도착 확인 → 로그에 비밀값 노출 없음