# STEP 01 — 개발환경 확인

## 작업 목표
실제 데이터 수집을 시작하기 전에, 지금 사용 중인 Notebook 실행 환경이 정상인지 확인합니다.

## 확인 항목
- Python 버전이 올바른지
- 운영체제(Platform) 정보
- `pandas`, `requests`, `BeautifulSoup` 라이브러리가 문제없이 import 되는지

## 완료 조건
- 아래 코드 셀이 모두 에러 없이 실행된다
- 커널이 `Python (ax-job-agent)`로 선택되어 있다
- 출력된 Python 경로가 `.venv` 안에 있는 것을 사람이 직접 확인한다

In [1]:
# Python 버전과 운영체제(Platform) 정보를 확인합니다.
import sys
import platform

print("Python:", sys.version)
print("Platform:", platform.platform())
print("Python 실행 경로:", sys.executable)

Python: 3.14.6 (tags/v3.14.6:c63aec6, Jun 10 2026, 10:26:10) [MSC v.1944 64 bit (AMD64)]
Platform: Windows-11-10.0.26200-SP0
Python 실행 경로: c:\dev\claude-code-agent-course\chapter11\ax-job-agent\.venv\Scripts\python.exe

In [4]:
# pandas, requests, BeautifulSoup이 정상적으로 import 되는지 확인합니다.
import pandas as pd
import requests
from bs4 import BeautifulSoup

print("pandas:", pd.__version__)
print("requests:", requests.__version__)
print("BeautifulSoup import: OK")

pandas: 3.0.6
requests: 2.34.2
BeautifulSoup import: OK

In [2]:
import sys
print(sys.executable)

c:\dev\claude-code-agent-course\chapter11\ax-job-agent\.venv\Scripts\python.exe

In [3]:
import sys
!{sys.executable} -m pip install pandas requests beautifulsoup4

Requirement already satisfied: pandas in c:\dev\claude-code-agent-course\chapter11\ax-job-agent\.venv\Lib\site-packages (3.0.6)
Requirement already satisfied: requests in c:\dev\claude-code-agent-course\chapter11\ax-job-agent\.venv\Lib\site-packages (2.34.2)
Requirement already satisfied: beautifulsoup4 in c:\dev\claude-code-agent-course\chapter11\ax-job-agent\.venv\Lib\site-packages (4.15.0)
Requirement already satisfied: numpy>=2.3.3 in c:\dev\claude-code-agent-course\chapter11\ax-job-agent\.venv\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\dev\claude-code-agent-course\chapter11\ax-job-agent\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\dev\claude-code-agent-course\chapter11\ax-job-agent\.venv\Lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\dev\claude-code-agent-course\chapter11\ax-job-agent\.venv\Lib\site-packages (from requests) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in c:\dev\claude-code-agent-course\chapter11\ax-job-agent\.venv\Lib\site-packages (from requests) (3.20)
Requirement already satisfied: urllib3<3,>=1.26 in c:\dev\claude-code-agent-course\chapter11\ax-job-agent\.venv\Lib\site-packages (from requests) (2.8.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\dev\claude-code-agent-course\chapter11\ax-job-agent\.venv\Lib\site-packages (from requests) (2026.7.22)
Requirement already satisfied: soupsieve>=1.6.1 in c:\dev\claude-code-agent-course\chapter11\ax-job-agent\.venv\Lib\site-packages (from beautifulsoup4) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\dev\claude-code-agent-course\chapter11\ax-job-agent\.venv\Lib\site-packages (from beautifulsoup4) (4.16.0)
Requirement already satisfied: six>=1.5 in c:\dev\claude-code-agent-course\chapter11\ax-job-agent\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

### 실행 결과 해석 / 분석 / 요약

- 현재 Jupyter Notebook은 프로젝트의 `.venv` 가상환경을 정상적으로 사용하고 있다.
- Python과 Windows 환경 정보가 정상적으로 출력되었다.
- pandas, requests, BeautifulSoup 라이브러리가 모두 정상적으로 import되었다.
- 따라서 STEP 01 개발환경 확인은 완료되었다.
- 다음 단계인 STEP 02 수집 데이터 명세로 진행할 수 있다.

### STEP 02. 수집 데이터 명세

### 작업 계획

이번 단계에서는 실제 크롤링 코드를 작성하기 전에
채용공고 데이터를 어떤 구조로 저장할지 먼저 정의한다.

기준:
- DataFrame의 한 행은 채용공고 1건을 의미한다.
- 처음에는 검색 결과에서 안정적으로 얻을 수 있는 정보만 사용한다.
- 아직 실제 웹페이지 수집은 하지 않는다.

In [1]:
import pandas as pd

columns_spec = pd.DataFrame({
    "컬럼명": [
        "company_name",
        "job_title",
        "career",
        "location",
        "posted_date",
        "closing_date",
        "job_url",
        "search_keyword",
        "collected_at"
    ],
    "의미": [
        "회사명",
        "공고 제목",
        "경력 조건",
        "근무 지역",
        "등록일",
        "마감일",
        "공고 URL",
        "공고를 발견한 검색어",
        "수집 시각"
    ]
})

columns_spec

              컬럼명           의미
0    company_name          회사명
1       job_title        공고 제목
2          career        경력 조건
3        location        근무 지역
4     posted_date          등록일
5    closing_date          마감일
6         job_url       공고 URL
7  search_keyword  공고를 발견한 검색어
8    collected_at        수집 시각

### 실행 결과 해석 / 분석 / 요약

- DataFrame의 한 행은 채용공고 1건을 의미한다.
- 초기 수집 컬럼은 회사명, 공고 제목, 경력 조건, 근무 지역, 등록일, 마감일, URL, 검색어, 수집 시각로 정의했다.
- 실제 크롤링 전에 데이터 구조를 먼저 정했기 때문에 이후 수집 결과가 이 기준에 맞는지 검증할 수 있다.
- 아직 실제 채용공고 수집은 수행하지 않았다.

### STEP 03. 채용공고 페이지 접근 테스트

### 작업 계획

이번 단계에서는 실제 데이터 수집 전에
채용공고 검색 페이지에 HTTP 요청이 가능한지 확인한다.

확인할 항목:
- HTTP 상태 코드
- 응답 Content-Type
- 응답 길이
- HTML 문서가 정상적으로 반환되는지

아직 여러 페이지를 반복 수집하지 않는다.

In [2]:
import requests

url = "https://www.jobkorea.co.kr/Search/?stext=AI"

response = requests.get(url, timeout=10)

print("상태 코드:", response.status_code)
print("Content-Type:", response.headers.get("Content-Type"))
print("응답 길이:", len(response.text))
print("HTML 시작 부분:")
print(response.text[:500])

상태 코드: 200
Content-Type: text/html
응답 길이: 3675
HTML 시작 부분:
<!DOCTYPE html><html lang="ko"><head><meta charset="utf-8" /><meta http-equiv="X-UA-Compatible" content="IE=edge" /><title>ë³´ìì ì±</title><style> *{margin:0;padding:0;box-sizing:border-box}body{font-family:'NanumGothic','ëëê³ ë','Malgun Gothic','ë§ì ê³ ë',sans-serif;background-color:#f8f9fa;line-height:1.6;color:#333;min-height:100vh;display:flex;flex-direction:column}.container{max-width:800px;margin:50px auto;padding:40px 20px;background-color:#fff;box-shadow:0 2px 10px rgba(0,

### 실행 결과 해석 / 분석 / 요약

- HTTP 요청 자체는 상태 코드 200으로 성공했다.
- Content-Type도 text/html로 확인되었다.
- 하지만 반환된 HTML은 실제 채용공고 검색 결과가 아니라 보안정책 페이지였다.
- 따라서 현재 requests 방식으로는 원하는 채용공고 데이터를 정상적으로 가져올 수 없다고 판단했다.
- 상태 코드 200만으로 정상적인 데이터 수집이라고 판단하면 안 된다는 점을 확인했다.
- 다음 단계에서는 사이트 제한을 우회하기보다 샘플 HTML 또는 CSV 사용 여부를 결정해야 한다.

### STEP 04. 소량 샘플 데이터 준비

### 작업 계획

STEP 03에서 잡코리아가 실제 검색결과 대신 보안정책 페이지를 반환했다.

이번 단계에서는 사이트 제한을 우회하지 않고,
파이프라인 학습을 계속하기 위해 소량의 샘플 채용공고 데이터를 만든다.

확인할 항목:
- 채용공고 5건 생성
- STEP 02에서 정의한 컬럼 사용
- DataFrame 생성 여부 확인

주의:
- 아래 데이터는 실제 수집 결과가 아니라 실습용 샘플 데이터이다.

In [3]:
import pandas as pd

sample_jobs = [
    {
        "company_name": "회사A",
        "job_title": "AI Engineer",
        "career": "신입",
        "location": "서울",
        "posted_date": "2026-09-20",
        "closing_date": "2026-10-10",
        "job_url": "https://example.com/job/1",
        "search_keyword": "AI",
        "collected_at": "2026-09-23"
    },
    {
        "company_name": "회사B",
        "job_title": "데이터 분석가",
        "career": "경력 1~3년",
        "location": "경기",
        "posted_date": "2026-09-21",
        "closing_date": "2026-10-15",
        "job_url": "https://example.com/job/2",
        "search_keyword": "데이터 분석",
        "collected_at": "2026-09-23"
    },
    {
        "company_name": "회사C",
        "job_title": "AX Engineer",
        "career": "신입/경력",
        "location": "서울",
        "posted_date": "2026-09-21",
        "closing_date": "2026-10-20",
        "job_url": "https://example.com/job/3",
        "search_keyword": "AX",
        "collected_at": "2026-09-23"
    },
    {
        "company_name": "회사D",
        "job_title": "LLM 서비스 개발자",
        "career": "경력 3년 이상",
        "location": "서울",
        "posted_date": "2026-09-22",
        "closing_date": "2026-10-12",
        "job_url": "https://example.com/job/4",
        "search_keyword": "LLM",
        "collected_at": "2026-09-23"
    },
    {
        "company_name": "회사E",
        "job_title": "Machine Learning Engineer",
        "career": "신입",
        "location": "부산",
        "posted_date": "2026-09-22",
        "closing_date": "2026-10-18",
        "job_url": "https://example.com/job/5",
        "search_keyword": "Machine Learning",
        "collected_at": "2026-09-23"
    }
]

df_jobs = pd.DataFrame(sample_jobs)

print("데이터 크기:", df_jobs.shape)
display(df_jobs)

데이터 크기: (5, 9)

,company_name,job_title,career,location,posted_date,closing_date,job_url,search_keyword,collected_at
0,회사A,AI Engineer,신입,서울,2026-09-20,2026-10-10,https://example.com/job/1,AI,2026-09-23
1,회사B,데이터 분석가,경력 1~3년,경기,2026-09-21,2026-10-15,https://example.com/job/2,데이터 분석,2026-09-23
2,회사C,AX Engineer,신입/경력,서울,2026-09-21,2026-10-20,https://example.com/job/3,AX,2026-09-23
3,회사D,LLM 서비스 개발자,경력 3년 이상,서울,2026-09-22,2026-10-12,https://example.com/job/4,LLM,2026-09-23
4,회사E,Machine Learning Engineer,신입,부산,2026-09-22,2026-10-18,https://example.com/job/5,Machine Learning,2026-09-23

### 실행 결과 해석 / 분석 / 요약

- 실습용 채용공고 5건이 정상적으로 DataFrame으로 생성되었다.
- 각 행은 채용공고 1건을 의미한다.
- STEP 02에서 정의한 9개 컬럼이 모두 포함되어 있다.
- 현재 데이터는 실제 크롤링 결과가 아니라 이후 전처리와 분석을 연습하기 위한 샘플 데이터이다.
- 다음 단계에서는 컬럼 구조, 결측값, 중복 여부를 확인한다.

### STEP 05. DataFrame 기본 구조 확인

### 작업 계획

STEP 04에서 만든 `df_jobs`의 기본 구조가 예상대로 만들어졌는지 확인한다.

확인할 항목:
- 행과 열의 개수
- 컬럼 목록
- 상위 데이터
- 결측값
- `job_url` 기준 중복 여부

아직 데이터를 수정하거나 전처리하지 않는다.
이번 단계는 현재 상태를 확인하는 단계이다.

In [4]:
print("데이터 크기:", df_jobs.shape)

print("\n컬럼 목록:")
print(df_jobs.columns.tolist())

print("\n상위 5개 데이터:")
display(df_jobs.head())

print("\n결측값 개수:")
display(df_jobs.isna().sum())

print("\njob_url 중복 개수:")
print(df_jobs.duplicated(subset=["job_url"]).sum())

데이터 크기: (5, 9)

컬럼 목록:
['company_name', 'job_title', 'career', 'location', 'posted_date', 'closing_date', 'job_url', 'search_keyword', 'collected_at']

상위 5개 데이터:

,company_name,job_title,career,location,posted_date,closing_date,job_url,search_keyword,collected_at
0,회사A,AI Engineer,신입,서울,2026-09-20,2026-10-10,https://example.com/job/1,AI,2026-09-23
1,회사B,데이터 분석가,경력 1~3년,경기,2026-09-21,2026-10-15,https://example.com/job/2,데이터 분석,2026-09-23
2,회사C,AX Engineer,신입/경력,서울,2026-09-21,2026-10-20,https://example.com/job/3,AX,2026-09-23
3,회사D,LLM 서비스 개발자,경력 3년 이상,서울,2026-09-22,2026-10-12,https://example.com/job/4,LLM,2026-09-23
4,회사E,Machine Learning Engineer,신입,부산,2026-09-22,2026-10-18,https://example.com/job/5,Machine Learning,2026-09-23

결측값 개수:

company_name      0
job_title         0
career            0
location          0
posted_date       0
closing_date      0
job_url           0
search_keyword    0
collected_at      0
dtype: int64

job_url 중복 개수:
0

### 실행 결과 해석 / 분석 / 요약

- DataFrame의 크기는 5행 × 9열이다.
- STEP 02에서 정의한 9개 컬럼이 모두 존재한다.
- 상위 데이터를 확인한 결과 각 행이 채용공고 1건 형태로 정상적으로 구성되어 있다.
- 모든 컬럼의 결측값은 0개이다.
- `job_url` 기준 중복 공고는 0건이다.
- 현재 샘플 데이터의 기본 구조에는 이상이 없으며, 다음 단계에서 데이터 타입 확인과 전처리를 진행할 수 있다.

### STEP 06. 전처리 / 중복 제거

### 작업 계획

STEP 05에서 `df_jobs`의 기본 구조에 이상이 없음을 확인했다.
이번 단계에서는 이후 분석에 사용할 수 있도록 데이터를 정리(전처리)한다.

할 일:
- 전처리 전 `df_jobs`의 크기(shape)와 데이터 타입(dtypes) 확인
- 날짜 컬럼(`posted_date`, `closing_date`, `collected_at`)을 datetime 타입으로 변환
  - `pd.to_datetime(..., errors="coerce")` 사용 → 날짜로 바꿀 수 없는 값은 `NaT`(날짜 결측값)가 된다
- 문자열 컬럼(`company_name`, `job_title`, `career`, `location`, `job_url`, `search_keyword`)의 앞뒤 공백 제거
- `job_url` 기준 중복 제거
- 전처리 후 shape / dtypes / 결측값 / `job_url` 중복 개수 재확인

이번 단계에서 하지 않는 것:
- STEP 07 신규 공고 판별
- 실제 크롤링 재시도, Gemini API, Slack / Gmail

완료 조건:
- 날짜 컬럼 3개의 dtype이 datetime으로 바뀐다
- 날짜 변환 후 결측값(`NaT`)이 새로 생기지 않는다
- `job_url` 중복 개수가 0이다

In [1]:
# ----- 1) 전처리 전 상태 확인 -----
shape_before = df_jobs.shape
print("[전처리 전] 데이터 크기:", shape_before)
print("\n[전처리 전] 데이터 타입:")
display(df_jobs.dtypes)

# ----- 2) 날짜 컬럼을 datetime 타입으로 변환 -----
date_columns = ["posted_date", "closing_date", "collected_at"]
for col in date_columns:
    # errors="coerce": 날짜로 바꿀 수 없는 값은 에러를 내지 않고 NaT(날짜 결측값)로 바꾼다
    df_jobs[col] = pd.to_datetime(df_jobs[col], errors="coerce")

# ----- 3) 문자열 컬럼의 앞뒤 공백 제거 -----
text_columns = ["company_name", "job_title", "career", "location", "job_url", "search_keyword"]
for col in text_columns:
    # .str.strip(): " 회사A " → "회사A" 처럼 앞뒤 공백만 제거한다
    df_jobs[col] = df_jobs[col].str.strip()

# ----- 4) job_url 기준 중복 제거 -----
# 같은 job_url이 여러 번 있으면 첫 번째 행만 남긴다
df_jobs = df_jobs.drop_duplicates(subset=["job_url"])

# ----- 5) 전처리 후 상태 확인 -----
print("\n[전처리 후] 데이터 크기:", df_jobs.shape)
print("제거된 행 수:", shape_before[0] - df_jobs.shape[0])

print("\n[전처리 후] 데이터 타입:")
display(df_jobs.dtypes)

print("\n[전처리 후] 결측값 개수:")
display(df_jobs.isna().sum())

print("\n[전처리 후] job_url 중복 개수:")
print(df_jobs.duplicated(subset=["job_url"]).sum())

[전처리 전] 데이터 크기: (5, 9)

[전처리 전] 데이터 타입:

company_name      str
job_title         str
career            str
location          str
posted_date       str
closing_date      str
job_url           str
search_keyword    str
collected_at      str
dtype: object

[전처리 후] 데이터 크기: (5, 9)
제거된 행 수: 0

[전처리 후] 데이터 타입:

company_name                 str
job_title                    str
career                       str
location                     str
posted_date       datetime64[us]
closing_date      datetime64[us]
job_url                      str
search_keyword               str
collected_at      datetime64[us]
dtype: object

[전처리 후] 결측값 개수:

company_name      0
job_title         0
career            0
location          0
posted_date       0
closing_date      0
job_url           0
search_keyword    0
collected_at      0
dtype: int64

[전처리 후] job_url 중복 개수:
0

### 실행 결과 해석 / 분석 / 요약

- 셀이 에러 없이 실행되었다.
- 전처리 전 데이터 크기는 5행 × 9열이고, 9개 컬럼이 모두 문자열(`str`) 타입이었다.
  - 즉 날짜처럼 보이는 `"2026-09-20"`도 pandas 입장에서는 그냥 글자였다.
- 날짜 컬럼 3개(`posted_date`, `closing_date`, `collected_at`)는 `datetime64[us]` 타입으로 변환되었다.
  - 이제 날짜 비교, 마감일까지 남은 기간 계산 같은 날짜 연산이 가능하다.
  - 변환 후 결측값이 0개이므로 `errors="coerce"` 때문에 `NaT`가 된 값은 없다. 즉 모든 날짜가 정상적으로 변환되었다.
- 문자열 컬럼 6개의 앞뒤 공백 제거를 적용했다. 샘플 데이터는 원래 공백이 없어서 값이 달라지지는 않았지만, 실제 수집 데이터에 대비한 기본 정리 절차를 갖추었다.
- `job_url` 기준 중복 제거 결과 제거된 행은 0개였고, 전처리 후 크기도 5행 × 9열로 그대로이다.
- 전처리 후 모든 컬럼의 결측값은 0개, `job_url` 중복 개수도 0개이다.
- 참고: pandas 3.x에서는 문자열 컬럼의 dtype이 `object` 대신 `str`로 표시된다.
- 결론: 전처리 / 중복 제거가 정상 완료되었으며, 다음 단계인 STEP 07 신규 공고 판별로 진행할 수 있다.

### STEP 07. 신규 공고 판별

### 작업 계획

STEP 06에서 전처리를 마친 `df_jobs`(공고 5건)를 이전 실행 이력과 비교해
**이번에 처음 나타난 공고(신규 공고)**만 골라낸다.

판별 기준:
- 1차 기준은 `job_url`이다. (URL이 같으면 같은 공고로 본다)
- 이전 이력에 있던 URL → 기존 공고
- 이전 이력에 없던 URL → 신규 공고

이전 실행 이력:
- 아직 실제 이력 파일이나 데이터베이스가 없으므로, 간단한 샘플 목록 `previous_urls`를 직접 만든다.
- 이전 이력에 `https://example.com/job/1`, `https://example.com/job/2`가 있었다고 가정한다.

확인할 항목:
- 이전 이력 URL 수
- 전체 공고 수 / 기존 공고 수 / 신규 공고 수
- 신규 공고의 `company_name`, `job_title`, `job_url`

이번 단계에서 하지 않는 것:
- STEP 08 기본 분석
- CSV 저장
- 실제 크롤링, Gemini API, Slack / Gmail

완료 조건:
- 기존 공고 수 + 신규 공고 수 = 전체 공고 수
- 신규 공고가 `new_jobs` DataFrame으로 만들어진다
- 신규 공고 목록에 이전 이력 URL이 들어 있지 않다

In [1]:
# ----- 1) 이전 실행 이력(샘플) 만들기 -----
# 실제로는 이전 실행 때 저장해 둔 URL 목록을 불러와야 하지만,
# 지금은 연습을 위해 "이전에 이미 봤던 공고 URL" 2개를 직접 적어 둔다.
previous_urls = [
    "https://example.com/job/1",
    "https://example.com/job/2",
]
print("이전 이력 URL 수:", len(previous_urls))

# ----- 2) job_url이 이전 이력에 있는지 비교하기 -----
# isin(): 각 행의 job_url이 previous_urls 목록 안에 "들어 있는지" 한 번에 검사한다.
#         들어 있으면 True(기존 공고), 없으면 False(신규 공고)가 된다.
#         for 문으로 한 행씩 비교하지 않아도 되어서 간단하고 빠르다.
is_existing = df_jobs["job_url"].isin(previous_urls)

# ----- 3) 기존 공고 / 신규 공고 구분하기 -----
existing_jobs = df_jobs[is_existing]   # True인 행만 → 기존 공고
new_jobs = df_jobs[~is_existing]       # ~ 는 True/False를 뒤집는다 → 신규 공고

# ----- 4) 결과 출력 -----
print("\n전체 공고 수:", len(df_jobs))
print("기존 공고 수:", len(existing_jobs))
print("신규 공고 수:", len(new_jobs))

print("\n신규 공고 목록:")
display(new_jobs[["company_name", "job_title", "job_url"]])

이전 이력 URL 수: 2

전체 공고 수: 5
기존 공고 수: 2
신규 공고 수: 3

신규 공고 목록:

  company_name                  job_title                    job_url
2          회사C                AX Engineer  https://example.com/job/3
3          회사D                LLM 서비스 개발자  https://example.com/job/4
4          회사E  Machine Learning Engineer  https://example.com/job/5

### 실행 결과 해석 / 분석 / 요약

- 셀이 에러 없이 실행되었다.
- 이전 실행 이력(`previous_urls`)에는 URL 2개(`job/1`, `job/2`)가 있다.
- 현재 `df_jobs`의 전체 공고는 5건이다.
- `isin()`으로 비교한 결과:
  - 기존 공고(이전 이력에 있던 URL): 2건 → 회사A, 회사B
  - 신규 공고(이전 이력에 없던 URL): 3건 → 회사C, 회사D, 회사E
- 기존 2건 + 신규 3건 = 전체 5건이므로 빠지거나 겹친 공고가 없다.
- `new_jobs`에는 `job/3`, `job/4`, `job/5`만 들어 있고, 이전 이력 URL은 포함되지 않았다.
- 참고: 신규 공고의 행 번호(index)가 2, 3, 4로 남아 있는 것은 원래 `df_jobs`에서의 위치를 그대로 유지했기 때문이며 문제는 아니다.
- 한계: 지금의 `previous_urls`는 직접 만든 샘플이다. 실제 운영에서는 이번 실행의 URL을 저장해 두었다가 다음 실행 때 불러와야 한다. (저장은 이후 단계에서 진행)
- 결론: `job_url` 기준 신규 공고 판별이 정상 동작하며, 다음 단계인 STEP 08 기본 분석으로 진행할 수 있다.

### STEP 07-A. 실제 JobKorea 소량 크롤링 검증

### 작업 계획

STEP 04~07은 직접 만든 **샘플 데이터**로 파이프라인을 연습했다. (이 기록은 그대로 보존한다)
이번 단계에서는 샘플이 아니라 **실제 JobKorea 검색 결과 웹페이지**에서 채용공고를 소량 읽어 올 수 있는지 검증한다.

사용 URL:
- `https://www.jobkorea.co.kr/Search/?stext=ax&tabType=recruit` (검색어 `ax`, 1페이지)

처음부터 여러 페이지를 수집하지 않는 이유:
- 한 페이지에서 정확히 읽는 방법이 확인되지 않았는데 페이지를 늘리면, 틀린 데이터만 많아진다.
- 짧은 시간에 요청을 많이 보내면 사이트에 부담을 주고 차단될 수 있다.
- 그래서 **검색어 1개 · 페이지 1개 · 최대 5건**만 읽는다.

상태 코드 200만으로 성공 판단을 하면 안 되는 이유:
- STEP 03에서 상태 코드는 200이었지만, 실제로는 **보안정책(접속 제한) 페이지**가 돌아왔다.
- 그래서 상태 코드와 함께 Content-Type, 응답 길이, HTML `title`, "채용공고"/"AX" 문자열 포함 여부를 같이 확인한다.
- 기본 요청이 보안정책 페이지를 받으면, 일반 브라우저 User-Agent 헤더를 붙여 **딱 1회만** 다시 확인한다. (반복 재시도·우회 기법은 사용하지 않는다)

HTML 구조를 먼저 확인해야 하는 이유:
- 브라우저 화면과 HTML 코드 구조는 다를 수 있어서, 선택자를 추측하면 엉뚱한 값을 읽을 수 있다.
- 이번에는 실제 응답 HTML에서 공고 링크(`/Recruit/GI_Read/번호`)를 찾고, 그 부모 요소를 거슬러 올라가
  공고 1건을 감싸는 반복 블록(`div[data-sentry-component="CardJob"]`)을 먼저 확인한 뒤 선택자를 정했다.

날짜 데이터를 가져오는 방법:
- 화면 카드 HTML에는 등록일/마감일 **텍스트가 직접 들어 있지 않다.**
- 하지만 같은 HTML 응답 안의 `<script>`(Next.js가 심어 둔 `self.__next_f.push(...)` 데이터)에 공고별 JSON이 들어 있고, 여기에 날짜가 있다.
- 이 프로젝트에서는 **지원 제출 기간**이 중요하므로 다음 값을 사용한다.
  - 지원 제출 시작일 → `applicationPeriod.start`
  - 지원 제출 마감일 → `applicationPeriod.end`
- `createdAt`은 공고가 사이트에 **등록된 시각**이라 지원 기간과 다를 수 있으므로 사용하지 않는다.
  (예: 에스코어 공고는 `createdAt`=07-15, `applicationPeriod.start`=07-01)
- 카드 순서와 JSON 순서에 기대지 않고, **공고 ID**(`job_url` 끝의 숫자)로 카드와 JSON을 짝지어 날짜를 붙인다.

컬럼 의미 정의 (컬럼명은 STEP 02 명세를 유지):
- `posted_date` = 이번 프로젝트에서는 **지원 제출 시작일**을 의미한다. (`applicationPeriod.start`의 날짜 부분, 예: `2026-09-21`)
- `closing_date` = **지원 제출 마감일** (`applicationPeriod.end`의 날짜 + 시:분, 예: `2026-10-01 23:00`)
- 참고: 이름과 의미를 맞추기 위해, 이후 전체 리팩터링 단계에서 `application_start_date` / `application_end_date`로 바꿀 수 있다.
- `search_keyword` = `ax`, `collected_at` = 이번에 페이지를 받아 온 시각

추출 결과를 사람이 브라우저와 비교해야 하는 이유:
- 코드가 에러 없이 실행돼도 다른 칸의 글자를 읽었을 수 있다.
- 출력된 제목·회사명·지역·경력·날짜·URL을 브라우저 화면과 직접 비교해야 "제대로 읽었다"고 판단할 수 있다.

이번 단계에서 하지 않는 것:
- 여러 페이지 / 여러 검색어 / 상세 페이지 반복 요청
- DataFrame 생성(다음 STEP 07-B에서 확인), CSV·JSON 저장, 신규 공고 판별, 분석
- Gemini API, Slack / Gmail

성공 기준:
- 실제 검색 결과 HTML을 받았음을 확인한다
- 반복되는 공고 블록을 확인한다
- 최대 5건을 추출한다
- 최소 `company_name` 또는 `job_title`을 확인한다
- 가능하면 `job_url`도 확인한다
- `posted_date` / `closing_date`에 `applicationPeriod.start` / `end` 값이 들어간다
- 브라우저 화면과 비교할 수 있는 형태로 출력한다

In [1]:
import re
import json
from datetime import datetime

import requests
from bs4 import BeautifulSoup

url = "https://www.jobkorea.co.kr/Search/?stext=ax&tabType=recruit"
search_keyword = "ax"
MAX_JOBS = 5  # 이번 STEP에서는 최대 5건만 읽는다


# 응답이 "실제 검색 결과"인지 확인하는 함수
# 상태 코드 200이어도 보안정책(접속 제한) 페이지일 수 있으므로 title과 본문 문자열까지 확인한다
def check_response(response):
    response.encoding = "utf-8"  # 한글이 깨지지 않도록 인코딩 지정
    soup = BeautifulSoup(response.text, "html.parser")
    title = soup.title.get_text(strip=True) if soup.title else None
    is_blocked = "보안정책" in response.text
    is_search_result = ("채용공고" in (title or "")) and ("AX" in response.text.upper())

    print("  상태 코드:", response.status_code)
    print("  Content-Type:", response.headers.get("Content-Type"))
    print("  응답 길이:", len(response.text))
    print("  HTML title:", title)
    print("  보안정책 페이지 여부:", is_blocked)
    print("  실제 검색 결과 여부:", is_search_result)
    return soup, is_search_result


# ----- 1) 가장 단순한 방식으로 1차 요청 -----
print("[1차 요청] requests.get() 기본 요청")
response = requests.get(url, timeout=10)
response.raise_for_status()
soup, is_search_result = check_response(response)

# ----- 2) 1차 요청이 보안정책 페이지일 때만, 일반 브라우저 User-Agent로 1회 추가 테스트 -----
used_user_agent = False
if not is_search_result:
    print("\n[2차 요청] 일반 브라우저 User-Agent 헤더를 붙여 1회만 다시 요청")
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                      "(KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"
    }
    response = requests.get(url, headers=headers, timeout=10)
    response.raise_for_status()
    soup, is_search_result = check_response(response)
    used_user_agent = True

# 수집 시각: 이번에 페이지를 받아 온 시각
collected_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

# ----- 3) 실제 검색 결과가 아니면 여기서 중단 (재시도하지 않는다) -----
jobs = []
if not is_search_result:
    print("\n실제 검색 결과 HTML을 받지 못했습니다. 추출을 진행하지 않습니다.")
else:
    # ----- 4) Next.js script 안에서 공고 목록 JSON 찾기 -----
    # 화면 카드에는 날짜 텍스트가 없지만, 같은 HTML 안의 <script>에
    # self.__next_f.push([1, "...문자열..."]) 형태로 공고 데이터(JSON)가 들어 있다
    period_by_id = {}  # 공고 ID별 applicationPeriod 매핑: {"50032017": {"start": ..., "end": ...}}
    for script in soup.find_all("script"):
        text = script.string or ""
        if "applicationPeriod" not in text:
            continue
        match = re.match(r'self\.__next_f\.push\(\[1,(".*")\]\)', text, re.S)
        if not match:
            continue
        # 따옴표로 감싼 JavaScript 문자열 → 일반 문자열로 풀기
        payload = json.loads(match.group(1))
        # 문자열 안에서 공고 목록 "content": [ {...}, {...} ] 부분을 찾아 JSON으로 읽기
        for found in re.finditer(r'"content":\[\{"id":', payload):
            start_index = found.start() + len('"content":')
            content, _ = json.JSONDecoder().raw_decode(payload, start_index)
            # 공고 ID별 applicationPeriod 매핑 만들기
            for item in content:
                period_by_id[item["id"]] = item.get("applicationPeriod")
    print("\nJSON에서 찾은 공고 날짜 데이터 수:", len(period_by_id))

    # ----- 5) 반복되는 채용공고 블록 찾기 -----
    # 실제 HTML 확인 결과, 공고 1건은 data-sentry-component="CardJob" 인 div 하나로 감싸져 있었다
    cards = soup.select('div[data-sentry-component="CardJob"]')
    print("찾은 채용공고 후보(CardJob) 수:", len(cards))

    # ----- 6) 최대 5건만 필드 추출 -----
    for card in cards[:MAX_JOBS]:
        # 공고 제목 링크: data-sentry-component="Title" 인 <a>
        title_link = card.select_one('a[data-sentry-component="Title"]')
        # 회사명: 제목 링크 바로 다음에 나오는 <a>(같은 공고 URL) 안의 첫 번째 <span>
        company_link = title_link.find_next("a") if title_link else None
        company_tag = company_link.select_one("span") if company_link else None
        # 근무 지역: 첫 번째 GrayChip(📍 아이콘이 있는 칩) 안의 텍스트
        location_tag = card.select_one('[data-sentry-component="GrayChip"] span.truncate')
        # 경력 조건: "경력3년↑", "신입" 등이 들어 있는 작은 글씨 span
        career_tag = card.select_one("span.flex-shrink-0.text-typo-c1-13")

        # 공고 URL: 뒤에 붙은 ?Oem_Code=...&listno=... 는 검색 위치 추적용이라 제거하고 기본 주소만 남긴다
        job_url = title_link["href"].split("?")[0] if title_link else None

        # 화면 카드와 같은 ID의 날짜 붙이기 (순서가 아니라 공고 ID로 매칭한다)
        # 예: .../GI_Read/50032017 → job_id = "50032017"
        job_id = job_url.rsplit("/", 1)[-1] if job_url else None
        period = period_by_id.get(job_id) or {}
        start_raw = period.get("start")  # 예: "2026-09-21T00:00:00+09:00"
        end_raw = period.get("end")      # 예: "2026-10-01T23:00:00+09:00"

        jobs.append({
            "company_name": company_tag.get_text(strip=True) if company_tag else None,
            "job_title": title_link.get_text(strip=True) if title_link else None,
            "career": career_tag.get_text(strip=True) if career_tag else None,
            "location": location_tag.get_text(strip=True) if location_tag else None,
            # posted_date = 지원 제출 시작일 (applicationPeriod.start의 날짜 부분만)
            "posted_date": start_raw[:10] if start_raw else None,
            # closing_date = 지원 제출 마감일 (applicationPeriod.end의 날짜 + 시:분)
            "closing_date": end_raw[:16].replace("T", " ") if end_raw else None,
            "job_url": job_url,
            "search_keyword": search_keyword,
            "collected_at": collected_at,
        })

        # 원본 값도 함께 보여 주어 잘라 낸 결과와 비교할 수 있게 한다
        print(f"  ID {job_id} 원본 applicationPeriod: start={start_raw}, end={end_raw}")

# ----- 7) 결과 출력 (브라우저 화면과 비교용) -----
print("\nUser-Agent 추가 요청 여부:", used_user_agent)
print("실제 출력한 공고 수:", len(jobs))
for i, job in enumerate(jobs, start=1):
    print(f"\n[{i}]")
    for key, value in job.items():
        print(f"  {key}: {value}")

[1차 요청] requests.get() 기본 요청
  상태 코드: 200
  Content-Type: text/html
  응답 길이: 3186
  HTML title: 보안정책
  보안정책 페이지 여부: True
  실제 검색 결과 여부: False

[2차 요청] 일반 브라우저 User-Agent 헤더를 붙여 1회만 다시 요청

  상태 코드: 200
  Content-Type: text/html; charset=utf-8
  응답 길이: 347641
  HTML title: 'ax' 관련 📢 채용공고 | 총 888건의 검색결과
  보안정책 페이지 여부: False
  실제 검색 결과 여부: True

JSON에서 찾은 공고 날짜 데이터 수: 31
찾은 채용공고 후보(CardJob) 수: 20
  ID 50032017 원본 applicationPeriod: start=2026-09-21T00:00:00+09:00, end=2026-10-01T23:00:00+09:00
  ID 49589368 원본 applicationPeriod: start=2026-07-01T00:00:00+09:00, end=2026-09-30T23:00:00+09:00
  ID 49976564 원본 applicationPeriod: start=2026-09-10T00:00:00+09:00, end=2026-09-29T10:00:00+09:00
  ID 49858859 원본 applicationPeriod: start=2026-08-26T00:00:00+09:00, end=2026-10-25T23:00:00+09:00
  ID 49976547 원본 applicationPeriod: start=2026-09-10T00:00:00+09:00, end=2026-09-29T10:00:00+09:00

User-Agent 추가 요청 여부: True
실제 출력한 공고 수: 5

[1]
  company_name: GS리테일
  job_title: [GS리테일] 9·10월 통합공고(BIZ CLUB팀 경력사원, MD AX 담당, 물류 AX 담당, 보안성 검토 담당)
  career: 경력3년↑
  location: 서울 강남구 외 1
  posted_date: 2026-09-21
  closing_date: 2026-10-01 23:00
  job_url: https://www.jobkorea.co.kr/Recruit/GI_Read/50032017
  search_keyword: ax
  collected_at: 2026-09-23 12:49:05

[2]
  company_name: 에스코어
  job_title: AX 컨설턴트 채용
  career: 경력
  location: 서울 송파구
  posted_date: 2026-07-01
  closing_date: 2026-09-30 23:00
  job_url: https://www.jobkorea.co.kr/Recruit/GI_Read/49589368
  search_keyword: ax
  collected_at: 2026-09-23 12:49:05

[3]
  company_name: ㈜NAVER
  job_title: 광고 프로덕트 기획 경력 채용(AX 광고 예산/과금 구조 설계 담당)
  career: 경력
  location: 경기 성남시
  posted_date: 2026-09-10
  closing_date: 2026-09-29 10:00
  job_url: https://www.jobkorea.co.kr/Recruit/GI_Read/49976564
  search_keyword: ax
  collected_at: 2026-09-23 12:49:05

[4]
  company_name: ㈜슈프리마
  job_title: [슈프리마HQ] HRD & AX 담당자 모집
  career: 경력7년↑
  location: 경기 성남시
  posted_date: 2026-08-26
  closing_date: 2026-10-25 23:00
  job_url: https://www.jobkorea.co.kr/Recruit/GI_Read/49858859
  search_keyword: ax
  collected_at: 2026-09-23 12:49:05

[5]
  company_name: ㈜NAVER
  job_title: 광고 프로덕트 기획 경력 채용(AX 광고 최적화 전략 담당)
  career: 경력
  location: 경기 성남시
  posted_date: 2026-09-10
  closing_date: 2026-09-29 10:00
  job_url: https://www.jobkorea.co.kr/Recruit/GI_Read/49976547
  search_keyword: ax
  collected_at: 2026-09-23 12:49:05

### 실행 결과 해석 / 분석 / 요약

- 사용 URL: `https://www.jobkorea.co.kr/Search/?stext=ax&tabType=recruit`
- 첫 번째 요청 상태 코드: `200` → 하지만 title이 `보안정책`, 응답 길이 3186 → **접속 제한 페이지**였다.
- User-Agent 추가 요청 여부: **예 (1회)** — 일반 브라우저 User-Agent 헤더만 추가했고, 그 외 우회 기법이나 반복 재시도는 쓰지 않았다.
- 최종 Content-Type: `text/html; charset=utf-8`
- 최종 응답 길이: 347641 (실행 시점마다 조금씩 달라질 수 있다)
- HTML title: `'ax' 관련 📢 채용공고 | 총 888건의 검색결과`
- 실제 검색 결과 HTML 여부: **예** (보안정책 문구 없음, title에 "채용공고" 포함)
- 찾은 채용공고 후보 수: 20개 (1페이지 기준)
- 실제 출력한 공고 수: 5건 (`cards[:5]`)
- 사용한 선택자 또는 탐색 방식:
  - 먼저 공고 링크 패턴 `/Recruit/GI_Read/번호`를 찾고, 그 부모 요소를 거슬러 올라가 반복 블록을 확인했다.
  - 공고 블록: `div[data-sentry-component="CardJob"]`
  - 제목: `a[data-sentry-component="Title"]`의 텍스트
  - 회사명: 제목 링크 다음 `<a>` 안의 첫 `<span>`
  - 지역: 첫 번째 `[data-sentry-component="GrayChip"] span.truncate`
  - 경력: `span.flex-shrink-0.text-typo-c1-13`
  - URL: 제목 링크의 `href`에서 `?` 뒤 추적용 파라미터를 제거한 기본 주소
  - 날짜: `self.__next_f.push(...)` script 안 JSON의 `"content": [...]` 공고 목록 → **공고 ID로 카드와 매칭**
- 날짜 데이터 결과:
  - 화면 카드 HTML에는 날짜 텍스트가 직접 없지만, 같은 응답의 Next.js script JSON에는 날짜가 있었다.
  - 지원 제출 시작일 → `applicationPeriod.start` → `posted_date`
    - 이번 프로젝트에서 **`posted_date`는 지원 제출 시작일을 의미한다.** (공고 등록일이 아님)
  - 지원 제출 마감일 → `applicationPeriod.end` → `closing_date`
  - `createdAt`은 사이트 등록 시각이라 사용하지 않았다.
  - 원본 값 예: `start=2026-09-21T00:00:00+09:00`, `end=2026-10-01T23:00:00+09:00`
    → 저장 값: `posted_date=2026-09-21`, `closing_date=2026-10-01 23:00`
    - 모든 값이 한국 시간(`+09:00`)이라 시간대 표기는 떼고, 시작일은 날짜만, 마감일은 날짜 + 시:분만 남겼다.
    - 원본 값은 코드 출력(`원본 applicationPeriod`)에서 함께 확인할 수 있다.
  - JSON에서 날짜가 있는 공고는 31건이었다. 검색 결과 목록 20건과, 별도 목록(`COMPANY_LIST` 쿼리) 11건이 섞여 있었다.
    ID로 매칭하기 때문에 섞여 있어도 문제가 없고, 같은 ID인데 날짜가 다른 경우는 없었다.
  - 5건 모두 JSON에서 같은 ID를 찾아 날짜가 채워졌다. (결측 없음)
- 추출 성공 필드: `company_name`, `job_title`, `career`, `location`, `posted_date`, `closing_date`, `job_url`, `search_keyword`, `collected_at` (9개 모두 값 있음)
- 비어 있는 필드: 없음
- HTML 구조상 특이사항:
  - 기본 `requests.get()`은 차단되고, 브라우저 User-Agent를 붙였을 때만 실제 페이지가 반환됐다.
  - 공고 1건에 같은 URL 링크가 3개(로고·제목·회사명) 있다. 그래서 `<a>` 태그를 세지 않고 `CardJob` 블록 단위로 셌다.
  - 경력 선택자와 script JSON 구조는 사이트 내부 구현이라, 사이트가 바뀌면 깨질 수 있다.
  - "서울 강남구 외 1"처럼 근무지가 여러 곳이면 화면에 보이는 요약 문구가 그대로 저장된다.
  - 비정상적으로 먼 날짜가 존재할 수 있으며, 후속 단계에서 상시채용 표기와의 관계를 별도 검증해야 한다.
    (이번 5건에는 없지만, 같은 페이지 6번째 공고의 `applicationPeriod.end`가 `2070-01-01`이었다. 원본 값을 그대로 둔다)
- 다음 단계 진행 가능 여부: 아래 브라우저 비교를 사람이 확인한 뒤, STEP 07-B에서 DataFrame 전달을 검증한다.

#### 브라우저와 직접 비교할 항목
1. 첫 번째 공고 제목이 브라우저 화면과 일치하는가? (`[GS리테일] 9·10월 통합공고(...)`)
2. 회사명이 일치하는가?
3. `job_url`을 브라우저에서 열면 해당 공고 상세 페이지로 연결되는가?
4. 위치/경력 정보가 실제 화면과 같은가?
5. 화면의 "MM/DD 등록 · MM/DD 마감"이 `posted_date` / `closing_date`와 같은가? (첫 공고: 화면 `09/21 등록 · 10/01 마감`)
6. 공고 순서가 브라우저와 같은가? (광고·추천 정렬 때문에 순서가 다를 수 있다)

### STEP 07-B. 날짜 데이터 전달 검증

### 작업 계획

이번 단계의 목적:
- STEP 07-A에서 추출한 `jobs`(list[dict]) 데이터가 DataFrame으로 변환된 뒤에도
  **지원 제출 시작일 / 마감일이 정상적으로 유지되는지** 확인한다.

DataFrame 이름:
- 실데이터용 DataFrame은 `df_real_jobs`로 만든다.
- STEP 04~07의 샘플 데이터 `df_jobs`를 덮어쓰지 않기 위해서다.

확인 항목:
- `jobs` → DataFrame 변환
- shape 확인
- 9개 컬럼 확인 (STEP 02 명세 순서)
- `posted_date`(= 지원 제출 시작일) 값 확인
- `closing_date`(= 지원 제출 마감일) 값 확인
- 결측값 확인
- `pd.to_datetime()`으로 날짜 변환이 가능한지 확인

중요:
- 원본 날짜 문자열은 보존한다.
- 날짜 변환 가능 여부는 원본 컬럼을 덮어쓰지 않고, 별도 변수(`posted_parsed`, `closing_parsed`)로만 확인한다.

이번 단계에서 하지 않는 것:
- 중복 제거, 신규 공고 판별, CSV 저장, 분석 (STEP 08 이후)

완료 조건:
- shape가 (5, 9)이다
- `posted_date`, `closing_date` 결측값이 0이다 (JSON에 값이 없는 공고가 있다면 그 수만큼 결측으로 남는 것이 정상)
- 날짜 변환 실패가 0건이다

In [2]:
import pandas as pd

# STEP 02에서 정한 9개 컬럼 순서
columns = [
    "company_name",
    "job_title",
    "career",
    "location",
    "posted_date",    # 지원 제출 시작일 (applicationPeriod.start)
    "closing_date",   # 지원 제출 마감일 (applicationPeriod.end)
    "job_url",
    "search_keyword",
    "collected_at",
]

# ----- 1) jobs(list[dict]) → DataFrame 변환 -----
# 샘플 데이터 df_jobs를 덮어쓰지 않도록 실데이터는 df_real_jobs라는 이름을 쓴다
df_real_jobs = pd.DataFrame(jobs, columns=columns)

# ----- 2) 크기와 컬럼 확인 -----
print("데이터 크기:", df_real_jobs.shape)
print("컬럼 목록:", df_real_jobs.columns.tolist())

# ----- 3) 날짜 값 확인 (원본 문자열 그대로) -----
print("\n회사명 / 지원 시작일 / 지원 마감일:")
display(df_real_jobs[["company_name", "posted_date", "closing_date"]])

# ----- 4) 결측값 확인 -----
print("\n결측값 개수:")
print(df_real_jobs.isna().sum())

# ----- 5) 날짜 변환 가능 여부 확인 -----
# 원본 컬럼은 그대로 두고, 변환 결과는 별도 변수에만 저장한다
# errors="coerce": 날짜로 바꿀 수 없는 값은 NaT(날짜 결측값)가 된다 → NaT 개수 = 변환 실패 수
posted_parsed = pd.to_datetime(df_real_jobs["posted_date"], errors="coerce")
closing_parsed = pd.to_datetime(df_real_jobs["closing_date"], errors="coerce")

print("\nposted_date 변환 실패:", posted_parsed.isna().sum())
print("closing_date 변환 실패:", closing_parsed.isna().sum())
print("변환 후 dtype:", posted_parsed.dtype, "/", closing_parsed.dtype)
print("원본 컬럼 dtype(그대로 유지):", df_real_jobs["posted_date"].dtype, "/", df_real_jobs["closing_date"].dtype)

데이터 크기: (5, 9)
컬럼 목록: ['company_name', 'job_title', 'career', 'location', 'posted_date', 'closing_date', 'job_url', 'search_keyword', 'collected_at']

회사명 / 지원 시작일 / 지원 마감일:

  company_name posted_date      closing_date
0        GS리테일  2026-09-21  2026-10-01 23:00
1         에스코어  2026-07-01  2026-09-30 23:00
2       ㈜NAVER  2026-09-10  2026-09-29 10:00
3        ㈜슈프리마  2026-08-26  2026-10-25 23:00
4       ㈜NAVER  2026-09-10  2026-09-29 10:00

결측값 개수:
company_name      0
job_title         0
career            0
location          0
posted_date       0
closing_date      0
job_url           0
search_keyword    0
collected_at      0
dtype: int64

posted_date 변환 실패: 0
closing_date 변환 실패: 0
변환 후 dtype: datetime64[us] / datetime64[us]
원본 컬럼 dtype(그대로 유지): str / str

### 실행 결과 해석 / 분석 / 요약

- 셀이 에러 없이 실행되었다.
- DataFrame shape: `(5, 9)`
- 총 행 수: 5 (STEP 07-A에서 추출한 공고 5건)
- 총 컬럼 수: 9 (`company_name`, `job_title`, `career`, `location`, `posted_date`, `closing_date`, `job_url`, `search_keyword`, `collected_at`)
- posted_date 결측 수: 0
- closing_date 결측 수: 0 (다른 7개 컬럼도 모두 결측 0)
- posted_date 변환 실패 수: 0
- closing_date 변환 실패 수: 0
  - 변환은 `posted_parsed`, `closing_parsed` 변수에만 했고, `df_real_jobs`의 원본 컬럼은 문자열(`str`) 그대로 유지했다.
- 첫 번째 공고의 지원 시작일: `2026-09-21` (GS리테일)
- 첫 번째 공고의 지원 마감일: `2026-10-01 23:00`
- 브라우저 화면과 일치 여부: 화면에 표시되는 `09/21 등록 · 10/01 마감`과 날짜가 일치한다. 나머지 4건은 사람이 브라우저에서 직접 확인해야 한다.
- 5건 날짜 요약:

| company_name | posted_date (지원 시작일) | closing_date (지원 마감일) |
|---|---|---|
| GS리테일 | 2026-09-21 | 2026-10-01 23:00 |
| 에스코어 | 2026-07-01 | 2026-09-30 23:00 |
| ㈜NAVER | 2026-09-10 | 2026-09-29 10:00 |
| ㈜슈프리마 | 2026-08-26 | 2026-10-25 23:00 |
| ㈜NAVER | 2026-09-10 | 2026-09-29 10:00 |

- 2070년 등 특이값 존재 여부: 이번 5건에는 없다. 다만 같은 페이지 6번째 공고에서 `2070-01-01`이 확인되었으므로,
  비정상적으로 먼 날짜가 존재할 수 있으며, 후속 단계에서 상시채용 표기와의 관계를 별도 검증해야 한다.
- 결론: `applicationPeriod.start/end → posted_date/closing_date → jobs → DataFrame` 흐름에서 날짜가 빠짐없이 유지되었다.
- 다음 단계 진행 가능 여부: 사용자가 브라우저 화면과 날짜를 비교해 확인하면 진행 가능하다.

# STEP 07-C. 실데이터 중복 확인 및 제거

## 작업 계획

이번 단계에서는 STEP 07-A/07-B에서 만든 **실제 공고 5건(`df_real_jobs`)** 안에
같은 공고가 두 번 이상 들어 있는지 확인한다.

> 참고: STEP 06의 중복 제거는 **샘플 데이터(`df_jobs`)** 연습이었다.
> 이번에는 실데이터(`df_real_jobs`)를 대상으로 한다.

중복 기준: `job_url`
- 같은 회사가 공고를 여러 개 낼 수 있어서, 회사명만으로는 중복을 판단할 수 없다.
- 공고 제목도 비슷하거나 같을 수 있다. (예: 같은 회사의 "광고 프로덕트 기획 경력 채용(...)" 공고 2개)
- `job_url`은 공고마다 번호가 달라서 개별 공고를 구분하는 데 가장 적합하다.
- STEP 07-A에서 `?Oem_Code=...&listno=...` 같은 추적용 값을 떼고 기본 공고 URL만 저장했으므로, 같은 공고는 같은 URL이 된다.

확인 내용:
- 현재 공고 수
- 중복된 `job_url`이 있는지
- 중복 행 수
- 중복 제거 후 공고 수
- 어떤 공고가 중복이었는지

중요:
- 원본 DataFrame인 `df_real_jobs`는 수정하지 않는다.
- 중복 제거 결과는 새로운 DataFrame `df_unique_jobs`에 저장한다.
- `df_real_jobs`가 메모리에 없으면 데이터를 임의로 만들지 않고, STEP 07-A → 07-B를 먼저 실행하라고 안내한다.

아직 하지 않는 것:
- 이전 실행 결과와 비교
- 신규/기존 공고 판별
- CSV 저장
- 여러 페이지 크롤링
- 여러 검색어 수집
- 통계 분석

완료 조건:
- `job_url` 기준 중복 확인을 수행하고 중복 행 수를 확인한다
- `df_unique_jobs`가 만들어진다
- 원본 `df_real_jobs`가 그대로 보존된다
- 중복 제거 전/후 행 수를 확인한다

In [4]:
# ----- 0) df_real_jobs가 있는지 먼저 확인 -----
# STEP 07-A → 07-B를 실행하지 않았다면 df_real_jobs가 없다 (데이터를 임의로 만들지 않는다)
if "df_real_jobs" not in globals():
    print("df_real_jobs가 없습니다. STEP 07-A와 STEP 07-B를 먼저 실행하세요.")
else:
    # ----- 1) 현재 행 수 -----
    print("현재 공고 수:", len(df_real_jobs))

    # ----- 2) job_url 기준 중복 여부 확인 -----
    # duplicated(): 중복인 행을 "찾기"만 한다 (True/False)
    # keep=False: 중복된 행을 첫 번째 것까지 모두 True로 표시 → 어떤 공고끼리 겹쳤는지 전부 볼 수 있다
    duplicate_mask = df_real_jobs.duplicated(subset=["job_url"], keep=False)
    duplicate_rows = df_real_jobs.loc[duplicate_mask, ["company_name", "job_title", "job_url"]]

    # ----- 3) 중복 행 수 -----
    print("중복 행 수:", duplicate_mask.sum())

    # ----- 4) 중복이 있으면 출력 -----
    if duplicate_mask.any():
        display(duplicate_rows)
    else:
        print("현재 5건 안에는 job_url 기준 중복 공고가 없습니다.")

    # ----- 5) 원본을 보존한 채 새 DataFrame 생성 -----
    # drop_duplicates(): 중복 행을 제거한 "새 결과"를 만든다 (df_real_jobs 자체는 바뀌지 않는다)
    # keep="first": 같은 job_url이 여러 개면 처음 나온 행만 남긴다
    # reset_index(drop=True): 행 번호를 0부터 다시 매긴다
    df_unique_jobs = (
        df_real_jobs
        .drop_duplicates(subset=["job_url"], keep="first")
        .reset_index(drop=True)
    )

    # ----- 6) 전/후 개수 확인 -----
    print("\n중복 제거 전:", len(df_real_jobs))
    print("중복 제거 후:", len(df_unique_jobs))
    print("제거된 행 수:", len(df_real_jobs) - len(df_unique_jobs))

    # ----- 7) 결과 확인 -----
    display(df_unique_jobs[["company_name", "job_title", "posted_date", "closing_date", "job_url"]])

현재 공고 수: 5
중복 행 수: 0
현재 5건 안에는 job_url 기준 중복 공고가 없습니다.

중복 제거 전: 5
중복 제거 후: 5
제거된 행 수: 0

,company_name,job_title,posted_date,closing_date,job_url
0,GS리테일,"[GS리테일] 9·10월 통합공고(BIZ CLUB팀 경력사원, MD AX 담당, 물...",2026-09-21,2026-10-01 23:00,https://www.jobkorea.co.kr/Recruit/GI_Read/500...
1,에스코어,AX 컨설턴트 채용,2026-07-01,2026-09-30 23:00,https://www.jobkorea.co.kr/Recruit/GI_Read/495...
2,㈜NAVER,광고 프로덕트 기획 경력 채용(AX 광고 예산/과금 구조 설계 담당),2026-09-10,2026-09-29 10:00,https://www.jobkorea.co.kr/Recruit/GI_Read/499...
3,㈜슈프리마,[슈프리마HQ] HRD & AX 담당자 모집,2026-08-26,2026-10-25 23:00,https://www.jobkorea.co.kr/Recruit/GI_Read/498...
4,㈜NAVER,광고 프로덕트 기획 경력 채용(AX 광고 최적화 전략 담당),2026-09-10,2026-09-29 10:00,https://www.jobkorea.co.kr/Recruit/GI_Read/499...

## 실행 결과 해석 / 분석 / 요약

- 셀이 에러 없이 실행되었다. (STEP 07-A → 07-B → 07-C 순서로 실행)
- 중복 확인 전 공고 수: 5
- 중복된 행 수: 0
- 중복 제거 후 공고 수: 5
- 실제 제거된 행 수: 0
- 사용한 중복 기준: `job_url` (추적용 파라미터를 뗀 기본 공고 URL)
- 중복 공고 존재 여부: **없음** — 현재 5건은 모두 서로 다른 공고이다.
- `df_real_jobs` 원본 보존 여부: **보존됨** — 실행 전후 5행 그대로이며 내용도 바뀌지 않았다.
- 새 DataFrame 이름: `df_unique_jobs` (5행)
- 예상과 다른 부분: 없음.
  - 참고로 ㈜NAVER 공고가 2건(3번째, 5번째) 있고 제목도 비슷하다.
    하지만 `job_url`이 서로 다르므로(`.../49976564`, `.../49976547`) **서로 다른 공고**로 판단되었다.
    회사명이나 제목이 아니라 `job_url`을 중복 기준으로 쓰는 이유를 보여 주는 사례이다.
- 다음 단계 진행 가능 여부: 사용자가 결과를 확인하면, 이전 실행 결과와 비교하는 다음 단계로 진행할 수 있다.

#### 초보자 설명
- `duplicated()` → 어떤 행이 중복인지 **"찾는"** 기능이다. 행마다 True/False를 돌려줄 뿐 데이터를 지우지 않는다.
  - `keep=False`로 두면 겹치는 행을 모두 True로 표시해서, 어떤 공고끼리 겹쳤는지 전부 볼 수 있다.
- `drop_duplicates()` → 중복된 행을 실제로 **"제거한 새 결과를 만드는"** 기능이다.
  - `keep="first"`로 두면 같은 URL 중 처음 나온 행만 남긴다.
- 이번에는 원본을 보존하기 위해 두 DataFrame을 분리했다.
  - `df_real_jobs` → 원본 (수집한 그대로)
  - `df_unique_jobs` → 중복 제거 결과
- 이번 단계는 "현재 5건 **안에서** 같은 공고가 겹치는가?"만 확인했다.
  "지난번 수집 결과와 비교해서 신규 공고인가?"는 아직 하지 않았다.

# STEP 07-D. 신규 공고 판별 및 이력 초기화

## 작업 계획

이번 단계에서는 현재 실데이터 공고(`df_unique_jobs`)를 **과거에 수집한 공고 이력**과 비교해서
이번에 처음 나타난 공고(신규 공고)만 골라낸다.

> 참고: STEP 07은 샘플 이력(`previous_urls`)으로 연습한 것이었다.
> 이번에는 실데이터와 **실제 파일로 저장되는 이력**을 사용한다.

신규 공고 판별의 개념:

```text
현재 수집 공고
  minus
과거에 이미 본 공고
  =
신규 공고
```

비교 기준: `job_url`
- 회사명이나 제목은 같거나 비슷할 수 있다. (예: ㈜NAVER의 비슷한 제목 공고 2건)
- `job_url`은 공고마다 번호가 달라서 개별 공고를 구분하기에 적합하다.

이력 파일:
- `data/processed/jobs_history.csv` (프로젝트 루트 기준)
- Notebook은 `notebooks/` 폴더에서 실행되므로, 코드에서 프로젝트 루트를 계산해 경로를 만든다.
- 폴더(`data/processed/`)가 없으면 저장할 때 만든다.

첫 실행 규칙:
- history 파일이 없으면 과거 데이터가 없다는 뜻이다.
- 현재 `df_unique_jobs` 전체를 신규 공고로 간주한다.
- 현재 데이터를 history 파일의 초기값으로 저장한다.

두 번째 실행부터:
- history의 `job_url` 집합과 현재 `job_url`을 비교한다.
- history에 없는 `job_url`만 신규 공고이다.
- history에는 현재 공고를 합치되, `job_url` 기준으로 중복을 제거해서 같은 공고가 두 번 쌓이지 않게 한다.

DataFrame 역할 분리 (원본은 수정하지 않는다):
- `df_real_jobs` → 원본 실데이터
- `df_unique_jobs` → 현재 실행의 중복 제거 결과
- `history_df` → 파일에서 읽은 과거 이력
- `new_jobs_df` → 이번 실행에서 새로 발견된 공고
- `updated_history_df` → 저장할 누적 이력

이번 단계에서 하지 않는 것:
- 통계 분석, Gemini 요약, Slack / Gmail
- 여러 페이지 / 여러 검색어 수집

완료 조건:
- 첫 실행: history 없음 → 현재 5건 모두 신규 → history 5건 생성
- 두 번째 실행: 같은 5건 → 신규 0건 → history 여전히 5건 (10건으로 늘어나면 안 된다)

In [5]:
from pathlib import Path
import pandas as pd

# ----- 0) df_unique_jobs가 있는지 먼저 확인 -----
if "df_unique_jobs" not in globals():
    print("df_unique_jobs가 없습니다. STEP 07-A → 07-B → 07-C를 먼저 실행하세요.")
else:
    # ----- A) 경로 정의 -----
    # Notebook은 notebooks/ 폴더에서 실행되므로, 그 경우 한 단계 위를 프로젝트 루트로 사용한다
    current_dir = Path.cwd()
    project_root = current_dir.parent if current_dir.name == "notebooks" else current_dir
    history_path = project_root / "data" / "processed" / "jobs_history.csv"
    print("현재 실행 위치:", current_dir)
    print("history 파일 경로:", history_path)

    # ----- B) history 존재 여부 확인 -----
    if history_path.exists():
        history_df = pd.read_csv(history_path)
        print("\n기존 이력 파일 있음")
        print("기존 이력 건수:", len(history_df))
    else:
        # 과거 데이터가 없으므로 컬럼만 있는 빈 표로 시작한다
        history_df = pd.DataFrame(columns=df_unique_jobs.columns)
        print("\n기존 이력 파일 없음")
        print("첫 실행으로 처리합니다.")

    # ----- C) 신규 공고 판별 -----
    # set(): 이미 본 URL을 모아 둔 "집합" — 어떤 URL이 들어 있는지 빠르게 확인할 수 있다
    known_urls = set(history_df["job_url"].dropna().astype(str))

    # isin(known_urls): 현재 URL이 과거 URL 집합에 "있는지" True/False로 확인
    # ~ 를 붙이면 True/False가 뒤집힌다 → 과거 집합에 "없는" 공고만 선택 = 신규 공고
    new_jobs_df = df_unique_jobs[~df_unique_jobs["job_url"].isin(known_urls)].copy()

    print("\n현재 공고 수:", len(df_unique_jobs))
    print("기존 이력 수:", len(history_df))
    print("신규 공고 수:", len(new_jobs_df))

    # ----- E) 신규 공고 출력 -----
    if len(new_jobs_df) > 0:
        display(new_jobs_df[["company_name", "job_title", "posted_date", "closing_date", "job_url"]])
    else:
        print("이번 실행에서 새로 발견된 공고가 없습니다.")

    # ----- F) history 업데이트 -----
    # 과거 이력 + 현재 공고를 합친 뒤, job_url 기준으로 중복을 제거한다
    # keep="last": 같은 공고가 있으면 나중에 붙은 행(= 이번 실행의 최신 정보)을 남긴다
    updated_history_df = pd.concat([history_df, df_unique_jobs], ignore_index=True)
    updated_history_df = (
        updated_history_df
        .drop_duplicates(subset=["job_url"], keep="last")
        .reset_index(drop=True)
    )

    # 폴더가 없으면 만든다 (이미 있으면 그대로 사용)
    history_path.parent.mkdir(parents=True, exist_ok=True)
    # encoding="utf-8-sig": 엑셀에서 열어도 한글이 깨지지 않게 저장
    updated_history_df.to_csv(history_path, index=False, encoding="utf-8-sig")

    print("\n업데이트 후 이력 건수:", len(updated_history_df))
    print("history 저장 경로:", history_path)

현재 실행 위치: C:\dev\claude-code-agent-course\chapter11\ax-job-agent\notebooks
history 파일 경로: C:\dev\claude-code-agent-course\chapter11\ax-job-agent\data\processed\jobs_history.csv

기존 이력 파일 없음
첫 실행으로 처리합니다.

현재 공고 수: 5
기존 이력 수: 0
신규 공고 수: 5

,company_name,job_title,posted_date,closing_date,job_url
0,GS리테일,"[GS리테일] 9·10월 통합공고(BIZ CLUB팀 경력사원, MD AX 담당, 물...",2026-09-21,2026-10-01 23:00,https://www.jobkorea.co.kr/Recruit/GI_Read/500...
1,에스코어,AX 컨설턴트 채용,2026-07-01,2026-09-30 23:00,https://www.jobkorea.co.kr/Recruit/GI_Read/495...
2,㈜NAVER,광고 프로덕트 기획 경력 채용(AX 광고 예산/과금 구조 설계 담당),2026-09-10,2026-09-29 10:00,https://www.jobkorea.co.kr/Recruit/GI_Read/499...
3,㈜슈프리마,[슈프리마HQ] HRD & AX 담당자 모집,2026-08-26,2026-10-25 23:00,https://www.jobkorea.co.kr/Recruit/GI_Read/498...
4,㈜NAVER,광고 프로덕트 기획 경력 채용(AX 광고 최적화 전략 담당),2026-09-10,2026-09-29 10:00,https://www.jobkorea.co.kr/Recruit/GI_Read/499...

업데이트 후 이력 건수: 5
history 저장 경로: C:\dev\claude-code-agent-course\chapter11\ax-job-agent\data\processed\jobs_history.csv

## 실행 결과 해석 / 분석 / 요약

- 셀이 에러 없이 실행되었다. (STEP 07-A → 07-B → 07-C → 07-D 순서로 실행, 실행 위치는 `notebooks/`)
- 위 출력은 **첫 실행** 결과이다.

#### 첫 실행 결과
- 현재 공고 수: 5
- 기존 history 건수: 0
- 신규 공고 수: 5
- history 업데이트 후 건수: 5
- 첫 실행 여부: **예** — 실행 전에는 `data/` 폴더와 history 파일이 없었다.
- history 파일 생성 여부: **생성됨** — `data/processed/jobs_history.csv` (5행 × 9열, `job_url` 5개 모두 서로 다름)

#### 두 번째 실행 결과 (같은 셀을 같은 5건으로 한 번 더 실행)
- 기존 history 건수: 5 (첫 실행에서 만든 파일을 읽음)
- 신규 공고 수: **0** — "이번 실행에서 새로 발견된 공고가 없습니다."
- history 업데이트 후 건수: **5** — 10건으로 늘어나지 않았다.
- 같은 공고 재실행 시 신규 0건인지: **예**

→ 첫 실행(5건 모두 신규)과 두 번째 실행(신규 0건) 결과가 다르게 나왔다.
즉 **"이미 본 공고는 다시 신규로 잡히지 않는다"**는 것이 확인되었다.

#### 기타 확인
- 신규 공고 기준: `job_url`이 history의 `job_url` 집합에 없으면 신규
- 원본 `df_unique_jobs` 보존 여부: **보존됨** (`df_real_jobs`도 그대로)
- `new_jobs_df` 생성 여부: **생성됨** (첫 실행 5건, 두 번째 실행 0건)
- 예상과 다른 부분: 없음.
- 참고 / 한계:
  - 두 번째 실행은 **다시 크롤링하지 않고** 같은 커널의 같은 5건으로 실행했다. 판별 로직 검증이 목적이었기 때문이다.
    실제 운영에서는 다음 수집 때 새로 나온 공고만 신규로 잡힐 것으로 예상하며, 이는 이후 실제 재수집으로 확인해야 한다.
  - history에는 `keep="last"`로 저장하므로, 같은 공고를 다시 수집하면 `collected_at`이 최신 수집 시각으로 바뀐다.
    ("처음 발견한 시각"을 따로 남기고 싶다면 후속 단계에서 컬럼 추가를 검토한다)
  - 이 셀은 실행할 때마다 history 파일을 덮어써 저장한다.
- 다음 단계 진행 가능 여부: 사용자가 결과와 CSV 파일을 확인하면 진행 가능하다.

#### 초보자 설명
- `set()` → 이미 본 URL을 모아 둔 **집합**이다. 어떤 URL이 들어 있는지 빠르게 비교할 수 있다.
- `isin()` → 현재 URL이 과거 URL 목록에 **있는지** True/False로 확인한다.
- `~isin(...)` → True/False를 뒤집어서, 과거 목록에 **없는 것만** 선택한다. = 신규 공고
- 첫 실행: history 없음 → 현재 공고 모두 신규 → history 초기 생성
- 두 번째 실행: history에 같은 5개 `job_url` 있음 → 신규 0건

# STEP 07-E. 실데이터 기본 분석

## 작업 계획

이번 단계의 목적:
- 수집된 채용공고를 **숫자로 요약**해서, 어떤 회사·지역·경력 조건이 많이 나오는지 확인한다.
- pandas의 기본 집계 방법(`value_counts()`, `min()`, `max()`)을 연습하는 것이 목적이다.

분석 대상: `df_unique_jobs`
- 현재 실행에서 `job_url` 기준으로 중복을 제거한 **실제 공고 데이터**이기 때문이다.
- 원본 `df_unique_jobs`는 수정하지 않고, 읽기만 한다.

확인 항목:
- 전체 공고 수
- 회사별 공고 수
- 지역별 공고 수
- 경력별 공고 수
- 검색어별 공고 수
- 신규 공고 수 (STEP 07-D의 `new_jobs_df`가 있을 때만)
- 지원 시작일(`posted_date`) / 지원 마감일(`closing_date`) 범위

중요한 해석 원칙:
- 현재 표본은 **검색어 `ax`, 1페이지 상위 5건**뿐이다.
- 따라서 결과를 "채용 시장 전체의 경향"으로 해석하면 안 된다.
- 결과는 항상 "현재 수집된 5건 기준으로"처럼 제한해서 해석한다.

참고:
- 신규 공고 수는 STEP 07-D를 실행한 결과(`new_jobs_df`)에 따라 달라진다.
  - 첫 실행 직후라면 5, 같은 공고로 다시 실행했다면 0이 나온다.
  - STEP 07-D를 실행하지 않았다면 신규 공고 수는 확인하지 못했다고 출력된다.

이번 단계에서 하지 않는 것:
- 관련 공고 점수화, Gemini 요약, Slack / Gmail
- 여러 검색어 / 여러 페이지 수집

완료 조건:
- 위 확인 항목이 모두 출력된다
- `df_unique_jobs`가 바뀌지 않는다

In [5]:
import pandas as pd

# ----- 0) df_unique_jobs가 있는지 먼저 확인 -----
if "df_unique_jobs" not in globals():
    print("df_unique_jobs가 없습니다. 이전 실데이터 STEP을 먼저 실행하세요.")
else:
    # ----- 1) 전체 공고 수 -----
    print("전체 공고 수:", len(df_unique_jobs))

    # ----- 2) 회사별 공고 수 -----
    # value_counts(): 같은 값이 몇 번 나오는지 세어서 많은 순서로 보여 준다
    company_counts = df_unique_jobs["company_name"].value_counts()
    print("\n=== 회사별 공고 수 ===")
    print(company_counts)

    # ----- 3) 지역별 공고 수 -----
    location_counts = df_unique_jobs["location"].value_counts()
    print("\n=== 지역별 공고 수 ===")
    print(location_counts)

    # ----- 4) 경력별 공고 수 -----
    career_counts = df_unique_jobs["career"].value_counts()
    print("\n=== 경력별 공고 수 ===")
    print(career_counts)

    # ----- 5) 검색어별 공고 수 -----
    keyword_counts = df_unique_jobs["search_keyword"].value_counts()
    print("\n=== 검색어별 공고 수 ===")
    print(keyword_counts)

    # ----- 6) 신규 공고 수 (STEP 07-D를 실행했을 때만 확인 가능) -----
    if "new_jobs_df" in globals():
        print("\n신규 공고 수:", len(new_jobs_df))
    else:
        print("\nnew_jobs_df가 없어 신규 공고 수는 확인하지 못했습니다.")

    # ----- 7) 날짜 범위 확인 -----
    # 원본 문자열 컬럼은 그대로 두고, 날짜로 바꾼 결과는 별도 변수에만 저장한다
    posted_parsed = pd.to_datetime(df_unique_jobs["posted_date"], errors="coerce")
    closing_parsed = pd.to_datetime(df_unique_jobs["closing_date"], errors="coerce")

    # min(): 가장 작은 값(가장 이른 날짜), max(): 가장 큰 값(가장 늦은 날짜)
    print("\n=== 지원 기간 날짜 범위 ===")
    print("가장 이른 지원 시작일:", posted_parsed.min())
    print("가장 늦은 지원 시작일:", posted_parsed.max())
    print("가장 이른 지원 마감일:", closing_parsed.min())
    print("가장 늦은 지원 마감일:", closing_parsed.max())

전체 공고 수: 5

=== 회사별 공고 수 ===
company_name
㈜NAVER    2
GS리테일     1
에스코어      1
㈜슈프리마     1
Name: count, dtype: int64

=== 지역별 공고 수 ===
location
경기 성남시        3
서울 강남구 외 1    1
서울 송파구        1
Name: count, dtype: int64

=== 경력별 공고 수 ===
career
경력       3
경력3년↑    1
경력7년↑    1
Name: count, dtype: int64

=== 검색어별 공고 수 ===
search_keyword
ax    5
Name: count, dtype: int64

new_jobs_df가 없어 신규 공고 수는 확인하지 못했습니다.

=== 지원 기간 날짜 범위 ===
가장 이른 지원 시작일: 2026-07-01 00:00:00
가장 늦은 지원 시작일: 2026-09-21 00:00:00
가장 이른 지원 마감일: 2026-09-29 10:00:00
가장 늦은 지원 마감일: 2026-10-25 23:00:00

## 실행 결과 해석 / 분석 / 요약

- 셀이 에러 없이 실행되었다. (STEP 07-A → 07-B → 07-C → 07-E 순서로 실행)
- 아래 해석은 모두 **현재 수집된 5건 기준**이다. (검색어 `ax`, 1페이지 상위 5건)

| 항목 | 결과 |
|---|---|
| 전체 공고 수 | 5 |
| 회사별 공고 수 | ㈜NAVER 2 / GS리테일 1 / 에스코어 1 / ㈜슈프리마 1 |
| 지역별 공고 수 | 경기 성남시 3 / 서울 강남구 외 1 1 / 서울 송파구 1 |
| 경력별 공고 수 | 경력 3 / 경력3년↑ 1 / 경력7년↑ 1 |
| 검색어별 공고 수 | ax 5 |
| 신규 공고 수 | 이번 실행에서는 확인하지 못함 (아래 참고) |
| 가장 이른 지원 시작일 | 2026-07-01 (에스코어) |
| 가장 늦은 지원 시작일 | 2026-09-21 (GS리테일) |
| 가장 이른 지원 마감일 | 2026-09-29 10:00 (㈜NAVER 2건) |
| 가장 늦은 지원 마감일 | 2026-10-25 23:00 (㈜슈프리마) |

해석 (현재 5건 기준):
- 이번 샘플에서는 ㈜NAVER 공고가 2건으로 가장 많고, 나머지 회사는 1건씩이다.
- 이번 샘플에서는 경기 성남시 공고가 3건이다. (㈜NAVER 2건 + ㈜슈프리마 1건)
- 이번 샘플에서는 5건 모두 경력직 공고이고, 신입 공고는 없다.
- 이번 샘플의 지원 마감일은 2026-09-29 ~ 2026-10-25 사이에 있다.

특이사항:
- 표본이 5건뿐이라 이 결과를 채용 시장 전체의 경향으로 볼 수 없다.
- 경력 값은 화면 글자 그대로라서 `경력`, `경력3년↑`, `경력7년↑`가 **서로 다른 값**으로 세어졌다.
  "경력직 전체"로 묶어 세려면 값 정리 규칙이 필요하다. (후속 단계에서 검토)
- 지역 값 `서울 강남구 외 1`은 근무지가 여러 곳인 공고의 요약 문구라, 다른 지역 값과 형식이 다르다.
- 신규 공고 수: STEP 07-D는 실행할 때마다 `jobs_history.csv`를 다시 저장하기 때문에,
  이번 검증 실행에서는 07-D를 실행하지 않았다. 그래서 `new_jobs_df`가 없어 "확인하지 못했습니다"가 출력되었다.
  - 참고로 history 파일을 읽기만 해서 비교해 보면, 현재 5건은 모두 이미 history에 있다. (지금 07-D를 실행하면 신규 0건 예상)
  - 07-D까지 실행한 뒤 이 셀을 실행하면 신규 공고 수가 출력된다.
- 이번 5건에는 `2070-01-01` 같은 비정상적으로 먼 마감일이 없다.
- 원본 `df_unique_jobs`는 수정되지 않았다.
- 다음 단계 진행 가능 여부: 사용자가 결과를 확인하면 진행 가능하다.

#### 초보자 설명
- `value_counts()` → 같은 값이 **몇 번 나오는지 세는** 기능이다. 많이 나온 값부터 순서대로 보여 준다.
- `min()` → **가장 작은 값**이다. 날짜에서는 가장 이른 날짜가 된다.
- `max()` → **가장 큰 값**이다. 날짜에서는 가장 늦은 날짜가 된다.
- 날짜는 문자열 상태에서도 모양상 비교할 수 있지만, `pd.to_datetime()`으로 날짜 타입으로 바꾼 뒤 `min()`/`max()`를 쓰는 것이 정확하다.

# STEP 07-F. AX/AI 관련 공고 1차 필터링

## 작업 계획

이번 단계의 목적:
- 현재 수집된 채용공고(`df_unique_jobs`) 중에서 **공고 제목에 AX/AI 관련 키워드가 들어 있는 공고**를 Python으로 먼저 골라 본다.
- LLM/Gemini가 아니라 **단순한 문자열 검색**을 사용한다.
- 원칙: Python으로 먼저 후보를 좁히고, 나중에 Gemini가 내용 해석을 담당한다.

1차 필터 키워드:
- `AX`, `AI`, `인공지능`, `생성형 AI`, `생성형AI`, `LLM`
- `Machine Learning`, `머신러닝`, `Data Scientist`, `데이터 사이언티스트`
- `AI Engineer`, `AI 엔지니어`, `데이터 분석`

검색 방법:
- 대상은 우선 `job_title`(공고 제목)만 사용한다. 회사명이나 상세 본문은 후속 단계에서 검토한다.
- 대소문자 차이를 없애기 위해 제목과 키워드를 모두 소문자로 바꿔서 비교한다. (예: `Ax`, `ax`, `AX`를 같게 취급)
- 원본 `job_title` 값 자체는 바꾸지 않는다.
- 공고마다 **어떤 키워드에 매칭됐는지**(`matched_keywords`)도 함께 출력해서 사람이 이유를 확인할 수 있게 한다.

미리 알아 둘 점:
- 현재 실데이터는 검색어 자체가 `ax`이므로, 5건 대부분 또는 전부가 통과할 가능성이 높다.
- 그래서 이번 STEP의 목적은 "좋은 공고를 최종 판단"하는 것이 아니라 **키워드 기반 필터링 방법을 검증**하는 것이다.
- 키워드가 들어 있다고 원하는 AX 직무라는 뜻은 아니고, 반대로 제목에 키워드가 없어도 실제 업무는 AI/AX 관련일 수 있다.
  → 이번 결과는 **"1차 후보"**로만 해석한다.

DataFrame 역할 분리 (원본은 수정하지 않는다):
- `df_real_jobs` → 원본 실데이터
- `df_unique_jobs` → 중복 제거된 현재 공고 (새 컬럼도 추가하지 않는다)
- `df_filtered_jobs` → AX/AI 키워드 1차 필터 결과 (복사본이며, 여기에만 `matched_keywords` 컬럼을 추가한다)

이번 단계에서 하지 않는 것:
- Gemini API, 점수화, 추천 순위
- 상세 페이지 요청, 여러 페이지 / 여러 검색어 수집
- history CSV 갱신

완료 조건:
- 전체 공고 수, 필터 통과 공고 수, 제외 공고 수가 출력된다
- 공고별 회사명 / 제목 / 매칭 키워드를 사람이 확인할 수 있다
- `df_filtered_jobs`가 만들어지고, `df_unique_jobs`는 바뀌지 않는다

In [5]:
# ----- 0) df_unique_jobs가 있는지 먼저 확인 -----
if "df_unique_jobs" not in globals():
    print("df_unique_jobs가 없습니다. 이전 실데이터 STEP을 먼저 실행하세요.")
else:
    # ----- 1) 1차 필터 키워드 -----
    relevance_keywords = [
        "AX",
        "AI",
        "인공지능",
        "생성형 AI",
        "생성형AI",
        "LLM",
        "Machine Learning",
        "머신러닝",
        "Data Scientist",
        "데이터 사이언티스트",
        "AI Engineer",
        "AI 엔지니어",
        "데이터 분석",
    ]

    # ----- 2) 제목에 키워드가 하나라도 있는지 확인하는 함수 -----
    def contains_relevance_keyword(title):
        if not isinstance(title, str):  # 제목이 비어 있으면(None 등) 통과시키지 않는다
            return False
        title_lower = title.lower()     # 비교할 때만 소문자로 바꾼다 (원본 값은 그대로)
        # any(): 여러 조건 중 하나라도 True면 True
        return any(keyword.lower() in title_lower for keyword in relevance_keywords)

    # ----- 3) 제목에서 실제로 매칭된 키워드 목록을 찾는 함수 -----
    def find_matched_keywords(title):
        if not isinstance(title, str):
            return []
        title_lower = title.lower()
        return [keyword for keyword in relevance_keywords if keyword.lower() in title_lower]

    # ----- 4) 1차 필터링 -----
    # apply(): job_title의 각 값에 함수를 하나씩 적용해서 True/False 목록을 만든다
    # .copy(): 필터 결과를 원본과 분리된 새 DataFrame으로 만든다
    is_relevant = df_unique_jobs["job_title"].apply(contains_relevance_keyword)
    df_filtered_jobs = df_unique_jobs[is_relevant].copy()

    # 매칭 키워드는 복사본(df_filtered_jobs)에만 컬럼으로 추가한다 (df_unique_jobs에는 추가하지 않음)
    df_filtered_jobs["matched_keywords"] = df_filtered_jobs["job_title"].apply(find_matched_keywords)

    # ----- 5) 결과 출력 -----
    print("전체 공고 수:", len(df_unique_jobs))
    print("1차 필터 통과 공고 수:", len(df_filtered_jobs))
    print("제외된 공고 수:", len(df_unique_jobs) - len(df_filtered_jobs))

    display(df_filtered_jobs[["company_name", "job_title", "career", "location", "posted_date", "closing_date"]])

    # ----- 6) 공고별 매칭 이유 확인 (사람이 직접 검토) -----
    print("\n=== 공고별 매칭 키워드 (전체 공고 기준) ===")
    for _, row in df_unique_jobs.iterrows():
        matched = find_matched_keywords(row["job_title"])
        result = "통과" if matched else "제외"
        print(f"[{result}] {row['company_name']} | {row['job_title']}")
        print(f"        → 매칭 키워드: {matched if matched else '없음'}")

전체 공고 수: 5
1차 필터 통과 공고 수: 5
제외된 공고 수: 0

,company_name,job_title,career,location,posted_date,closing_date
0,GS리테일,"[GS리테일] 9·10월 통합공고(BIZ CLUB팀 경력사원, MD AX 담당, 물...",경력3년↑,서울 강남구 외 1,2026-09-21,2026-10-01 23:00
1,에스코어,AX 컨설턴트 채용,경력,서울 송파구,2026-07-01,2026-09-30 23:00
2,㈜NAVER,광고 프로덕트 기획 경력 채용(AX 광고 예산/과금 구조 설계 담당),경력,경기 성남시,2026-09-10,2026-09-29 10:00
3,㈜슈프리마,[슈프리마HQ] HRD & AX 담당자 모집,경력7년↑,경기 성남시,2026-08-26,2026-10-25 23:00
4,㈜NAVER,광고 프로덕트 기획 경력 채용(AX 광고 최적화 전략 담당),경력,경기 성남시,2026-09-10,2026-09-29 10:00

=== 공고별 매칭 키워드 (전체 공고 기준) ===
[통과] GS리테일 | [GS리테일] 9·10월 통합공고(BIZ CLUB팀 경력사원, MD AX 담당, 물류 AX 담당, 보안성 검토 담당)
        → 매칭 키워드: ['AX']
[통과] 에스코어 | AX 컨설턴트 채용
        → 매칭 키워드: ['AX']
[통과] ㈜NAVER | 광고 프로덕트 기획 경력 채용(AX 광고 예산/과금 구조 설계 담당)
        → 매칭 키워드: ['AX']
[통과] ㈜슈프리마 | [슈프리마HQ] HRD & AX 담당자 모집
        → 매칭 키워드: ['AX']
[통과] ㈜NAVER | 광고 프로덕트 기획 경력 채용(AX 광고 최적화 전략 담당)
        → 매칭 키워드: ['AX']

## 실행 결과 해석 / 분석 / 요약

- 셀이 에러 없이 실행되었다. (STEP 07-A → 07-B → 07-C → 07-F 순서로 실행)
- 전체 공고 수: 5
- 1차 필터 통과 공고 수: 5
- 제외된 공고 수: 0
- 사용한 필터 기준: `job_title`에 키워드 13개 중 하나라도 들어 있으면 통과 (소문자로 바꿔서 비교)
- 실제 매칭된 주요 키워드: **`AX` 하나뿐** — 5건 모두 `AX`로만 매칭되었고, 나머지 12개 키워드는 한 번도 매칭되지 않았다.
- 필터 결과 예시:

| company_name | 제목에서 매칭된 부분 | matched_keywords |
|---|---|---|
| GS리테일 | "MD **AX** 담당, 물류 **AX** 담당" | `['AX']` |
| 에스코어 | "**AX** 컨설턴트 채용" | `['AX']` |
| ㈜NAVER | "(**AX** 광고 예산/과금 구조 설계 담당)" | `['AX']` |
| ㈜슈프리마 | "HRD & **AX** 담당자 모집" | `['AX']` |
| ㈜NAVER | "(**AX** 광고 최적화 전략 담당)" | `['AX']` |

- 예상과 다른 부분: 없음. 검색어가 `ax`라서 전부 통과할 것으로 예상했고, 실제로 그랬다.
- 원본 보존: `df_unique_jobs`는 바뀌지 않았고 새 컬럼도 생기지 않았다. `matched_keywords`는 `df_filtered_jobs`에만 있다.
- 결과 DataFrame: `df_filtered_jobs` (5행 × 10열 = 기존 9개 컬럼 + `matched_keywords`)

해석 주의사항:
- 이번 결과는 **"1차 후보"**일 뿐이다. 제목에 `AX`가 있다고 우리가 원하는 AX 직무라는 뜻은 아니다.
  - 예: ㈜NAVER 2건은 "광고 프로덕트 기획" 직무이고, `AX`는 담당 업무 설명에 들어 있다.
  - 예: ㈜슈프리마는 "HRD & AX 담당자"로, 교육·인사(HRD)와 함께 묶인 직무이다.
- 반대로 제목에 키워드가 없어도 실제 업무는 AI/AX 관련일 수 있다. (이번에는 제목만 검사했다)
- 최종 의미 판단은 이후 Gemini 단계에서 한다.

한계 / 특이사항:
- 5건이 모두 통과해서 **"제외되는 경우"는 이번 데이터로 확인하지 못했다.** 검색어가 `ax` 하나라서 생긴 한계이다.
- 단순 포함 검색이라 짧은 키워드가 다른 단어 안에 들어 있어도 매칭될 수 있다.
  - 예: `ai`는 영어 단어 "m**ai**ntenance", "tr**ai**ning" 안에서도, `ax`는 "t**ax**", "m**ax**" 안에서도 매칭된다.
  - 이번 5건에서는 이런 잘못된 매칭이 없었지만, 검색어나 수집 범위를 넓히면 주의해야 한다.
- 키워드가 서로 겹친다. (예: `생성형 AI`, `AI Engineer`가 들어 있으면 `AI`도 함께 매칭된다) 통과 여부에는 영향이 없다.
- 다음 단계 진행 가능 여부: 사용자가 공고별 매칭 결과를 확인하면 진행 가능하다.

#### 초보자 설명
- `any()` → 여러 조건 중 **하나라도 True**인지 확인한다. 키워드 13개 중 하나만 들어 있어도 True가 된다.
- `apply()` → DataFrame/Series의 **각 값에 함수를 하나씩 적용**한다. 여기서는 공고 제목마다 `contains_relevance_keyword()`를 실행했다.
- `.copy()` → 필터링한 결과를 **원본과 분리된 새 DataFrame**으로 만든다. 그래서 `df_filtered_jobs`에 컬럼을 추가해도 `df_unique_jobs`는 바뀌지 않는다.

# STEP 07-G. 키워드 필터 오탐 검증 및 개선

## 작업 계획

STEP 07-F의 필터는 `keyword in title` 방식이다.
이 방식은 **글자가 포함되어 있는지만** 보기 때문에, 다른 단어 속에 우연히 들어간 글자도 매칭할 수 있다. (오탐 = false positive)
- 예: `ai` → "M**ai**ntenance", "Tr**ai**ning" / `ax` → "T**ax**", "M**ax**"

이번 단계에서는 **실데이터를 다시 크롤링하지 않고**, 직접 만든 테스트 제목으로 이 문제를 확인하고 매칭 규칙을 개선한다.
(STEP 07-F의 함수는 수정하지 않고, 새 함수 `find_matched_keywords_safe()`를 만든다)

테스트 제목:

| 구분 | 제목 | 기대 결과 |
|---|---|---|
| 매칭되어야 함 | AX 컨설턴트 채용 | True |
| 매칭되어야 함 | AI Engineer 모집 | True |
| 매칭되어야 함 | LLM 개발자 | True |
| 매칭되어야 함 | 생성형 AI 서비스 개발 | True |
| 매칭되어야 함 | 머신러닝 엔지니어 | True |
| 매칭되어야 함 | 데이터 분석 담당자 | True |
| 매칭되면 안 됨 | Tax Manager | False |
| 매칭되면 안 됨 | Max Performance Engineer | False |
| 매칭되면 안 됨 | Maintenance Engineer | False |
| 매칭되면 안 됨 | Training Manager | False |
| 추가 (한글이 바로 붙은 경우) | AX담당자 모집 | True |
| 추가 (한글이 바로 붙은 경우) | AI기반 서비스 기획 | True |

개선 방식 — 키워드 종류에 따라 검사 방법을 나눈다:
- **영문 키워드** (`AX`, `AI`, `LLM`, `Machine Learning`, `Data Scientist`, `AI Engineer`)
  → 정규식으로 "키워드 **앞뒤에 영문자·숫자가 붙어 있지 않을 때만**" 매칭한다.
  - `Tax`: `ax` 앞에 영문자 `T`가 붙어 있으므로 매칭 안 됨
  - `AX 담당`, `(AX`, `AX담당`: 앞뒤가 공백·괄호·한글이므로 매칭됨
- **한글이 들어 있는 키워드** (`인공지능`, `생성형 AI`, `생성형AI`, `머신러닝`, `데이터 분석`, `AI 엔지니어`, `데이터 사이언티스트`)
  → 기존처럼 포함 검색을 사용한다.

왜 흔히 쓰는 `\b`(단어 경계)를 그대로 쓰지 않는가:
- Python 정규식은 **한글도 "단어 글자"로 취급**한다.
- 그래서 `\bAX\b`는 `"AX 담당"`은 잡지만, 한글이 바로 붙은 `"AX담당"`은 놓친다.
- 이런 이유로 모든 키워드에 같은 정규식을 쓰지 않고, 영문 키워드에만 "영문자·숫자 경계"를 적용한다.
- 코드에서 기존 방식, `\b` 방식, 개선 방식을 나란히 비교해 확인한다.

실데이터 적용:
- `df_unique_jobs`가 **현재 메모리에 있을 때만** 새 함수를 적용해 `df_filtered_jobs_safe`에 저장한다.
- 없으면 데이터를 임의로 만들지 않고 안내만 출력한다.
- 원본 `df_unique_jobs`, `df_filtered_jobs`는 수정하지 않는다.

주의:
- 정규식이 직무 의미를 완벽히 판단해 주지는 않는다. 이번 목표는 **명백한 오탐(Tax / Max / Maintenance / Training)을 줄이는 것**이다.
- 직무 의미의 최종 판단은 이후 Gemini 단계에서 한다.

이번 단계에서 하지 않는 것:
- 웹 재요청, 크롤링 재실행, history 갱신
- Gemini API, 상세 페이지 수집, 점수화

완료 조건:
- 테스트 12개가 모두 기대 결과와 일치한다
- 기존 방식에서 오탐이 생기는 제목을 출력으로 확인한다

In [1]:
import re

# ----- 1) 키워드 (STEP 07-F와 같은 13개) -----
relevance_keywords = [
    "AX",
    "AI",
    "인공지능",
    "생성형 AI",
    "생성형AI",
    "LLM",
    "Machine Learning",
    "머신러닝",
    "Data Scientist",
    "데이터 사이언티스트",
    "AI Engineer",
    "AI 엔지니어",
    "데이터 분석",
]

# ----- 2) 테스트 데이터: (제목, 기대 결과) -----
test_titles = [
    ("AX 컨설턴트 채용", True),
    ("AI Engineer 모집", True),
    ("LLM 개발자", True),
    ("생성형 AI 서비스 개발", True),
    ("머신러닝 엔지니어", True),
    ("데이터 분석 담당자", True),
    ("Tax Manager", False),
    ("Max Performance Engineer", False),
    ("Maintenance Engineer", False),
    ("Training Manager", False),
    # 추가: 한글이 영문 키워드에 바로 붙은 경우 (\b 방식의 약점 확인용)
    ("AX담당자 모집", True),
    ("AI기반 서비스 기획", True),
]


# ----- 3) 기존 방식 (STEP 07-F와 같은 단순 포함 검색) — 비교용 -----
def find_matched_keywords_substring(title):
    title_lower = title.lower()
    return [k for k in relevance_keywords if k.lower() in title_lower]


# ----- 4) \b(단어 경계) 방식 — 비교용 -----
# Python에서는 한글도 "단어 글자"라서, "AX담당"처럼 한글이 바로 붙으면 경계로 인정되지 않는다
def find_matched_keywords_wordb(title):
    return [k for k in relevance_keywords
            if re.search(r"\b" + re.escape(k) + r"\b", title, re.IGNORECASE)]


# ----- 5) 개선 방식 -----
# 영문 키워드인지 확인: 알파벳·숫자·공백으로만 되어 있으면 영문 키워드로 본다
def is_english_keyword(keyword):
    return re.fullmatch(r"[A-Za-z0-9 ]+", keyword) is not None


def find_matched_keywords_safe(title):
    if not isinstance(title, str):
        return []
    matched = []
    for keyword in relevance_keywords:
        if is_english_keyword(keyword):
            # 영문 키워드: 앞뒤에 영문자·숫자가 "없을 때만" 매칭
            #   (?<![A-Za-z0-9]) → 바로 앞 글자가 영문자·숫자가 아니어야 함
            #   (?![A-Za-z0-9])  → 바로 뒤 글자가 영문자·숫자가 아니어야 함
            #   re.escape()      → 키워드 안의 특수문자를 글자 그대로 취급
            #   re.IGNORECASE    → 대소문자 구분 없이 비교
            pattern = r"(?<![A-Za-z0-9])" + re.escape(keyword) + r"(?![A-Za-z0-9])"
            if re.search(pattern, title, re.IGNORECASE):
                matched.append(keyword)
        else:
            # 한글이 들어 있는 키워드: 기존처럼 포함 검색
            if keyword.lower() in title.lower():
                matched.append(keyword)
    return matched


# ----- 6) 테스트 실행: 개선 방식이 기대 결과와 같은지 확인 -----
print("=== 개선 방식(find_matched_keywords_safe) 테스트 ===")
pass_count = 0
for title, expected in test_titles:
    matched = find_matched_keywords_safe(title)
    actual = len(matched) > 0
    result = "PASS" if actual == expected else "FAIL"
    if result == "PASS":
        pass_count += 1
    print(f"[{result}] {title}")
    print(f"    expected={expected}  actual={actual}  matched={matched}")
    if result == "FAIL":
        print("    → 실패 원인 확인 필요: 기대와 다른 키워드 매칭 결과")

print("\n전체 테스트:", len(test_titles))
print("통과:", pass_count)
print("실패:", len(test_titles) - pass_count)

# ----- 7) 세 방식 비교: 기존 방식에서 어떤 오탐/누락이 생기는지 확인 -----
print("\n=== 방식별 비교 (기대와 다르면 ✗) ===")
for title, expected in test_titles:
    row = []
    for name, func in [("기존 포함검색", find_matched_keywords_substring),
                       ("\\b 방식", find_matched_keywords_wordb),
                       ("개선 방식", find_matched_keywords_safe)]:
        matched = func(title)
        mark = "✓" if (len(matched) > 0) == expected else "✗"
        row.append(f"{name} {mark} {matched}")
    print(f"{title}  (기대={expected})")
    print("    " + " | ".join(row))

# ----- 8) 실데이터 적용 (df_unique_jobs가 메모리에 있을 때만) -----
print("\n=== 실데이터 적용 ===")
if "df_unique_jobs" not in globals():
    print("df_unique_jobs가 현재 메모리에 없어 실데이터 적용을 건너뜁니다.")
    print("실데이터에 적용하려면 STEP 07-A → 07-B → 07-C를 먼저 실행한 뒤 이 셀을 다시 실행하세요.")
else:
    safe_matches = df_unique_jobs["job_title"].apply(find_matched_keywords_safe)
    df_filtered_jobs_safe = df_unique_jobs[safe_matches.apply(len) > 0].copy()
    df_filtered_jobs_safe["matched_keywords"] = safe_matches[safe_matches.apply(len) > 0]

    print("전체 공고 수:", len(df_unique_jobs))
    print("개선 필터 통과 수:", len(df_filtered_jobs_safe))
    for title, company, matched in zip(df_unique_jobs["job_title"], df_unique_jobs["company_name"], safe_matches):
        print(f"[{'통과' if matched else '제외'}] {company} | {title}")
        print(f"        → 매칭 키워드: {matched if matched else '없음'}")

=== 개선 방식(find_matched_keywords_safe) 테스트 ===
[PASS] AX 컨설턴트 채용
    expected=True  actual=True  matched=['AX']
[PASS] AI Engineer 모집
    expected=True  actual=True  matched=['AI', 'AI Engineer']
[PASS] LLM 개발자
    expected=True  actual=True  matched=['LLM']
[PASS] 생성형 AI 서비스 개발
    expected=True  actual=True  matched=['AI', '생성형 AI']
[PASS] 머신러닝 엔지니어
    expected=True  actual=True  matched=['머신러닝']
[PASS] 데이터 분석 담당자
    expected=True  actual=True  matched=['데이터 분석']
[PASS] Tax Manager
    expected=False  actual=False  matched=[]
[PASS] Max Performance Engineer
    expected=False  actual=False  matched=[]
[PASS] Maintenance Engineer
    expected=False  actual=False  matched=[]
[PASS] Training Manager
    expected=False  actual=False  matched=[]
[PASS] AX담당자 모집
    expected=True  actual=True  matched=['AX']
[PASS] AI기반 서비스 기획
    expected=True  actual=True  matched=['AI']

전체 테스트: 12
통과: 12
실패: 0

=== 방식별 비교 (기대와 다르면 ✗) ===
AX 컨설턴트 채용  (기대=True)
    기존 포함검색 ✓ ['AX'] | \b 방식 ✓ ['AX'] | 개선 방식 ✓ ['AX']
AI Engineer 모집  (기대=True)
    기존 포함검색 ✓ ['AI', 'AI Engineer'] | \b 방식 ✓ ['AI', 'AI Engineer'] | 개선 방식 ✓ ['AI', 'AI Engineer']
LLM 개발자  (기대=True)
    기존 포함검색 ✓ ['LLM'] | \b 방식 ✓ ['LLM'] | 개선 방식 ✓ ['LLM']
생성형 AI 서비스 개발  (기대=True)
    기존 포함검색 ✓ ['AI', '생성형 AI'] | \b 방식 ✓ ['AI', '생성형 AI'] | 개선 방식 ✓ ['AI', '생성형 AI']
머신러닝 엔지니어  (기대=True)
    기존 포함검색 ✓ ['머신러닝'] | \b 방식 ✓ ['머신러닝'] | 개선 방식 ✓ ['머신러닝']
데이터 분석 담당자  (기대=True)
    기존 포함검색 ✓ ['데이터 분석'] | \b 방식 ✓ ['데이터 분석'] | 개선 방식 ✓ ['데이터 분석']
Tax Manager  (기대=False)
    기존 포함검색 ✗ ['AX'] | \b 방식 ✓ [] | 개선 방식 ✓ []
Max Performance Engineer  (기대=False)
    기존 포함검색 ✗ ['AX'] | \b 방식 ✓ [] | 개선 방식 ✓ []
Maintenance Engineer  (기대=False)
    기존 포함검색 ✗ ['AI'] | \b 방식 ✓ [] | 개선 방식 ✓ []
Training Manager  (기대=False)
    기존 포함검색 ✗ ['AI'] | \b 방식 ✓ [] | 개선 방식 ✓ []
AX담당자 모집  (기대=True)
    기존 포함검색 ✓ ['AX'] | \b 방식 ✗ [] | 개선 방식 ✓ ['AX']
AI기반 서비스 기획  (기대=True)
    기존 포함검색 ✓ ['AI'] | \b 방식 ✗ [] | 개선 방식 ✓ ['AI']

=== 실데이터 적용 ===
df_unique_jobs가 현재 메모리에 없어 실데이터 적용을 건너뜁니다.
실데이터에 적용하려면 STEP 07-A → 07-B → 07-C를 먼저 실행한 뒤 이 셀을 다시 실행하세요.

## 실행 결과 해석 / 분석 / 요약

- 셀이 에러 없이 실행되었다. (웹 요청 없음, 테스트 데이터만 사용)
- 테스트 케이스 수: 12 (요청된 10개 + 한글이 바로 붙은 경우 2개)
- 기대 결과와 일치한 수: 12
- 실패 수: 0

방식별 비교 결과:

| 제목 | 기대 | 기존 포함검색 | `\b` 방식 | 개선 방식 |
|---|---|---|---|---|
| Tax Manager | False | ✗ `['AX']` 오탐 | ✓ | ✓ |
| Max Performance Engineer | False | ✗ `['AX']` 오탐 | ✓ | ✓ |
| Maintenance Engineer | False | ✗ `['AI']` 오탐 | ✓ | ✓ |
| Training Manager | False | ✗ `['AI']` 오탐 | ✓ | ✓ |
| AX담당자 모집 | True | ✓ | ✗ 누락 | ✓ `['AX']` |
| AI기반 서비스 기획 | True | ✓ | ✗ 누락 | ✓ `['AI']` |
| 나머지 6개 (AX 컨설턴트 채용 등) | True | ✓ | ✓ | ✓ |

- 기존 substring 방식의 문제: 글자 포함 여부만 보기 때문에 `Tax`/`Max` 안의 `ax`, `Maintenance`/`Training` 안의 `ai`까지 매칭했다. → **4건 오탐**
- `\b` 방식의 문제: 오탐은 없앴지만, Python에서는 한글도 단어 글자로 취급되어 `AX담당자`, `AI기반`처럼 한글이 바로 붙은 경우를 놓쳤다. → **2건 누락**
- 개선 방식:
  - 영문 키워드(`AX`, `AI`, `LLM`, `Machine Learning`, `Data Scientist`, `AI Engineer`)는
    "앞뒤에 **영문자·숫자**가 붙어 있지 않을 때만" 매칭한다. (`(?<![A-Za-z0-9])키워드(?![A-Za-z0-9])`, 대소문자 무시)
  - 한글이 들어 있는 키워드는 기존처럼 포함 검색을 사용한다.
  - → 오탐 4건, 누락 2건 모두 해결
- Tax 오탐 여부: 없음 (개선 방식)
- Max 오탐 여부: 없음
- Maintenance 오탐 여부: 없음
- Training 오탐 여부: 없음

실데이터 적용:
- 실데이터 5건 필터 결과: **이번 실행에서는 적용하지 않았다.**
  - 이번 작업은 웹 재요청이 금지라서 STEP 07-A를 실행하지 않았고, 그래서 `df_unique_jobs`가 메모리에 없었다.
  - 코드는 데이터를 임의로 만들지 않고 "건너뜁니다" 안내만 출력했다.
  - 참고: history 파일의 실제 제목 5개를 **읽기만 해서** 새 함수에 넣어 보면 5건 모두 `['AX']`로 매칭된다. (기존 07-F 결과와 동일, 이 확인은 Notebook에 저장하지 않음)
- `df_unique_jobs` 원본 보존 여부: 이번 셀은 `df_unique_jobs`를 읽기만 하도록 작성했다. (이번 실행에서는 메모리에 없었음)
- `df_filtered_jobs_safe` 생성 여부: 이번 실행에서는 생성되지 않았다. STEP 07-A → 07-B → 07-C 실행 후 이 셀을 다시 실행하면 생성된다.
- `df_filtered_jobs`(STEP 07-F 결과)와 STEP 07-F 함수는 수정하지 않았다.

한계:
- 정규식은 글자 모양만 검사할 뿐 **직무 의미를 판단하지 않는다.** 이번 목표는 명백한 오탐(Tax / Max / Maintenance / Training)을 줄이는 것이었다.
- `OpenAI`처럼 영문자가 붙은 표현은 이제 `AI`로 매칭되지 않는다. 필요하면 키워드를 따로 추가해야 한다.
- 직무 의미의 최종 판단은 이후 Gemini 단계에서 한다.
- 다음 단계 진행 가능 여부: 사용자가 실데이터에 적용한 결과(`df_filtered_jobs_safe`)까지 확인하면 진행 가능하다.

#### 초보자 설명
- **substring**(부분 문자열) → 단순히 **글자가 포함되어 있는지만** 확인한다. `"ax" in "tax"`도 True가 된다.
- **regex**(정규식) → 문자열 **패턴을 더 구체적으로** 검사할 수 있다. 예: "앞 글자가 영문자가 아닐 것"
- **word boundary**(`\b`, 단어 경계) → 독립된 단어인지 구분할 때 도움이 된다.
  하지만 Python에서는 한글도 단어 글자로 보기 때문에, 한글 제목에서는 이번처럼 "영문자·숫자 경계"를 직접 지정하는 편이 더 정확하다.

# STEP 07-H. Gemini API 환경변수 준비

## 작업 계획

이번 단계에서는 **Gemini API를 호출하지 않는다.**
다음 단계에서 Gemini를 쓰기 전에, API 키를 안전하게 보관하고 읽어 오는 준비만 한다.

왜 필요한가:
- API Key는 **비밀번호와 비슷한 민감정보**이다.
- Notebook 코드에 직접 적으면, Notebook을 Git에 올리거나 다른 사람에게 공유할 때 키가 그대로 노출된다.
- 그래서 키는 코드가 아니라 **`.env` 파일**에 따로 저장하고, 코드에서는 이름(`GEMINI_API_KEY`)으로만 읽어 온다.

목표:
- API 키를 코드에 직접 쓰지 않기
- `.env`에 비밀값 저장 (사용자가 직접 작성)
- `python-dotenv`의 `load_dotenv()`로 환경변수 읽기
- Notebook에서 `GEMINI_API_KEY`가 **있는지 없는지만** 확인 (값은 출력하지 않는다)

준비된 파일 (프로젝트 루트 `chapter11/ax-job-agent/`):
- `.env.example` → 필요한 환경변수 이름만 적어 둔 샘플 (Git에 포함)
- `.gitignore` → `.env`, `.venv/`, `__pycache__/`, `.ipynb_checkpoints/`를 Git에서 제외
- `.env` → **사용자가 직접 만든다.** (Claude Code는 이 파일을 만들거나 값을 넣지 않는다)

코드에서 하는 일:
- Notebook은 `notebooks/` 폴더에서 실행되므로, 한 단계 위를 프로젝트 루트로 보고 `.env`를 찾는다.
- `.env`가 있으면 불러오고, 없으면 오류로 멈추지 않고 만드는 방법을 안내한다.
- 키는 "설정됨 / 미설정"으로만 출력한다. (키 값, 키 길이, 앞뒤 일부도 출력하지 않는다)

이번 단계에서 하지 않는 것:
- Gemini API 호출, API Key 생성·입력
- Slack / Gmail, 새 패키지 설치, 크롤링 재실행

성공 기준:
- `.env.example`이 있다
- `.gitignore`에서 `.env`가 제외된다
- Notebook에서 `.env`를 찾고 `GEMINI_API_KEY` 설정 여부를 확인할 수 있다
- 실제 키 값은 화면에 출력되지 않는다

In [9]:
from pathlib import Path
import os
from dotenv import load_dotenv

# ----- 1) 프로젝트 루트의 .env 경로 찾기 -----
# Notebook은 notebooks/ 폴더에서 실행되므로, 그 경우 한 단계 위를 프로젝트 루트로 사용한다
current_dir = Path.cwd()
project_root = current_dir.parent if current_dir.name == "notebooks" else current_dir
env_path = project_root / ".env"

print("프로젝트 루트:", project_root)
print(".env 파일 존재 여부:", env_path.exists())

# ----- 2) .env가 있으면 불러오기 -----
# load_dotenv(): .env 파일의 "이름=값"을 읽어서 Python 환경변수로 등록한다
if env_path.exists():
    load_dotenv(env_path)
else:
    print("\n.env 파일이 없습니다.")
    print("프로젝트 루트에 .env 파일을 만들고")
    print("GEMINI_API_KEY=본인의_API_키")
    print("형태로 입력하세요. (.env.example 파일을 복사해서 만들면 편합니다)")

# ----- 3) GEMINI_API_KEY 설정 여부만 확인 (값은 절대 출력하지 않는다) -----
gemini_api_key = os.getenv("GEMINI_API_KEY")
print("\nGEMINI_API_KEY 설정 여부:", "설정됨" if gemini_api_key else "미설정")

# 참고: .env가 없는데 "설정됨"이면, Windows 시스템 환경변수에 이미 등록된 값이다
if gemini_api_key and not env_path.exists():
    print("(참고: .env가 아니라 시스템 환경변수에서 읽은 값입니다)")

프로젝트 루트: c:\dev\claude-code-agent-course\chapter11\ax-job-agent
.env 파일 존재 여부: True

GEMINI_API_KEY 설정 여부: 설정됨

## 실행 결과 해석 / 분석 / 요약

- 셀이 에러 없이 실행되었다. (Gemini API 호출 없음, 웹 요청 없음)
- 프로젝트 루트 계산: `notebooks/`에서 실행 → 한 단계 위인 `chapter11/ax-job-agent`를 정상적으로 찾았다.
- `.env` 파일 존재 여부: **없음** — 아직 사용자가 만들지 않은 상태이다. 코드는 오류로 멈추지 않고 만드는 방법을 안내했다.
- `GEMINI_API_KEY` 설정 여부: **미설정** — `.env`가 없고, 시스템 환경변수에도 등록되어 있지 않다.
- API Key 값이 화면에 노출됐는지: **노출되지 않음** — 코드는 "설정됨 / 미설정"만 출력하고, 키 값·길이·일부 글자는 출력하지 않는다.
- `.env`가 Git 제외 대상인지: **예** — 프로젝트 루트 `.gitignore`에 `.env`를 추가했고, `git check-ignore`로 제외되는 것을 확인했다.
  (`.venv/`, `__pycache__/`, `.ipynb_checkpoints/`도 함께 제외)
- `.env.example` 존재 여부: **있음** — `GEMINI_API_KEY`, `SLACK_WEBHOOK_URL`, `GMAIL_USER`, `GMAIL_APP_PASSWORD` 이름만 빈 값으로 들어 있다. 이 파일은 Git에 포함된다.
- 다음 단계 진행 가능 여부: 준비 작업(파일·코드)은 완료되었다.
  사용자가 `.env`를 직접 만들고 키를 입력한 뒤, 이 셀을 다시 실행해 **"설정됨"**이 나오면 Gemini 연동 단계로 진행할 수 있다.

#### 사용자가 직접 할 일
1. 프로젝트 루트(`chapter11/ax-job-agent/`)에서 `.env.example`을 복사해 이름을 `.env`로 바꾼다.
2. `GEMINI_API_KEY=` 뒤에 본인의 API 키를 붙여 넣는다. (따옴표·공백 없이)
3. 이 셀을 다시 실행해 `.env 파일 존재 여부: True`, `GEMINI_API_KEY 설정 여부: 설정됨`인지 확인한다.

#### 초보자 설명
- `.env` → 실제 비밀값을 저장하는 **로컬 파일**이다. 내 컴퓨터에만 두고 Git에는 올리지 않는다.
- `.env.example` → 어떤 환경변수가 필요한지 보여 주는 **샘플 파일**이다. 값은 비워 두고 Git에 올린다.
- `.gitignore` → Git에 **올리지 않을 파일**을 지정하는 파일이다.
- `load_dotenv()` → `.env`의 값을 **Python 환경변수로 읽어 오는** 기능이다. 이후 `os.getenv("이름")`으로 꺼내 쓴다.

# STEP 07-I. Gemini API 최소 연결 테스트

## 작업 계획

STEP 07-H에서는 `GEMINI_API_KEY`가 **있는지**만 확인했다.
이번 단계에서는 그 키로 **실제로 Gemini API를 1번 호출**해서, 연결이 정상인지 확인한다.

이번 단계 목적:
- `GEMINI_API_KEY`가 실제 API 호출에 사용 가능한지 확인
- Gemini 서버와 통신이 되는지 확인
- 응답 텍스트를 정상적으로 받을 수 있는지 확인

사용 도구:
- Google 공식 Python SDK **`google-genai`** (`from google import genai`)
  - 예전 패키지인 `google-generativeai`는 사용하지 않는다.
- 모델: `gemini-3.6-flash` (Flash 계열)
  - 이 모델을 쓸 수 없다는 오류가 나오면, 다른 모델을 여러 번 시도하지 않고 오류를 기록한 뒤 사용 가능한 모델을 확인한다.

보내는 내용:
- 아주 짧은 연결 테스트 문장 **1개만** 보낸다. (비용과 호출 횟수를 최소화)

보안 원칙:
- API 키 값, 키 일부, 키 길이, `.env` 내용은 **절대 출력하지 않는다.**
- 오류가 나면 오류 종류와 메시지만 출력하되, 메시지 안에 키가 섞여 있을 경우를 대비해 키 부분은 `***`로 가린다.

아직 하지 않는 것:
- 채용공고 5건 요약
- 반복 호출
- JSON 구조화
- 비용이 커질 수 있는 긴 프롬프트
- 상세 페이지 내용 전달
- Slack / Gmail 연동

성공 기준:
- API 호출 오류 없음
- Gemini가 짧은 텍스트 응답을 반환
- API 키가 화면에 출력되지 않음

In [1]:
from pathlib import Path
import os
from dotenv import load_dotenv
from google import genai

# ----- 1) 프로젝트 루트의 .env 읽기 (STEP 07-H와 같은 방식) -----
current_dir = Path.cwd()
project_root = current_dir.parent if current_dir.name == "notebooks" else current_dir
env_path = project_root / ".env"

print(".env 파일 존재 여부:", env_path.exists())
if env_path.exists():
    load_dotenv(env_path)

# ----- 2) API 키 확인 (값은 절대 출력하지 않는다) -----
gemini_api_key = os.getenv("GEMINI_API_KEY")
print("GEMINI_API_KEY 설정 여부:", "설정됨" if gemini_api_key else "미설정")

MODEL_NAME = "gemini-3.6-flash"

if not gemini_api_key:
    print("\nGEMINI_API_KEY가 없어 API를 호출하지 않습니다.")
    print("프로젝트 루트의 .env 파일에 GEMINI_API_KEY=본인의_API_키 를 입력한 뒤 다시 실행하세요.")
else:
    # ----- 3) Gemini Client 생성 -----
    # client: Gemini API에 요청을 보내기 위한 연결 객체
    client = genai.Client(api_key=gemini_api_key)

    # ----- 4) 아주 짧은 프롬프트 1개만 전송 -----
    test_prompt = (
        "연결 테스트입니다. "
        "한국어로 'Gemini API 연결 성공'이라고 짧게 답해 주세요."
    )
    print("\n사용 모델:", MODEL_NAME)

    try:
        # generate_content(): 프롬프트를 보내고 응답을 받는 함수 (이 셀에서 1번만 호출)
        response = client.models.generate_content(
            model=MODEL_NAME,
            contents=test_prompt,
        )
        # response.text: Gemini가 만든 텍스트 결과
        print("\nGemini 응답:")
        print(response.text)
    except Exception as e:
        # 오류 메시지 안에 혹시 키가 들어 있으면 *** 로 가린 뒤 출력한다
        safe_message = str(e).replace(gemini_api_key, "***")
        print("\nGemini API 호출 실패")
        print("오류 종류:", type(e).__name__)
        print("오류 메시지:", safe_message[:500])

Direct use of automatic function calling (AFC) in Models.generate_content is not recommended. Instead, we recommend to use AFC in Chat.send_message. Similarly, direct use of AFC in Models.generate_content_stream is not recommended. Instead, we recommend to use AFC in Chat.send_message_stream.

.env 파일 존재 여부: True
GEMINI_API_KEY 설정 여부: 설정됨

사용 모델: gemini-3.6-flash

Gemini 응답:
Gemini API 연결 성공

## 실행 결과 해석 / 분석 / 요약

- 셀이 에러 없이 실행되었다. (API 호출 **1회**)
- google-genai 설치 여부: **설치됨** — 이번 STEP에서 프로젝트 가상환경에 `google-genai` 2.25.0을 설치했다. (구버전 `google-generativeai`는 사용하지 않음)
- .env 로드 여부: **로드됨** — 프로젝트 루트의 `.env`를 찾아 `load_dotenv()`로 읽었다.
- GEMINI_API_KEY 설정 여부: **설정됨**
- 사용한 모델: `gemini-3.6-flash`
- API 호출 성공 여부: **성공**
- 응답 텍스트 수신 여부: **수신됨** — 응답: `Gemini API 연결 성공`
- API 키 노출 여부: **노출되지 않음** — 출력에는 "설정됨"만 표시되고, 저장된 셀 출력에 키 문자열이 없는 것도 확인했다.
- 오류가 있었다면 오류 종류: 오류 없음.
  - 참고: 출력 맨 위의 `Direct use of automatic function calling (AFC) ...` 문구는 오류가 아니라 SDK가 보여 주는 **안내(경고) 메시지**이다.
    AFC는 Gemini가 Python 함수를 대신 호출하게 하는 기능인데, 이번 호출에서는 사용하지 않았으므로 결과에 영향이 없다.
- 다음 단계 진행 가능 여부: **진행 가능** — `.env → 키 로드 → Client 생성 → 짧은 프롬프트 1회 → response.text 수신` 흐름이 실제로 동작했다.

주의:
- 이 셀을 실행할 때마다 API가 1번 호출된다. 불필요하게 반복 실행하지 않는다.
- 채용공고 요약처럼 긴 내용을 보내는 작업은 다음 단계에서 호출 횟수와 입력 길이를 정해 진행한다.

#### 초보자 설명
- `client` → Gemini API에 요청을 보내기 위한 **연결 객체**이다. API 키를 넣어 한 번 만들어 두고 계속 사용한다.
- `generate_content()` → 프롬프트를 보내고 **응답을 받는 함수**이다. `model`에 사용할 모델, `contents`에 보낼 내용을 넣는다.
- `response.text` → Gemini가 생성한 **텍스트 결과**이다.